using System.Data;
using Ams.Application.Abstractions.Persistence;
using Ams.Application.Common.Dtos;
using Ams.Application.Features.Billing;
using Dapper;

namespace Ams.Infrastructure.Persistence.Repositories;

public sealed class AgencyBillRepository(ISqlConnectionFactory connectionFactory) : IAgencyBillRepository
{
    public async Task<AgencyBillWorkspaceDto> GetWorkspaceAsync(Guid tenantId, CancellationToken cancellationToken = default)
    {
        const string sql = """
SELECT AgencyBillOptionId,TenantId,OptionGroupCode,OptionCode,DisplayName,Description,NumericValue,IsDefault,IsActive,SortOrder FROM Billing.AgencyBillOption WHERE TenantId=@TenantId AND IsDeleted=0 AND IsActive=1 ORDER BY OptionGroupCode,SortOrder,DisplayName;
SELECT AgencyBillReceivableId,TenantId,ReceivableNumber,SourceTypeCode,SourceInvoiceId,PolicyId,PolicyTermId,AccountId,CarrierId,BillingTypeCode,CurrencyCode,TransactionDate,DueDate,OriginalAmount,AllocatedAmount,AdjustedAmount,BalanceAmount,StatusCode,DelinquencyStageCode,FinanceCompanyId,Notes,CreatedDateUtc FROM Billing.AgencyBillReceivable WHERE TenantId=@TenantId AND IsDeleted=0 ORDER BY DueDate,ReceivableNumber;
SELECT AgencyBillInstallmentId,TenantId,AgencyBillReceivableId,InstallmentNumber,DueDate,InstallmentAmount,AllocatedAmount,BalanceAmount,StatusCode,GraceDate FROM Billing.AgencyBillInstallment WHERE TenantId=@TenantId AND IsDeleted=0 ORDER BY DueDate,InstallmentNumber;
SELECT AgencyBillPaymentAllocationId,TenantId,PaymentId,AgencyBillReceivableId,AgencyBillInstallmentId,AllocationAmount,AllocationDateUtc,StatusCode,ReversalOfAllocationId,Notes FROM Billing.AgencyBillPaymentAllocation WHERE TenantId=@TenantId AND IsDeleted=0 ORDER BY AllocationDateUtc DESC;
SELECT PremiumTrustTransactionId,TenantId,TrustAccountCode,TransactionTypeCode,AgencyBillReceivableId,PaymentId,PaymentAllocationId,TransactionDate,Amount,DirectionCode,ReferenceNumber,StatusCode,ReversalOfTransactionId FROM Billing.PremiumTrustTransaction WHERE TenantId=@TenantId AND IsDeleted=0 ORDER BY TransactionDate DESC,CreatedDateUtc DESC;
SELECT AgencyBillLateNoticeId,TenantId,AgencyBillReceivableId,AgencyBillInstallmentId,NoticeLevelCode,NoticeDateUtc,DeliveryMethodCode,RecipientAddress,AmountDue,DueDate,StatusCode,DeliveryReference FROM Billing.AgencyBillLateNotice WHERE TenantId=@TenantId AND IsDeleted=0 ORDER BY NoticeDateUtc DESC;
SELECT NonPaymentCancellationReferralId,TenantId,ReferralNumber,AgencyBillReceivableId,PolicyId,PolicyCancellationId,ReferralDateUtc,RequestedEffectiveDate,AmountDue,StatusCode,ReviewNotes,ReviewedDateUtc,ReviewedByUserId FROM Billing.NonPaymentCancellationReferral WHERE TenantId=@TenantId AND IsDeleted=0 ORDER BY ReferralDateUtc DESC;
SELECT AgencyBillReconciliationId,TenantId,ReconciliationNumber,StatementReference,StatementDate,PeriodStartDate,PeriodEndDate,StatementAmount,SubledgerAmount,VarianceAmount,StatusCode,CompletedDateUtc FROM Billing.AgencyBillReconciliation WHERE TenantId=@TenantId AND IsDeleted=0 ORDER BY StatementDate DESC;
SELECT FinanceCompanyId,TenantId,CompanyCode,CompanyName,ContactName,EmailAddress,PhoneNumber,RemittanceInstructions,IsActive FROM Billing.FinanceCompany WHERE TenantId=@TenantId AND IsDeleted=0 ORDER BY CompanyName;
SELECT FinanceAgreementId,TenantId,AgencyBillReceivableId,FinanceCompanyId,AgreementNumber,FinancedAmount,DownPaymentAmount,FundingStatusCode,ExpectedFundingDate,FundedDate,CancellationProtectionDate,StatusCode FROM Billing.FinanceAgreement WHERE TenantId=@TenantId AND IsDeleted=0 ORDER BY CreatedDateUtc DESC;
SELECT COALESCE(SUM(OriginalAmount+AdjustedAmount),0) TotalReceivable,COALESCE(SUM(AllocatedAmount),0) TotalAllocated,COALESCE(SUM(BalanceAmount),0) OpenBalance,(SELECT COALESCE(SUM(CASE DirectionCode WHEN N'Credit' THEN Amount ELSE -Amount END),0) FROM Billing.PremiumTrustTransaction WHERE TenantId=@TenantId AND IsDeleted=0 AND StatusCode=N'Posted') PremiumTrustBalance,(SELECT COALESCE(SUM(VarianceAmount),0) FROM Billing.AgencyBillReconciliation WHERE TenantId=@TenantId AND IsDeleted=0 AND StatusCode<>N'Completed') ReconciliationVariance,SUM(CASE WHEN BalanceAmount>0 AND DueDate<CONVERT(date,SYSUTCDATETIME()) THEN 1 ELSE 0 END) PastDueCount,(SELECT COUNT(1) FROM Billing.AgencyBillLateNotice WHERE TenantId=@TenantId AND IsDeleted=0 AND StatusCode IN(N'Prepared',N'Queued')) OpenLateNoticeCount,(SELECT COUNT(1) FROM Billing.NonPaymentCancellationReferral WHERE TenantId=@TenantId AND IsDeleted=0 AND StatusCode=N'PendingReview') PendingReferralCount,(SELECT COUNT(1) FROM Billing.FinanceAgreement WHERE TenantId=@TenantId AND IsDeleted=0 AND FundingStatusCode=N'Pending' AND StatusCode=N'Active') PendingFinanceAgreementCount FROM Billing.AgencyBillReceivable WHERE TenantId=@TenantId AND IsDeleted=0;
""";
        using var cn = await connectionFactory.CreateOpenConnectionAsync(cancellationToken);
        using var multi = await cn.QueryMultipleAsync(new CommandDefinition(sql, new { TenantId = tenantId }, cancellationToken: cancellationToken));
        var options = (await multi.ReadAsync<AgencyBillOptionDto>()).AsList();
        var receivables = (await multi.ReadAsync<AgencyBillReceivableDto>()).AsList();
        var installments = (await multi.ReadAsync<AgencyBillInstallmentDto>()).AsList();
        var allocations = (await multi.ReadAsync<AgencyBillPaymentAllocationDto>()).AsList();
        var trust = (await multi.ReadAsync<PremiumTrustTransactionDto>()).AsList();
        var notices = (await multi.ReadAsync<AgencyBillLateNoticeDto>()).AsList();
        var referrals = (await multi.ReadAsync<NonPaymentCancellationReferralDto>()).AsList();
        var reconciliations = (await multi.ReadAsync<AgencyBillReconciliationDto>()).AsList();
        var companies = (await multi.ReadAsync<FinanceCompanyDto>()).AsList();
        var agreements = (await multi.ReadAsync<FinanceAgreementDto>()).AsList();
        var summary = await multi.ReadSingleAsync<AgencyBillSummaryDto>();
        return new(options, receivables, installments, allocations, trust, notices, referrals, reconciliations, companies, agreements, summary);
    }

    public async Task<AgencyBillSynchronizationResultDto> SynchronizeAsync(SynchronizeAgencyBillRequest request, CancellationToken cancellationToken = default)
    {
        const string sql = """
SET XACT_ABORT ON; BEGIN TRAN;
DECLARE @R INT=0,@I INT=0,@A INT=0,@T INT=0;
INSERT Billing.AgencyBillReceivable(AgencyBillReceivableId,TenantId,ReceivableNumber,SourceTypeCode,SourceInvoiceId,AccountId,BillingTypeCode,CurrencyCode,TransactionDate,DueDate,OriginalAmount,AllocatedAmount,AdjustedAmount,StatusCode,DelinquencyStageCode,CreatedDateUtc,CreatedByUserId,IsDeleted)
SELECT NEWID(),i.TenantId,CONCAT(N'ABR-',i.InvoiceNumber),N'BillingInvoice',i.InvoiceId,i.AccountId,N'AgencyBill',N'USD',CONVERT(date,i.CreatedDateUtc),DATEADD(day,30,CONVERT(date,i.CreatedDateUtc)),i.TotalAmount,CASE WHEN i.BalanceAmount BETWEEN 0 AND i.TotalAmount THEN i.TotalAmount-i.BalanceAmount ELSE 0 END,0,CASE WHEN i.BalanceAmount<=0 THEN N'Paid' WHEN i.BalanceAmount<i.TotalAmount THEN N'PartiallyPaid' ELSE N'Open' END,N'Current',COALESCE(i.CreatedDateUtc,SYSUTCDATETIME()),@UserId,0
FROM Billing.Invoice i WHERE i.TenantId=@TenantId AND i.IsDeleted=0 AND i.TotalAmount>=0 AND (@FromDate IS NULL OR CONVERT(date,i.CreatedDateUtc)>=@FromDate) AND (@ThroughDate IS NULL OR CONVERT(date,i.CreatedDateUtc)<=@ThroughDate) AND NOT EXISTS(SELECT 1 FROM Billing.AgencyBillReceivable r WHERE r.TenantId=i.TenantId AND r.SourceInvoiceId=i.InvoiceId AND r.IsDeleted=0); SET @R=@@ROWCOUNT;
INSERT Billing.AgencyBillInstallment(AgencyBillInstallmentId,TenantId,AgencyBillReceivableId,InstallmentNumber,DueDate,InstallmentAmount,AllocatedAmount,StatusCode,GraceDate,CreatedDateUtc,CreatedByUserId,IsDeleted)
SELECT NEWID(),r.TenantId,r.AgencyBillReceivableId,1,r.DueDate,r.OriginalAmount,r.AllocatedAmount,CASE WHEN r.BalanceAmount<=0 THEN N'Paid' WHEN r.AllocatedAmount>0 THEN N'PartiallyPaid' WHEN r.DueDate<CONVERT(date,SYSUTCDATETIME()) THEN N'PastDue' ELSE N'Scheduled' END,DATEADD(day,10,r.DueDate),SYSUTCDATETIME(),@UserId,0 FROM Billing.AgencyBillReceivable r WHERE r.TenantId=@TenantId AND r.IsDeleted=0 AND NOT EXISTS(SELECT 1 FROM Billing.AgencyBillInstallment i WHERE i.AgencyBillReceivableId=r.AgencyBillReceivableId AND i.IsDeleted=0); SET @I=@@ROWCOUNT;
INSERT Billing.AgencyBillPaymentAllocation(AgencyBillPaymentAllocationId,TenantId,PaymentId,AgencyBillReceivableId,AgencyBillInstallmentId,AllocationAmount,StatusCode,Notes,CreatedDateUtc,CreatedByUserId,IsDeleted)
SELECT NEWID(),p.TenantId,p.PaymentId,r.AgencyBillReceivableId,i.AgencyBillInstallmentId,CASE WHEN pa.AppliedAmount>r.BalanceAmount THEN r.BalanceAmount ELSE pa.AppliedAmount END,N'Applied',N'Synchronized from invoice payment application.',SYSUTCDATETIME(),@UserId,0 FROM Billing.Payment p JOIN Billing.PaymentApplication pa ON pa.PaymentId=p.PaymentId JOIN Billing.AgencyBillReceivable r ON r.TenantId=p.TenantId AND r.SourceInvoiceId=pa.InvoiceId AND r.IsDeleted=0 OUTER APPLY(SELECT TOP 1 AgencyBillInstallmentId FROM Billing.AgencyBillInstallment x WHERE x.AgencyBillReceivableId=r.AgencyBillReceivableId AND x.IsDeleted=0 ORDER BY InstallmentNumber)i WHERE p.TenantId=@TenantId AND p.IsDeleted=0 AND pa.AppliedAmount>0 AND r.BalanceAmount>0 AND NOT EXISTS(SELECT 1 FROM Billing.AgencyBillPaymentAllocation a WHERE a.TenantId=p.TenantId AND a.PaymentId=p.PaymentId AND a.AgencyBillReceivableId=r.AgencyBillReceivableId AND a.StatusCode=N'Applied' AND a.IsDeleted=0); SET @A=@@ROWCOUNT;
UPDATE r SET AllocatedAmount=x.Amount,StatusCode=CASE WHEN r.OriginalAmount+r.AdjustedAmount-x.Amount<=0 THEN N'Paid' WHEN x.Amount>0 THEN N'PartiallyPaid' ELSE N'Open' END,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId FROM Billing.AgencyBillReceivable r CROSS APPLY(SELECT COALESCE(SUM(CASE WHEN a.StatusCode=N'Applied' THEN a.AllocationAmount ELSE -a.AllocationAmount END),0) Amount FROM Billing.AgencyBillPaymentAllocation a WHERE a.AgencyBillReceivableId=r.AgencyBillReceivableId AND a.IsDeleted=0)x WHERE r.TenantId=@TenantId AND r.IsDeleted=0;
UPDATE i SET AllocatedAmount=x.Amount,StatusCode=CASE WHEN i.InstallmentAmount-x.Amount<=0 THEN N'Paid' WHEN x.Amount>0 THEN N'PartiallyPaid' WHEN i.DueDate<CONVERT(date,SYSUTCDATETIME()) THEN N'PastDue' ELSE N'Scheduled' END,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId FROM Billing.AgencyBillInstallment i CROSS APPLY(SELECT COALESCE(SUM(CASE WHEN a.StatusCode=N'Applied' THEN a.AllocationAmount ELSE -a.AllocationAmount END),0) Amount FROM Billing.AgencyBillPaymentAllocation a WHERE a.AgencyBillInstallmentId=i.AgencyBillInstallmentId AND a.IsDeleted=0)x WHERE i.TenantId=@TenantId AND i.IsDeleted=0;
INSERT Billing.PremiumTrustTransaction(PremiumTrustTransactionId,TenantId,TrustAccountCode,TransactionTypeCode,AgencyBillReceivableId,PaymentId,PaymentAllocationId,TransactionDate,Amount,DirectionCode,StatusCode,CreatedDateUtc,CreatedByUserId,IsDeleted) SELECT NEWID(),a.TenantId,N'PREMIUM_TRUST',N'PremiumReceipt',a.AgencyBillReceivableId,a.PaymentId,a.AgencyBillPaymentAllocationId,CONVERT(date,a.AllocationDateUtc),a.AllocationAmount,N'Credit',N'Posted',SYSUTCDATETIME(),@UserId,0 FROM Billing.AgencyBillPaymentAllocation a WHERE a.TenantId=@TenantId AND a.StatusCode=N'Applied' AND a.IsDeleted=0 AND NOT EXISTS(SELECT 1 FROM Billing.PremiumTrustTransaction t WHERE t.PaymentAllocationId=a.AgencyBillPaymentAllocationId AND t.StatusCode=N'Posted' AND t.IsDeleted=0); SET @T=@@ROWCOUNT;
INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,NewValueJson,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'Synchronization',@TenantId,N'Completed',N'Agency-bill source synchronization completed.',JSON_OBJECT(N'ReceivablesCreated':@R,N'InstallmentsCreated':@I,N'AllocationsCreated':@A,N'TrustTransactionsCreated':@T),@UserId,SYSUTCDATETIME());
COMMIT; SELECT @R ReceivablesCreated,@I InstallmentsCreated,@A AllocationsCreated,@T TrustTransactionsCreated;
""";
        using var cn = await connectionFactory.CreateOpenConnectionAsync(cancellationToken);
        return await cn.QuerySingleAsync<AgencyBillSynchronizationResultDto>(new CommandDefinition(sql, new { request.TenantId, request.FromDate, request.ThroughDate, request.UserId }, cancellationToken: cancellationToken));
    }

    public async Task<IReadOnlyList<AgencyBillInstallmentDto>> CreateInstallmentScheduleAsync(CreateAgencyBillInstallmentScheduleRequest request, CancellationToken cancellationToken = default)
    {
        var amounts = AgencyBillRules.SplitInstallments(await GetReceivableBalanceAsync(request.TenantId, request.AgencyBillReceivableId, cancellationToken), request.InstallmentCount);
        using var cn = await connectionFactory.CreateOpenConnectionAsync(cancellationToken);
        using var tx = cn.BeginTransaction(IsolationLevel.Serializable);
        try
        {
            var existing = await cn.ExecuteScalarAsync<int>(new CommandDefinition("SELECT COUNT(1) FROM Billing.AgencyBillInstallment WITH(UPDLOCK,HOLDLOCK) WHERE TenantId=@TenantId AND AgencyBillReceivableId=@Id AND IsDeleted=0;", new { request.TenantId, Id = request.AgencyBillReceivableId }, tx, cancellationToken: cancellationToken));
            if (existing > 1) throw new InvalidOperationException("The receivable already has an installment schedule.");
            await cn.ExecuteAsync(new CommandDefinition("UPDATE Billing.AgencyBillInstallment SET IsDeleted=1,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE TenantId=@TenantId AND AgencyBillReceivableId=@Id AND IsDeleted=0;", new { request.TenantId, Id = request.AgencyBillReceivableId, request.UserId }, tx, cancellationToken: cancellationToken));
            const string insert = "INSERT Billing.AgencyBillInstallment(AgencyBillInstallmentId,TenantId,AgencyBillReceivableId,InstallmentNumber,DueDate,InstallmentAmount,AllocatedAmount,StatusCode,GraceDate,CreatedDateUtc,CreatedByUserId,IsDeleted) VALUES(NEWID(),@TenantId,@Id,@Number,@DueDate,@Amount,0,N'Scheduled',DATEADD(day,@GraceDays,@DueDate),SYSUTCDATETIME(),@UserId,0);";
            for (var index = 0; index < amounts.Count; index++) await cn.ExecuteAsync(new CommandDefinition(insert, new { request.TenantId, Id = request.AgencyBillReceivableId, Number = index + 1, DueDate = request.FirstDueDate.AddMonths(index * request.FrequencyMonths), Amount = amounts[index], request.GraceDays, request.UserId }, tx, cancellationToken: cancellationToken));
            await AuditAsync(cn, tx, request.TenantId, "Receivable", request.AgencyBillReceivableId, "InstallmentScheduleCreated", $"Created {amounts.Count} installments.", request.UserId, cancellationToken);
            tx.Commit();
        }
        catch { tx.Rollback(); throw; }
        return await GetInstallmentsAsync(request.TenantId, request.AgencyBillReceivableId, cancellationToken);
    }

    public Task<Guid> AllocatePaymentAsync(AllocateAgencyBillPaymentRequest request, CancellationToken cancellationToken = default)
        => ExecuteGuidAsync(AllocationSql, new { request.TenantId, request.PaymentId, ReceivableId = request.AgencyBillReceivableId, InstallmentId = request.AgencyBillInstallmentId, request.AllocationAmount, request.Notes, request.UserId }, cancellationToken);

    public Task<Guid> ReverseAllocationAsync(ReverseAgencyBillPaymentAllocationRequest request, CancellationToken cancellationToken = default)
        => ExecuteGuidAsync(ReversalSql, new { request.TenantId, AllocationId = request.AgencyBillPaymentAllocationId, request.Reason, request.UserId }, cancellationToken);

    public async Task<AgencyBillDelinquencyRunResultDto> RunDelinquencyAsync(RunAgencyBillDelinquencyRequest request, CancellationToken cancellationToken = default)
    {
        const string sql = """
SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Evaluated INT,@Notices INT=0,@Referrals INT=0;
UPDATE r SET DelinquencyStageCode=CASE WHEN DATEDIFF(day,r.DueDate,@AsOfDate)>=COALESCE(ref.NumericValue,30) THEN N'CancellationReview' WHEN DATEDIFF(day,r.DueDate,@AsOfDate)>=COALESCE(fin.NumericValue,20) THEN N'Late2' WHEN DATEDIFF(day,r.DueDate,@AsOfDate)>=COALESCE(first.NumericValue,10) THEN N'Late1' ELSE N'Current' END,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId FROM Billing.AgencyBillReceivable r OUTER APPLY(SELECT TOP 1 NumericValue FROM Billing.AgencyBillOption WHERE TenantId=@TenantId AND OptionGroupCode=N'DelinquencyStage' AND OptionCode=N'Late1' AND IsActive=1 AND IsDeleted=0)first OUTER APPLY(SELECT TOP 1 NumericValue FROM Billing.AgencyBillOption WHERE TenantId=@TenantId AND OptionGroupCode=N'DelinquencyStage' AND OptionCode=N'Late2' AND IsActive=1 AND IsDeleted=0)fin OUTER APPLY(SELECT TOP 1 NumericValue FROM Billing.AgencyBillOption WHERE TenantId=@TenantId AND OptionGroupCode=N'DelinquencyStage' AND OptionCode=N'CancellationReview' AND IsActive=1 AND IsDeleted=0)ref WHERE r.TenantId=@TenantId AND r.IsDeleted=0 AND r.BalanceAmount>0; SET @Evaluated=@@ROWCOUNT;
INSERT Billing.AgencyBillLateNotice(AgencyBillLateNoticeId,TenantId,AgencyBillReceivableId,NoticeLevelCode,NoticeDateUtc,DeliveryMethodCode,AmountDue,DueDate,StatusCode,CreatedDateUtc,CreatedByUserId,IsDeleted) SELECT NEWID(),r.TenantId,r.AgencyBillReceivableId,r.DelinquencyStageCode,SYSUTCDATETIME(),COALESCE(dm.OptionCode,N'Email'),r.BalanceAmount,r.DueDate,N'Prepared',SYSUTCDATETIME(),@UserId,0 FROM Billing.AgencyBillReceivable r OUTER APPLY(SELECT TOP 1 OptionCode FROM Billing.AgencyBillOption WHERE TenantId=@TenantId AND OptionGroupCode=N'NoticeDeliveryMethod' AND IsDefault=1 AND IsActive=1 AND IsDeleted=0 ORDER BY SortOrder)dm WHERE r.TenantId=@TenantId AND r.IsDeleted=0 AND r.BalanceAmount>0 AND r.DelinquencyStageCode IN(N'Late1',N'Late2') AND NOT EXISTS(SELECT 1 FROM Billing.AgencyBillLateNotice n WHERE n.AgencyBillReceivableId=r.AgencyBillReceivableId AND n.NoticeLevelCode=r.DelinquencyStageCode AND n.IsDeleted=0); SET @Notices=@@ROWCOUNT;
INSERT Billing.NonPaymentCancellationReferral(NonPaymentCancellationReferralId,TenantId,ReferralNumber,AgencyBillReceivableId,PolicyId,ReferralDateUtc,RequestedEffectiveDate,AmountDue,StatusCode,CreatedDateUtc,CreatedByUserId,IsDeleted) SELECT NEWID(),r.TenantId,CONCAT(N'NPC-',FORMAT(@AsOfDate,N'yyyyMMdd'),N'-',LEFT(REPLACE(CONVERT(NVARCHAR(36),r.AgencyBillReceivableId),N'-',N''),8)),r.AgencyBillReceivableId,r.PolicyId,SYSUTCDATETIME(),DATEADD(day,10,@AsOfDate),r.BalanceAmount,N'PendingReview',SYSUTCDATETIME(),@UserId,0 FROM Billing.AgencyBillReceivable r WHERE r.TenantId=@TenantId AND r.IsDeleted=0 AND r.BalanceAmount>0 AND r.DelinquencyStageCode=N'CancellationReview' AND r.PolicyId IS NOT NULL AND NOT EXISTS(SELECT 1 FROM Billing.NonPaymentCancellationReferral x WHERE x.AgencyBillReceivableId=r.AgencyBillReceivableId AND x.StatusCode IN(N'PendingReview',N'Approved') AND x.IsDeleted=0); SET @Referrals=@@ROWCOUNT;
INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,NewValueJson,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'DelinquencyRun',@TenantId,N'Completed',N'Agency-bill delinquency evaluation completed.',JSON_OBJECT(N'AsOfDate':@AsOfDate,N'Evaluated':@Evaluated,N'NoticesCreated':@Notices,N'ReferralsCreated':@Referrals),@UserId,SYSUTCDATETIME()); COMMIT; SELECT @Evaluated ReceivablesEvaluated,@Notices NoticesCreated,@Referrals ReferralsCreated;
""";
        using var cn = await connectionFactory.CreateOpenConnectionAsync(cancellationToken);
        return await cn.QuerySingleAsync<AgencyBillDelinquencyRunResultDto>(new CommandDefinition(sql, new { request.TenantId, request.AsOfDate, request.UserId }, cancellationToken: cancellationToken));
    }

    public Task<Guid> CreateLateNoticeAsync(CreateAgencyBillLateNoticeRequest request, CancellationToken cancellationToken = default)
        => ExecuteGuidAsync("""SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Id UNIQUEIDENTIFIER=NEWID(); INSERT Billing.AgencyBillLateNotice(AgencyBillLateNoticeId,TenantId,AgencyBillReceivableId,AgencyBillInstallmentId,NoticeLevelCode,DeliveryMethodCode,RecipientAddress,AmountDue,DueDate,StatusCode,CreatedDateUtc,CreatedByUserId,IsDeleted) SELECT @Id,@TenantId,r.AgencyBillReceivableId,@InstallmentId,@NoticeLevelCode,@DeliveryMethodCode,@RecipientAddress,COALESCE(i.BalanceAmount,r.BalanceAmount),COALESCE(i.DueDate,r.DueDate),N'Prepared',SYSUTCDATETIME(),@UserId,0 FROM Billing.AgencyBillReceivable r LEFT JOIN Billing.AgencyBillInstallment i ON i.AgencyBillInstallmentId=@InstallmentId AND i.TenantId=r.TenantId AND i.AgencyBillReceivableId=r.AgencyBillReceivableId AND i.IsDeleted=0 WHERE r.TenantId=@TenantId AND r.AgencyBillReceivableId=@ReceivableId AND r.IsDeleted=0 AND r.BalanceAmount>0; IF @@ROWCOUNT<>1 THROW 51000,N'Open receivable or installment not found.',1; INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'LateNotice',@Id,N'Prepared',N'Late notice prepared for delivery.',@UserId,SYSUTCDATETIME()); COMMIT; SELECT @Id;""", new { request.TenantId, ReceivableId = request.AgencyBillReceivableId, InstallmentId = request.AgencyBillInstallmentId, request.NoticeLevelCode, request.DeliveryMethodCode, request.RecipientAddress, request.UserId }, cancellationToken);

    public Task<Guid> CreateNonPaymentReferralAsync(CreateNonPaymentReferralRequest request, CancellationToken cancellationToken = default)
        => ExecuteGuidAsync("""SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Id UNIQUEIDENTIFIER=NEWID(),@Number NVARCHAR(50)=CONCAT(N'NPC-',FORMAT(SYSUTCDATETIME(),N'yyyyMMddHHmmss'),N'-',LEFT(REPLACE(CONVERT(NVARCHAR(36),@Id),N'-',N''),6)); INSERT Billing.NonPaymentCancellationReferral(NonPaymentCancellationReferralId,TenantId,ReferralNumber,AgencyBillReceivableId,PolicyId,ReferralDateUtc,RequestedEffectiveDate,AmountDue,StatusCode,ReviewNotes,CreatedDateUtc,CreatedByUserId,IsDeleted) SELECT @Id,@TenantId,@Number,r.AgencyBillReceivableId,r.PolicyId,SYSUTCDATETIME(),@RequestedEffectiveDate,r.BalanceAmount,N'PendingReview',@Notes,SYSUTCDATETIME(),@UserId,0 FROM Billing.AgencyBillReceivable r WHERE r.TenantId=@TenantId AND r.AgencyBillReceivableId=@ReceivableId AND r.IsDeleted=0 AND r.BalanceAmount>0 AND r.PolicyId IS NOT NULL AND NOT EXISTS(SELECT 1 FROM Billing.NonPaymentCancellationReferral x WHERE x.AgencyBillReceivableId=r.AgencyBillReceivableId AND x.StatusCode IN(N'PendingReview',N'Approved') AND x.IsDeleted=0); IF @@ROWCOUNT<>1 THROW 51000,N'Receivable is not eligible or already has an active referral.',1; INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'NonPaymentReferral',@Id,N'Created',N'Non-payment referral submitted for human review.',@UserId,SYSUTCDATETIME()); COMMIT; SELECT @Id;""", new { request.TenantId, ReceivableId = request.AgencyBillReceivableId, request.RequestedEffectiveDate, request.Notes, request.UserId }, cancellationToken);

    public async Task ReviewNonPaymentReferralAsync(ReviewNonPaymentReferralRequest request, CancellationToken cancellationToken = default)
    {
        if (!AgencyBillRules.IsReferralDecision(request.DecisionCode)) throw new ArgumentException("Decision must be Approved, Rejected, or Withdrawn.", nameof(request));
        const string sql = """SET XACT_ABORT ON; BEGIN TRAN; UPDATE Billing.NonPaymentCancellationReferral SET StatusCode=@DecisionCode,ReviewNotes=@ReviewNotes,ReviewedDateUtc=SYSUTCDATETIME(),ReviewedByUserId=@UserId,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE TenantId=@TenantId AND NonPaymentCancellationReferralId=@Id AND StatusCode=N'PendingReview' AND IsDeleted=0; IF @@ROWCOUNT<>1 THROW 51000,N'Pending referral not found.',1; INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,NewValueJson,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'NonPaymentReferral',@Id,N'Reviewed',N'Non-payment referral reviewed.',JSON_OBJECT(N'Decision':@DecisionCode,N'Notes':@ReviewNotes),@UserId,SYSUTCDATETIME()); COMMIT;""";
        await ExecuteAsync(sql, new { request.TenantId, Id = request.NonPaymentCancellationReferralId, request.DecisionCode, request.ReviewNotes, request.UserId }, cancellationToken);
    }

    public Task<Guid> CreateReconciliationAsync(CreateAgencyBillReconciliationRequest request, CancellationToken cancellationToken = default)
        => ExecuteGuidAsync("""SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Id UNIQUEIDENTIFIER=NEWID(); INSERT Billing.AgencyBillReconciliation(AgencyBillReconciliationId,TenantId,ReconciliationNumber,StatementReference,StatementDate,PeriodStartDate,PeriodEndDate,StatementAmount,SubledgerAmount,StatusCode,CreatedDateUtc,CreatedByUserId,IsDeleted) VALUES(@Id,@TenantId,CONCAT(N'ABREC-',FORMAT(@StatementDate,N'yyyyMMdd'),N'-',LEFT(REPLACE(CONVERT(NVARCHAR(36),@Id),N'-',N''),6)),@StatementReference,@StatementDate,@PeriodStartDate,@PeriodEndDate,@StatementAmount,0,N'Draft',SYSUTCDATETIME(),@UserId,0); INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'Reconciliation',@Id,N'Created',N'Agency-bill reconciliation created.',@UserId,SYSUTCDATETIME()); COMMIT; SELECT @Id;""", request, cancellationToken);

    public Task<Guid> AddReconciliationLineAsync(AddAgencyBillReconciliationLineRequest request, CancellationToken cancellationToken = default)
        => ExecuteGuidAsync("""SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Id UNIQUEIDENTIFIER=NEWID(); IF NOT EXISTS(SELECT 1 FROM Billing.AgencyBillReconciliation WHERE TenantId=@TenantId AND AgencyBillReconciliationId=@AgencyBillReconciliationId AND StatusCode IN(N'Draft',N'InProgress') AND IsDeleted=0) THROW 51000,N'Open reconciliation not found.',1; INSERT Billing.AgencyBillReconciliationLine(AgencyBillReconciliationLineId,TenantId,AgencyBillReconciliationId,AgencyBillReceivableId,PaymentAllocationId,StatementLineReference,StatementAmount,SubledgerAmount,MatchStatusCode,ExceptionReason,CreatedDateUtc,CreatedByUserId,IsDeleted) VALUES(@Id,@TenantId,@AgencyBillReconciliationId,@AgencyBillReceivableId,@PaymentAllocationId,@StatementLineReference,@StatementAmount,@SubledgerAmount,CASE WHEN @StatementAmount=@SubledgerAmount THEN N'Matched' ELSE N'Exception' END,@ExceptionReason,SYSUTCDATETIME(),@UserId,0); UPDATE r SET SubledgerAmount=(SELECT COALESCE(SUM(SubledgerAmount),0) FROM Billing.AgencyBillReconciliationLine WHERE AgencyBillReconciliationId=@AgencyBillReconciliationId AND IsDeleted=0),StatusCode=N'InProgress',ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId FROM Billing.AgencyBillReconciliation r WHERE r.AgencyBillReconciliationId=@AgencyBillReconciliationId; COMMIT; SELECT @Id;""", request, cancellationToken);

    public async Task CompleteReconciliationAsync(CompleteAgencyBillReconciliationRequest request, CancellationToken cancellationToken = default)
    {
        const string sql = """SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Variance DECIMAL(18,2); SELECT @Variance=VarianceAmount FROM Billing.AgencyBillReconciliation WITH(UPDLOCK,HOLDLOCK) WHERE TenantId=@TenantId AND AgencyBillReconciliationId=@Id AND StatusCode IN(N'Draft',N'InProgress') AND IsDeleted=0; IF @Variance IS NULL THROW 51000,N'Open reconciliation not found.',1; IF ABS(@Variance)>@Tolerance THROW 51000,N'Reconciliation variance exceeds tolerance.',1; IF EXISTS(SELECT 1 FROM Billing.AgencyBillReconciliationLine WHERE AgencyBillReconciliationId=@Id AND MatchStatusCode=N'Exception' AND IsDeleted=0) THROW 51000,N'Reconciliation has unresolved exception lines.',1; UPDATE Billing.AgencyBillReconciliation SET StatusCode=N'Completed',CompletedDateUtc=SYSUTCDATETIME(),ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE AgencyBillReconciliationId=@Id; INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,NewValueJson,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'Reconciliation',@Id,N'Completed',N'Agency-bill reconciliation completed.',JSON_OBJECT(N'Variance':@Variance,N'Tolerance':@Tolerance),@UserId,SYSUTCDATETIME()); COMMIT;""";
        await ExecuteAsync(sql, new { request.TenantId, Id = request.AgencyBillReconciliationId, Tolerance = request.VarianceTolerance, request.UserId }, cancellationToken);
    }

    public Task<Guid> UpsertFinanceCompanyAsync(UpsertFinanceCompanyRequest request, CancellationToken cancellationToken = default)
        => ExecuteGuidAsync("""SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Id UNIQUEIDENTIFIER=COALESCE(@FinanceCompanyId,NEWID()); IF EXISTS(SELECT 1 FROM Billing.FinanceCompany WHERE TenantId=@TenantId AND FinanceCompanyId=@Id AND IsDeleted=0) UPDATE Billing.FinanceCompany SET CompanyCode=@CompanyCode,CompanyName=@CompanyName,ContactName=@ContactName,EmailAddress=@EmailAddress,PhoneNumber=@PhoneNumber,RemittanceInstructions=@RemittanceInstructions,IsActive=@IsActive,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE TenantId=@TenantId AND FinanceCompanyId=@Id; ELSE INSERT Billing.FinanceCompany(FinanceCompanyId,TenantId,CompanyCode,CompanyName,ContactName,EmailAddress,PhoneNumber,RemittanceInstructions,IsActive,CreatedDateUtc,CreatedByUserId,IsDeleted) VALUES(@Id,@TenantId,@CompanyCode,@CompanyName,@ContactName,@EmailAddress,@PhoneNumber,@RemittanceInstructions,@IsActive,SYSUTCDATETIME(),@UserId,0); INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'FinanceCompany',@Id,N'Upserted',N'Finance company configuration saved.',@UserId,SYSUTCDATETIME()); COMMIT; SELECT @Id;""", request, cancellationToken);

    public Task<Guid> CreateFinanceAgreementAsync(CreateFinanceAgreementRequest request, CancellationToken cancellationToken = default)
        => ExecuteGuidAsync("""SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Id UNIQUEIDENTIFIER=NEWID(); INSERT Billing.FinanceAgreement(FinanceAgreementId,TenantId,AgencyBillReceivableId,FinanceCompanyId,AgreementNumber,FinancedAmount,DownPaymentAmount,FundingStatusCode,ExpectedFundingDate,CancellationProtectionDate,StatusCode,CreatedDateUtc,CreatedByUserId,IsDeleted) SELECT @Id,@TenantId,r.AgencyBillReceivableId,c.FinanceCompanyId,@AgreementNumber,@FinancedAmount,@DownPaymentAmount,N'Pending',@ExpectedFundingDate,@CancellationProtectionDate,N'Active',SYSUTCDATETIME(),@UserId,0 FROM Billing.AgencyBillReceivable r JOIN Billing.FinanceCompany c ON c.TenantId=r.TenantId AND c.FinanceCompanyId=@FinanceCompanyId AND c.IsActive=1 AND c.IsDeleted=0 WHERE r.TenantId=@TenantId AND r.AgencyBillReceivableId=@AgencyBillReceivableId AND r.IsDeleted=0; IF @@ROWCOUNT<>1 THROW 51000,N'Receivable or active finance company not found.',1; UPDATE Billing.AgencyBillReceivable SET FinanceCompanyId=@FinanceCompanyId,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE AgencyBillReceivableId=@AgencyBillReceivableId; INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'FinanceAgreement',@Id,N'Created',N'Premium finance agreement created.',@UserId,SYSUTCDATETIME()); COMMIT; SELECT @Id;""", request, cancellationToken);

    public async Task UpdateFinanceAgreementFundingAsync(UpdateFinanceAgreementFundingRequest request, CancellationToken cancellationToken = default)
    {
        const string sql = """SET XACT_ABORT ON; BEGIN TRAN; UPDATE Billing.FinanceAgreement SET FundingStatusCode=@FundingStatusCode,FundedDate=@FundedDate,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE TenantId=@TenantId AND FinanceAgreementId=@Id AND IsDeleted=0; IF @@ROWCOUNT<>1 THROW 51000,N'Finance agreement not found.',1; INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,NewValueJson,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'FinanceAgreement',@Id,N'FundingUpdated',N'Finance agreement funding status updated.',JSON_OBJECT(N'Status':@FundingStatusCode,N'FundedDate':@FundedDate,N'Notes':@Notes),@UserId,SYSUTCDATETIME()); COMMIT;""";
        await ExecuteAsync(sql, new { request.TenantId, Id = request.FinanceAgreementId, request.FundingStatusCode, request.FundedDate, request.Notes, request.UserId }, cancellationToken);
    }

    private async Task<decimal> GetReceivableBalanceAsync(Guid tenantId, Guid receivableId, CancellationToken cancellationToken)
    {
        using var cn = await connectionFactory.CreateOpenConnectionAsync(cancellationToken);
        var balance = await cn.QuerySingleOrDefaultAsync<decimal?>(new CommandDefinition("SELECT BalanceAmount FROM Billing.AgencyBillReceivable WHERE TenantId=@TenantId AND AgencyBillReceivableId=@Id AND IsDeleted=0 AND BalanceAmount>0;", new { TenantId = tenantId, Id = receivableId }, cancellationToken: cancellationToken));
        return balance ?? throw new InvalidOperationException("Open agency-bill receivable not found.");
    }

    private async Task<IReadOnlyList<AgencyBillInstallmentDto>> GetInstallmentsAsync(Guid tenantId, Guid receivableId, CancellationToken cancellationToken)
    {
        using var cn = await connectionFactory.CreateOpenConnectionAsync(cancellationToken);
        return (await cn.QueryAsync<AgencyBillInstallmentDto>(new CommandDefinition("SELECT AgencyBillInstallmentId,TenantId,AgencyBillReceivableId,InstallmentNumber,DueDate,InstallmentAmount,AllocatedAmount,BalanceAmount,StatusCode,GraceDate FROM Billing.AgencyBillInstallment WHERE TenantId=@TenantId AND AgencyBillReceivableId=@Id AND IsDeleted=0 ORDER BY InstallmentNumber;", new { TenantId = tenantId, Id = receivableId }, cancellationToken: cancellationToken))).AsList();
    }

    private async Task<Guid> ExecuteGuidAsync(string sql, object parameters, CancellationToken cancellationToken)
    {
        using var cn = await connectionFactory.CreateOpenConnectionAsync(cancellationToken);
        return await cn.QuerySingleAsync<Guid>(new CommandDefinition(sql, parameters, cancellationToken: cancellationToken));
    }

    private async Task ExecuteAsync(string sql, object parameters, CancellationToken cancellationToken)
    {
        using var cn = await connectionFactory.CreateOpenConnectionAsync(cancellationToken);
        await cn.ExecuteAsync(new CommandDefinition(sql, parameters, cancellationToken: cancellationToken));
    }

    private static Task AuditAsync(IDbConnection connection, IDbTransaction transaction, Guid tenantId, string entityType, Guid entityId, string eventType, string description, Guid? userId, CancellationToken cancellationToken)
        => connection.ExecuteAsync(new CommandDefinition("INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,@EntityType,@EntityId,@EventType,@Description,@UserId,SYSUTCDATETIME());", new { TenantId = tenantId, EntityType = entityType, EntityId = entityId, EventType = eventType, Description = description, UserId = userId }, transaction, cancellationToken: cancellationToken));

    private const string AllocationSql = """
SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Id UNIQUEIDENTIFIER=NEWID(),@PaymentAvailable DECIMAL(18,2),@ReceivableBalance DECIMAL(18,2),@InstallmentBalance DECIMAL(18,2);
SELECT @PaymentAvailable=p.Amount-COALESCE((SELECT SUM(CASE WHEN a.StatusCode=N'Applied' THEN a.AllocationAmount ELSE -a.AllocationAmount END) FROM Billing.AgencyBillPaymentAllocation a WHERE a.TenantId=p.TenantId AND a.PaymentId=p.PaymentId AND a.IsDeleted=0),0) FROM Billing.Payment p WITH(UPDLOCK,HOLDLOCK) WHERE p.TenantId=@TenantId AND p.PaymentId=@PaymentId AND p.IsDeleted=0;
SELECT @ReceivableBalance=BalanceAmount FROM Billing.AgencyBillReceivable WITH(UPDLOCK,HOLDLOCK) WHERE TenantId=@TenantId AND AgencyBillReceivableId=@ReceivableId AND IsDeleted=0;
IF @InstallmentId IS NOT NULL SELECT @InstallmentBalance=BalanceAmount FROM Billing.AgencyBillInstallment WITH(UPDLOCK,HOLDLOCK) WHERE TenantId=@TenantId AND AgencyBillInstallmentId=@InstallmentId AND AgencyBillReceivableId=@ReceivableId AND IsDeleted=0;
IF @PaymentAvailable IS NULL OR @ReceivableBalance IS NULL OR @AllocationAmount<=0 OR @AllocationAmount>@PaymentAvailable OR @AllocationAmount>@ReceivableBalance OR (@InstallmentId IS NOT NULL AND (@InstallmentBalance IS NULL OR @AllocationAmount>@InstallmentBalance)) THROW 51000,N'Allocation exceeds available payment, receivable, or installment balance.',1;
INSERT Billing.AgencyBillPaymentAllocation(AgencyBillPaymentAllocationId,TenantId,PaymentId,AgencyBillReceivableId,AgencyBillInstallmentId,AllocationAmount,StatusCode,Notes,CreatedDateUtc,CreatedByUserId,IsDeleted) VALUES(@Id,@TenantId,@PaymentId,@ReceivableId,@InstallmentId,@AllocationAmount,N'Applied',@Notes,SYSUTCDATETIME(),@UserId,0);
UPDATE Billing.AgencyBillReceivable SET AllocatedAmount=AllocatedAmount+@AllocationAmount,StatusCode=CASE WHEN BalanceAmount-@AllocationAmount<=0 THEN N'Paid' ELSE N'PartiallyPaid' END,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE AgencyBillReceivableId=@ReceivableId;
IF @InstallmentId IS NOT NULL UPDATE Billing.AgencyBillInstallment SET AllocatedAmount=AllocatedAmount+@AllocationAmount,StatusCode=CASE WHEN BalanceAmount-@AllocationAmount<=0 THEN N'Paid' ELSE N'PartiallyPaid' END,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE AgencyBillInstallmentId=@InstallmentId;
INSERT Billing.PremiumTrustTransaction(PremiumTrustTransactionId,TenantId,TrustAccountCode,TransactionTypeCode,AgencyBillReceivableId,PaymentId,PaymentAllocationId,TransactionDate,Amount,DirectionCode,StatusCode,CreatedDateUtc,CreatedByUserId,IsDeleted) VALUES(NEWID(),@TenantId,N'PREMIUM_TRUST',N'PremiumReceipt',@ReceivableId,@PaymentId,@Id,CONVERT(date,SYSUTCDATETIME()),@AllocationAmount,N'Credit',N'Posted',SYSUTCDATETIME(),@UserId,0);
INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,NewValueJson,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'PaymentAllocation',@Id,N'Applied',N'Payment allocated to agency-bill receivable.',JSON_OBJECT(N'Amount':@AllocationAmount,N'PaymentId':@PaymentId,N'ReceivableId':@ReceivableId),@UserId,SYSUTCDATETIME()); COMMIT; SELECT @Id;
""";

    private const string ReversalSql = """
SET XACT_ABORT ON; BEGIN TRAN; DECLARE @Id UNIQUEIDENTIFIER=NEWID(),@PaymentId UNIQUEIDENTIFIER,@ReceivableId UNIQUEIDENTIFIER,@InstallmentId UNIQUEIDENTIFIER,@Amount DECIMAL(18,2);
SELECT @PaymentId=PaymentId,@ReceivableId=AgencyBillReceivableId,@InstallmentId=AgencyBillInstallmentId,@Amount=AllocationAmount FROM Billing.AgencyBillPaymentAllocation WITH(UPDLOCK,HOLDLOCK) WHERE TenantId=@TenantId AND AgencyBillPaymentAllocationId=@AllocationId AND StatusCode=N'Applied' AND IsDeleted=0; IF @Amount IS NULL THROW 51000,N'Applied allocation not found.',1;
IF EXISTS(SELECT 1 FROM Billing.AgencyBillPaymentAllocation WHERE ReversalOfAllocationId=@AllocationId AND IsDeleted=0) THROW 51000,N'Allocation has already been reversed.',1;
INSERT Billing.AgencyBillPaymentAllocation(AgencyBillPaymentAllocationId,TenantId,PaymentId,AgencyBillReceivableId,AgencyBillInstallmentId,AllocationAmount,StatusCode,ReversalOfAllocationId,Notes,CreatedDateUtc,CreatedByUserId,IsDeleted) VALUES(@Id,@TenantId,@PaymentId,@ReceivableId,@InstallmentId,@Amount,N'Reversed',@AllocationId,@Reason,SYSUTCDATETIME(),@UserId,0);
UPDATE Billing.AgencyBillReceivable SET AllocatedAmount=AllocatedAmount-@Amount,StatusCode=N'Open',ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE AgencyBillReceivableId=@ReceivableId;
IF @InstallmentId IS NOT NULL UPDATE Billing.AgencyBillInstallment SET AllocatedAmount=AllocatedAmount-@Amount,StatusCode=CASE WHEN DueDate<CONVERT(date,SYSUTCDATETIME()) THEN N'PastDue' ELSE N'Scheduled' END,ModifiedDateUtc=SYSUTCDATETIME(),ModifiedByUserId=@UserId WHERE AgencyBillInstallmentId=@InstallmentId;
INSERT Billing.PremiumTrustTransaction(PremiumTrustTransactionId,TenantId,TrustAccountCode,TransactionTypeCode,AgencyBillReceivableId,PaymentId,PaymentAllocationId,TransactionDate,Amount,DirectionCode,StatusCode,ReversalOfTransactionId,CreatedDateUtc,CreatedByUserId,IsDeleted) SELECT NEWID(),@TenantId,TrustAccountCode,N'PremiumReceiptReversal',@ReceivableId,@PaymentId,@Id,CONVERT(date,SYSUTCDATETIME()),@Amount,N'Debit',N'Posted',PremiumTrustTransactionId,SYSUTCDATETIME(),@UserId,0 FROM Billing.PremiumTrustTransaction WHERE TenantId=@TenantId AND PaymentAllocationId=@AllocationId AND StatusCode=N'Posted' AND IsDeleted=0;
INSERT Billing.AgencyBillAuditEvent(AgencyBillAuditEventId,TenantId,EntityTypeCode,EntityId,EventTypeCode,EventDescription,NewValueJson,ActorUserId,CreatedDateUtc) VALUES(NEWID(),@TenantId,N'PaymentAllocation',@Id,N'Reversed',N'Payment allocation and trust receipt reversed.',JSON_OBJECT(N'OriginalAllocationId':@AllocationId,N'Amount':@Amount,N'Reason':@Reason),@UserId,SYSUTCDATETIME()); COMMIT; SELECT @Id;
""";
}
