using Ams.Application.Abstractions.Persistence;
using Ams.Application.Common.Dtos;
using Ams.Application.Common.Models;
using Ams.Application.Features.CarrierRules;
using Dapper;

namespace Ams.Infrastructure.Persistence.Repositories;

public sealed class MarketAccessRuleRepository : IMarketAccessRuleRepository
{
    private readonly ISqlConnectionFactory _cf;
    public MarketAccessRuleRepository(ISqlConnectionFactory cf) => _cf = cf;
    private const string Cols = "MarketAccessRuleId, TenantId, RuleName, CarrierNaic, StateCode, LobCode, AccessLevel, Requirements, Priority, IsActive, CreatedDateUtc";
    public async Task<MarketAccessRuleDto?> GetByIdAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); return await cn.QuerySingleOrDefaultAsync<MarketAccessRuleDto>(new CommandDefinition($"SELECT {Cols} FROM Agency.MarketAccessRule WHERE MarketAccessRuleId=@Id AND IsDeleted=0;", new { Id = id }, cancellationToken: ct)); }
    public async Task<PagedResult<MarketAccessRuleDto>> SearchAsync(Guid tenantId, string? searchTerm, int pageNumber = 1, int pageSize = 50, CancellationToken ct = default) { var sql = RepositorySql.BuildPagedSearchSql("Agency.MarketAccessRule", Cols, "RuleName LIKE '%'+@SearchTerm+'%' OR StateCode LIKE '%'+@SearchTerm+'%' OR LobCode LIKE '%'+@SearchTerm+'%'", "Priority ASC, RuleName ASC"); using var cn = await _cf.CreateOpenConnectionAsync(ct); using var multi = await cn.QueryMultipleAsync(new CommandDefinition(sql, new { TenantId = tenantId, SearchTerm = searchTerm ?? "", Offset = (Math.Max(pageNumber, 1) - 1) * pageSize, PageSize = pageSize }, cancellationToken: ct)); return new() { Items = (await multi.ReadAsync<MarketAccessRuleDto>()).AsList(), TotalCount = await multi.ReadSingleAsync<int>(), PageNumber = pageNumber, PageSize = pageSize }; }
    public async Task<Guid> CreateAsync(CreateMarketAccessRuleRequest r, CancellationToken ct = default) { const string sql = "INSERT INTO Agency.MarketAccessRule (MarketAccessRuleId,TenantId,RuleName,CarrierNaic,StateCode,LobCode,AccessLevel,Requirements,Priority,IsActive,IsDeleted,CreatedDateUtc) VALUES (@Id,@TenantId,@RuleName,@CarrierNaic,@StateCode,@LobCode,@AccessLevel,@Requirements,@Priority,1,0,GETUTCDATE());"; var id = Guid.NewGuid(); using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.TenantId, r.RuleName, r.CarrierNaic, r.StateCode, r.LobCode, r.AccessLevel, r.Requirements, r.Priority }, cancellationToken: ct)); return id; }
    public async Task UpdateAsync(Guid id, UpdateMarketAccessRuleRequest r, CancellationToken ct = default) { const string sql = "UPDATE Agency.MarketAccessRule SET RuleName=@RuleName,CarrierNaic=@CarrierNaic,StateCode=@StateCode,LobCode=@LobCode,AccessLevel=@AccessLevel,Requirements=@Requirements,Priority=@Priority,IsActive=@IsActive,ModifiedDateUtc=GETUTCDATE() WHERE MarketAccessRuleId=@Id AND IsDeleted=0;"; using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.RuleName, r.CarrierNaic, r.StateCode, r.LobCode, r.AccessLevel, r.Requirements, r.Priority, r.IsActive }, cancellationToken: ct)); }
    public async Task DeleteAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition("UPDATE Agency.MarketAccessRule SET IsDeleted=1 WHERE MarketAccessRuleId=@Id;", new { Id = id }, cancellationToken: ct)); }
}

public sealed class CarrierDownloadMappingRepository : ICarrierDownloadMappingRepository
{
    private readonly ISqlConnectionFactory _cf;
    public CarrierDownloadMappingRepository(ISqlConnectionFactory cf) => _cf = cf;
    private const string Cols = "DownloadMappingId, TenantId, MappingCode, CarrierNaic, TransactionType, SourceField, TargetField, TransformRule, IsActive, SortOrder, CreatedDateUtc";
    public async Task<CarrierDownloadMappingDto?> GetByIdAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); return await cn.QuerySingleOrDefaultAsync<CarrierDownloadMappingDto>(new CommandDefinition($"SELECT {Cols} FROM Agency.CarrierDownloadMapping WHERE DownloadMappingId=@Id AND IsDeleted=0;", new { Id = id }, cancellationToken: ct)); }
    public async Task<PagedResult<CarrierDownloadMappingDto>> SearchAsync(Guid tenantId, string? searchTerm, int pageNumber = 1, int pageSize = 50, CancellationToken ct = default) { var sql = RepositorySql.BuildPagedSearchSql("Agency.CarrierDownloadMapping", Cols, "MappingCode LIKE '%'+@SearchTerm+'%' OR TransactionType LIKE '%'+@SearchTerm+'%' OR SourceField LIKE '%'+@SearchTerm+'%'", "SortOrder ASC, MappingCode ASC"); using var cn = await _cf.CreateOpenConnectionAsync(ct); using var multi = await cn.QueryMultipleAsync(new CommandDefinition(sql, new { TenantId = tenantId, SearchTerm = searchTerm ?? "", Offset = (Math.Max(pageNumber, 1) - 1) * pageSize, PageSize = pageSize }, cancellationToken: ct)); return new() { Items = (await multi.ReadAsync<CarrierDownloadMappingDto>()).AsList(), TotalCount = await multi.ReadSingleAsync<int>(), PageNumber = pageNumber, PageSize = pageSize }; }
    public async Task<Guid> CreateAsync(CreateCarrierDownloadMappingRequest r, CancellationToken ct = default) { const string sql = "INSERT INTO Agency.CarrierDownloadMapping (DownloadMappingId,TenantId,MappingCode,CarrierNaic,TransactionType,SourceField,TargetField,TransformRule,SortOrder,IsActive,IsDeleted,CreatedDateUtc) VALUES (@Id,@TenantId,@MappingCode,@CarrierNaic,@TransactionType,@SourceField,@TargetField,@TransformRule,@SortOrder,1,0,GETUTCDATE());"; var id = Guid.NewGuid(); using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.TenantId, r.MappingCode, r.CarrierNaic, r.TransactionType, r.SourceField, r.TargetField, r.TransformRule, r.SortOrder }, cancellationToken: ct)); return id; }
    public async Task UpdateAsync(Guid id, UpdateCarrierDownloadMappingRequest r, CancellationToken ct = default) { const string sql = "UPDATE Agency.CarrierDownloadMapping SET MappingCode=@MappingCode,CarrierNaic=@CarrierNaic,TransactionType=@TransactionType,SourceField=@SourceField,TargetField=@TargetField,TransformRule=@TransformRule,IsActive=@IsActive,SortOrder=@SortOrder,ModifiedDateUtc=GETUTCDATE() WHERE DownloadMappingId=@Id AND IsDeleted=0;"; using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.MappingCode, r.CarrierNaic, r.TransactionType, r.SourceField, r.TargetField, r.TransformRule, r.IsActive, r.SortOrder }, cancellationToken: ct)); }
    public async Task DeleteAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition("UPDATE Agency.CarrierDownloadMapping SET IsDeleted=1 WHERE DownloadMappingId=@Id;", new { Id = id }, cancellationToken: ct)); }
}
