using Ams.Application.Abstractions.Persistence;
using Ams.Application.Common.Dtos;
using Ams.Application.Common.Models;
using Ams.Application.Features.CarrierConfig;
using Dapper;

namespace Ams.Infrastructure.Persistence.Repositories;

public sealed class MgaWholesalerRepository : IMgaWholesalerRepository
{
    private readonly ISqlConnectionFactory _cf;
    public MgaWholesalerRepository(ISqlConnectionFactory cf) => _cf = cf;
    private const string Cols = "MgaWholesalerId, TenantId, MgaCode, MgaName, Type, Website, IsActive, SortOrder, CreatedDateUtc";
    public async Task<MgaWholesalerDto?> GetByIdAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); return await cn.QuerySingleOrDefaultAsync<MgaWholesalerDto>(new CommandDefinition($"SELECT {Cols} FROM Agency.MgaWholesaler WHERE MgaWholesalerId=@Id AND IsDeleted=0;", new { Id = id }, cancellationToken: ct)); }
    public async Task<PagedResult<MgaWholesalerDto>> SearchAsync(Guid tenantId, string? searchTerm, int pageNumber = 1, int pageSize = 50, CancellationToken ct = default) { var sql = RepositorySql.BuildPagedSearchSql("Agency.MgaWholesaler", Cols, "MgaName LIKE '%'+@SearchTerm+'%' OR MgaCode LIKE '%'+@SearchTerm+'%'", "SortOrder ASC, MgaName ASC"); using var cn = await _cf.CreateOpenConnectionAsync(ct); using var multi = await cn.QueryMultipleAsync(new CommandDefinition(sql, new { TenantId = tenantId, SearchTerm = searchTerm ?? "", Offset = (Math.Max(pageNumber, 1) - 1) * pageSize, PageSize = pageSize }, cancellationToken: ct)); return new() { Items = (await multi.ReadAsync<MgaWholesalerDto>()).AsList(), TotalCount = await multi.ReadSingleAsync<int>(), PageNumber = pageNumber, PageSize = pageSize }; }
    public async Task<Guid> CreateAsync(CreateMgaWholesalerRequest r, CancellationToken ct = default) { const string sql = "INSERT INTO Agency.MgaWholesaler (MgaWholesalerId,TenantId,MgaCode,MgaName,Type,Website,SortOrder,IsActive,IsDeleted,CreatedDateUtc) VALUES (@Id,@TenantId,@MgaCode,@MgaName,@Type,@Website,@SortOrder,1,0,GETUTCDATE());"; var id = Guid.NewGuid(); using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.TenantId, r.MgaCode, r.MgaName, r.Type, r.Website, r.SortOrder }, cancellationToken: ct)); return id; }
    public async Task UpdateAsync(Guid id, UpdateMgaWholesalerRequest r, CancellationToken ct = default) { const string sql = "UPDATE Agency.MgaWholesaler SET MgaCode=@MgaCode,MgaName=@MgaName,Type=@Type,Website=@Website,IsActive=@IsActive,SortOrder=@SortOrder,ModifiedDateUtc=GETUTCDATE() WHERE MgaWholesalerId=@Id AND IsDeleted=0;"; using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.MgaCode, r.MgaName, r.Type, r.Website, r.IsActive, r.SortOrder }, cancellationToken: ct)); }
    public async Task DeleteAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition("UPDATE Agency.MgaWholesaler SET IsDeleted=1 WHERE MgaWholesalerId=@Id;", new { Id = id }, cancellationToken: ct)); }
}

public sealed class CarrierContactRepository : ICarrierContactRepository
{
    private readonly ISqlConnectionFactory _cf;
    public CarrierContactRepository(ISqlConnectionFactory cf) => _cf = cf;
    private const string Cols = "CarrierContactId, TenantId, CarrierId, ContactName, Title, Email, Phone, Department, IsPrimary, IsActive, CreatedDateUtc";
    public async Task<CarrierContactDto?> GetByIdAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); return await cn.QuerySingleOrDefaultAsync<CarrierContactDto>(new CommandDefinition($"SELECT {Cols} FROM Agency.CarrierContact WHERE CarrierContactId=@Id AND IsDeleted=0;", new { Id = id }, cancellationToken: ct)); }
    public async Task<PagedResult<CarrierContactDto>> SearchAsync(Guid tenantId, string? searchTerm, int pageNumber = 1, int pageSize = 50, CancellationToken ct = default) { var sql = RepositorySql.BuildPagedSearchSql("Agency.CarrierContact", Cols, "ContactName LIKE '%'+@SearchTerm+'%' OR Email LIKE '%'+@SearchTerm+'%'", "ContactName ASC"); using var cn = await _cf.CreateOpenConnectionAsync(ct); using var multi = await cn.QueryMultipleAsync(new CommandDefinition(sql, new { TenantId = tenantId, SearchTerm = searchTerm ?? "", Offset = (Math.Max(pageNumber, 1) - 1) * pageSize, PageSize = pageSize }, cancellationToken: ct)); return new() { Items = (await multi.ReadAsync<CarrierContactDto>()).AsList(), TotalCount = await multi.ReadSingleAsync<int>(), PageNumber = pageNumber, PageSize = pageSize }; }
    public async Task<Guid> CreateAsync(CreateCarrierContactRequest r, CancellationToken ct = default) { const string sql = "INSERT INTO Agency.CarrierContact (CarrierContactId,TenantId,CarrierId,ContactName,Title,Email,Phone,Department,IsPrimary,IsActive,IsDeleted,CreatedDateUtc) VALUES (@Id,@TenantId,@CarrierId,@ContactName,@Title,@Email,@Phone,@Department,@IsPrimary,1,0,GETUTCDATE());"; var id = Guid.NewGuid(); using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.TenantId, r.CarrierId, r.ContactName, r.Title, r.Email, r.Phone, r.Department, r.IsPrimary }, cancellationToken: ct)); return id; }
    public async Task UpdateAsync(Guid id, UpdateCarrierContactRequest r, CancellationToken ct = default) { const string sql = "UPDATE Agency.CarrierContact SET CarrierId=@CarrierId,ContactName=@ContactName,Title=@Title,Email=@Email,Phone=@Phone,Department=@Department,IsPrimary=@IsPrimary,IsActive=@IsActive,ModifiedDateUtc=GETUTCDATE() WHERE CarrierContactId=@Id AND IsDeleted=0;"; using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.CarrierId, r.ContactName, r.Title, r.Email, r.Phone, r.Department, r.IsPrimary, r.IsActive }, cancellationToken: ct)); }
    public async Task DeleteAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition("UPDATE Agency.CarrierContact SET IsDeleted=1 WHERE CarrierContactId=@Id;", new { Id = id }, cancellationToken: ct)); }
}

public sealed class CarrierAppointmentRepository : ICarrierAppointmentRepository
{
    private readonly ISqlConnectionFactory _cf;
    public CarrierAppointmentRepository(ISqlConnectionFactory cf) => _cf = cf;
    private const string Cols = "CarrierAppointmentId, TenantId, CarrierId, AppointmentCode, StateCode, LineOfBusiness, AppointmentDate, ExpirationDate, IsActive, CreatedDateUtc";
    public async Task<CarrierAppointmentDto?> GetByIdAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); return await cn.QuerySingleOrDefaultAsync<CarrierAppointmentDto>(new CommandDefinition($"SELECT {Cols} FROM Agency.CarrierAppointment WHERE CarrierAppointmentId=@Id AND IsDeleted=0;", new { Id = id }, cancellationToken: ct)); }
    public async Task<PagedResult<CarrierAppointmentDto>> SearchAsync(Guid tenantId, string? searchTerm, int pageNumber = 1, int pageSize = 50, CancellationToken ct = default) { var sql = RepositorySql.BuildPagedSearchSql("Agency.CarrierAppointment", Cols, "AppointmentCode LIKE '%'+@SearchTerm+'%' OR StateCode LIKE '%'+@SearchTerm+'%' OR LineOfBusiness LIKE '%'+@SearchTerm+'%'", "StateCode ASC, LineOfBusiness ASC"); using var cn = await _cf.CreateOpenConnectionAsync(ct); using var multi = await cn.QueryMultipleAsync(new CommandDefinition(sql, new { TenantId = tenantId, SearchTerm = searchTerm ?? "", Offset = (Math.Max(pageNumber, 1) - 1) * pageSize, PageSize = pageSize }, cancellationToken: ct)); return new() { Items = (await multi.ReadAsync<CarrierAppointmentDto>()).AsList(), TotalCount = await multi.ReadSingleAsync<int>(), PageNumber = pageNumber, PageSize = pageSize }; }
    public async Task<Guid> CreateAsync(CreateCarrierAppointmentRequest r, CancellationToken ct = default) { const string sql = "INSERT INTO Agency.CarrierAppointment (CarrierAppointmentId,TenantId,CarrierId,AppointmentCode,StateCode,LineOfBusiness,AppointmentDate,ExpirationDate,IsActive,IsDeleted,CreatedDateUtc) VALUES (@Id,@TenantId,@CarrierId,@AppointmentCode,@StateCode,@LineOfBusiness,@AppointmentDate,@ExpirationDate,1,0,GETUTCDATE());"; var id = Guid.NewGuid(); using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.TenantId, r.CarrierId, r.AppointmentCode, r.StateCode, r.LineOfBusiness, r.AppointmentDate, r.ExpirationDate }, cancellationToken: ct)); return id; }
    public async Task UpdateAsync(Guid id, UpdateCarrierAppointmentRequest r, CancellationToken ct = default) { const string sql = "UPDATE Agency.CarrierAppointment SET CarrierId=@CarrierId,AppointmentCode=@AppointmentCode,StateCode=@StateCode,LineOfBusiness=@LineOfBusiness,AppointmentDate=@AppointmentDate,ExpirationDate=@ExpirationDate,IsActive=@IsActive,ModifiedDateUtc=GETUTCDATE() WHERE CarrierAppointmentId=@Id AND IsDeleted=0;"; using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.CarrierId, r.AppointmentCode, r.StateCode, r.LineOfBusiness, r.AppointmentDate, r.ExpirationDate, r.IsActive }, cancellationToken: ct)); }
    public async Task DeleteAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition("UPDATE Agency.CarrierAppointment SET IsDeleted=1 WHERE CarrierAppointmentId=@Id;", new { Id = id }, cancellationToken: ct)); }
}

public sealed class CarrierPerformanceRepository : ICarrierPerformanceRepository
{
    private readonly ISqlConnectionFactory _cf;
    public CarrierPerformanceRepository(ISqlConnectionFactory cf) => _cf = cf;
    private const string Cols = "CarrierPerformanceId, TenantId, CarrierId, Period, WrittenPremium, LossRatio, HitRatio, QuoteCount, BindCount, IsActive, CreatedDateUtc";
    public async Task<CarrierPerformanceDto?> GetByIdAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); return await cn.QuerySingleOrDefaultAsync<CarrierPerformanceDto>(new CommandDefinition($"SELECT {Cols} FROM Agency.CarrierPerformance WHERE CarrierPerformanceId=@Id AND IsDeleted=0;", new { Id = id }, cancellationToken: ct)); }
    public async Task<PagedResult<CarrierPerformanceDto>> SearchAsync(Guid tenantId, string? searchTerm, int pageNumber = 1, int pageSize = 50, CancellationToken ct = default) { var sql = RepositorySql.BuildPagedSearchSql("Agency.CarrierPerformance", Cols, "Period LIKE '%'+@SearchTerm+'%'", "Period DESC"); using var cn = await _cf.CreateOpenConnectionAsync(ct); using var multi = await cn.QueryMultipleAsync(new CommandDefinition(sql, new { TenantId = tenantId, SearchTerm = searchTerm ?? "", Offset = (Math.Max(pageNumber, 1) - 1) * pageSize, PageSize = pageSize }, cancellationToken: ct)); return new() { Items = (await multi.ReadAsync<CarrierPerformanceDto>()).AsList(), TotalCount = await multi.ReadSingleAsync<int>(), PageNumber = pageNumber, PageSize = pageSize }; }
    public async Task<Guid> CreateAsync(CreateCarrierPerformanceRequest r, CancellationToken ct = default) { const string sql = "INSERT INTO Agency.CarrierPerformance (CarrierPerformanceId,TenantId,CarrierId,Period,WrittenPremium,LossRatio,HitRatio,QuoteCount,BindCount,IsActive,IsDeleted,CreatedDateUtc) VALUES (@Id,@TenantId,@CarrierId,@Period,@WrittenPremium,@LossRatio,@HitRatio,@QuoteCount,@BindCount,1,0,GETUTCDATE());"; var id = Guid.NewGuid(); using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.TenantId, r.CarrierId, r.Period, r.WrittenPremium, r.LossRatio, r.HitRatio, r.QuoteCount, r.BindCount }, cancellationToken: ct)); return id; }
    public async Task UpdateAsync(Guid id, UpdateCarrierPerformanceRequest r, CancellationToken ct = default) { const string sql = "UPDATE Agency.CarrierPerformance SET CarrierId=@CarrierId,Period=@Period,WrittenPremium=@WrittenPremium,LossRatio=@LossRatio,HitRatio=@HitRatio,QuoteCount=@QuoteCount,BindCount=@BindCount,IsActive=@IsActive,ModifiedDateUtc=GETUTCDATE() WHERE CarrierPerformanceId=@Id AND IsDeleted=0;"; using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition(sql, new { Id = id, r.CarrierId, r.Period, r.WrittenPremium, r.LossRatio, r.HitRatio, r.QuoteCount, r.BindCount, r.IsActive }, cancellationToken: ct)); }
    public async Task DeleteAsync(Guid id, CancellationToken ct = default) { using var cn = await _cf.CreateOpenConnectionAsync(ct); await cn.ExecuteAsync(new CommandDefinition("UPDATE Agency.CarrierPerformance SET IsDeleted=1 WHERE CarrierPerformanceId=@Id;", new { Id = id }, cancellationToken: ct)); }
}
