using System.ComponentModel.DataAnnotations;

namespace Ams.Application.Features.CarrierRules;

public sealed record CreateMarketAccessRuleRequest(Guid TenantId, string RuleName, string? CarrierNaic, string? StateCode, string? LobCode, string? AccessLevel, string? Requirements, int Priority);
public sealed record UpdateMarketAccessRuleRequest(string RuleName, string? CarrierNaic, string? StateCode, string? LobCode, string? AccessLevel, string? Requirements, int Priority, bool IsActive);

public sealed record CreateCarrierDownloadMappingRequest(Guid TenantId, string MappingCode, string? CarrierNaic, string? TransactionType, string? SourceField, string? TargetField, string? TransformRule, int SortOrder);
public sealed record UpdateCarrierDownloadMappingRequest(string MappingCode, string? CarrierNaic, string? TransactionType, string? SourceField, string? TargetField, string? TransformRule, bool IsActive, int SortOrder);

public sealed record CreateCarrierProductRuleRequest(
    Guid TenantId,
    Guid? CarrierId,
    [property: StringLength(200)] string? CarrierName,
    [property: StringLength(20)] string? CarrierNaic,
    [property: StringLength(80)] string? CarrierProductCode,
    [property: Required, StringLength(200)] string CarrierProductName,
    Guid? LineOfBusinessId,
    [property: StringLength(80)] string? LineOfBusinessCode,
    [property: StringLength(2, MinimumLength = 2)] string? StateCode,
    [property: Required, StringLength(80)] string RuleCategoryCode,
    [property: Required, StringLength(100)] string RuleCode,
    [property: Required, StringLength(240)] string RuleName,
    [property: StringLength(1000)] string? RuleDescription,
    DateTime EffectiveDate,
    DateTime? ExpirationDate,
    [property: Range(0, 9999)] int Priority,
    [property: StringLength(80)] string? BillingType,
    [property: Range(0, 100)] decimal? MinimumDownPaymentPercent,
    [property: Range(0, 999999999)] decimal? MinimumDownPaymentAmount,
    [property: Range(0, 999)] int? MaximumInstallments,
    bool RequirePaymentBeforeBinding,
    bool AllowPremiumFinance,
    bool AllowAgencyBill,
    bool AllowDirectBill,
    bool AllowZeroDown,
    bool RequireSignedApplication,
    bool RequirePayment,
    bool RequireInspection,
    bool RequirePhotos,
    bool RequireLossRuns,
    bool AllowSameDayBind,
    [property: Range(0, 3660)] int? MaximumAdvanceBindDays,
    bool AllowWeekendBinding,
    TimeSpan? BindingTimeCutoff,
    bool RequireUnderwriterApproval,
    bool RequireACORD125,
    bool RequireACORD126,
    bool RequireACORD127,
    bool RequireStatementOfValues,
    bool RequireFinancialStatement,
    bool RequireSupplementalForm,
    [property: Range(0, 100)] decimal? NewBusinessRate,
    [property: Range(0, 100)] decimal? RenewalRate,
    bool BrokerFeeAllowed,
    [property: Range(0, 999999999)] decimal? MaximumBrokerFee,
    [property: StringLength(240)] string? CommissionSchedule,
    [property: StringLength(120)] string? CommissionPaymentMethod,
    bool ValidateVIN,
    bool ValidateFEIN,
    bool ValidateRoofAge,
    bool ValidateDriverAge,
    bool ValidatePayroll,
    bool ValidateSquareFootage,
    bool ValidateClaimsHistory,
    [property: Required] string RulePayloadJson,
    [property: StringLength(1000)] string? Notes);

public sealed record UpdateCarrierProductRuleRequest(
    Guid? CarrierId,
    [property: StringLength(200)] string? CarrierName,
    [property: StringLength(20)] string? CarrierNaic,
    [property: StringLength(80)] string? CarrierProductCode,
    [property: Required, StringLength(200)] string CarrierProductName,
    Guid? LineOfBusinessId,
    [property: StringLength(80)] string? LineOfBusinessCode,
    [property: StringLength(2, MinimumLength = 2)] string? StateCode,
    [property: Required, StringLength(80)] string RuleCategoryCode,
    [property: Required, StringLength(100)] string RuleCode,
    [property: Required, StringLength(240)] string RuleName,
    [property: StringLength(1000)] string? RuleDescription,
    DateTime EffectiveDate,
    DateTime? ExpirationDate,
    [property: Range(0, 9999)] int Priority,
    [property: StringLength(80)] string? BillingType,
    [property: Range(0, 100)] decimal? MinimumDownPaymentPercent,
    [property: Range(0, 999999999)] decimal? MinimumDownPaymentAmount,
    [property: Range(0, 999)] int? MaximumInstallments,
    bool RequirePaymentBeforeBinding,
    bool AllowPremiumFinance,
    bool AllowAgencyBill,
    bool AllowDirectBill,
    bool AllowZeroDown,
    bool RequireSignedApplication,
    bool RequirePayment,
    bool RequireInspection,
    bool RequirePhotos,
    bool RequireLossRuns,
    bool AllowSameDayBind,
    [property: Range(0, 3660)] int? MaximumAdvanceBindDays,
    bool AllowWeekendBinding,
    TimeSpan? BindingTimeCutoff,
    bool RequireUnderwriterApproval,
    bool RequireACORD125,
    bool RequireACORD126,
    bool RequireACORD127,
    bool RequireStatementOfValues,
    bool RequireFinancialStatement,
    bool RequireSupplementalForm,
    [property: Range(0, 100)] decimal? NewBusinessRate,
    [property: Range(0, 100)] decimal? RenewalRate,
    bool BrokerFeeAllowed,
    [property: Range(0, 999999999)] decimal? MaximumBrokerFee,
    [property: StringLength(240)] string? CommissionSchedule,
    [property: StringLength(120)] string? CommissionPaymentMethod,
    bool ValidateVIN,
    bool ValidateFEIN,
    bool ValidateRoofAge,
    bool ValidateDriverAge,
    bool ValidatePayroll,
    bool ValidateSquareFootage,
    bool ValidateClaimsHistory,
    [property: Required] string RulePayloadJson,
    [property: StringLength(1000)] string? Notes,
    bool IsActive);
