SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
BEGIN TRANSACTION;

IF OBJECT_ID(N'POLOXI.Legal_DecisionResearchNeed', N'U') IS NOT NULL
BEGIN
	IF OBJECT_ID(N'POLOXI.CK_Legal_DecisionResearch_NeedType', N'C') IS NOT NULL
		ALTER TABLE POLOXI.Legal_DecisionResearchNeed
			DROP CONSTRAINT CK_Legal_DecisionResearch_NeedType;

	ALTER TABLE POLOXI.Legal_DecisionResearchNeed WITH CHECK
		ADD CONSTRAINT CK_Legal_DecisionResearch_NeedType CHECK (ResearchNeedTypeCode IN
			(N'LEGAL_AUTHORITY', N'LEGAL_RULE', N'PROCEDURAL_STANDARD', N'MATTER_FACT',
			 N'MATTER_EVIDENCE', N'APPLICATION', N'DERIVED', N'MIXED'));
END

COMMIT TRANSACTION;
