SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
BEGIN TRANSACTION;

-- ────────────────────────────────────────────────────────────────────────────────────────────────
-- POLOXI Legal R1: First-class Outcome Proposal Hierarchy for DECISION_DISCOVERY_V2, idempotent.
-- ADDITIVE enhancement to the existing branch-first discovery prompt. Astra now ALSO proposes an
-- outcomeProposalHierarchy: a first-class DISCOVERY structure of materially-distinct outcome
-- interpretations (O1, O1.1, …) that normalize into the SAME global candidate universe, with each
-- candidate carrying originatingOutcomeNodeIds back to the outcome nodes it was normalized from.
--   • The outcome hierarchy is a DISCOVERY structure — separate from the Section 3 shared legal /
--     factual dependency (EVALUATION) hierarchy. Outcome nodes are NOT independent evidence and are
--     NEVER double-counted in authoritative scoring.
--   • POLOXI Core formulas, the Light Evidence Graph, and the Typed Legal Dependency Graph are
--     UNCHANGED. No new scoring formula, no second engine, no additional LLM call.
--   • Generated by default for LEGAL_DECISION / EVALUATE; NOT forced for IMPLEMENT_DRAFT. General
--     POLOXI Research / Wide (/legal/search) are untouched.
-- The prompt patch is a MINIMAL Section 2 addition + a one-line Section 3 clarification; the output
-- schema gains an OPTIONAL outcomeProposalHierarchy object and candidate originatingOutcomeNodeIds.
-- Idempotent: the prompt/schema UPDATE is guarded by a unique marker; the DDL is IF-guarded.
-- ────────────────────────────────────────────────────────────────────────────────────────────────

-- ── 1) + 2) Patch the DECISION_DISCOVERY_V2 SystemPrompt (Section 2 additive paragraph + Section 3
--    clarification) and extend the OutputSchemaJson (optional outcomeProposalHierarchy object +
--    candidate originatingOutcomeNodeIds). One guarded UPDATE so the whole patch applies exactly once. ──
UPDATE POLOXI.Legal_DecisionPrompt
SET SystemPrompt = REPLACE(
		REPLACE(
			SystemPrompt,
			N'Generate a GLOBAL candidate set of genuinely distinct outcomes responsive to the proposed decisionIntent.',
			N'Generate a GLOBAL candidate set of genuinely distinct outcomes responsive to the proposed decisionIntent. For LEGAL_DECISION / EVALUATE, first propose an outcomeProposalHierarchy representing materially distinct interpretations and prospective outcomes responsive to the decisionIntent. Use L1 for materially distinct outcome interpretations. Use L2/L3+ only where further semantic decomposition identifies a meaningful distinction; do not force a fixed branch count or depth. Preserve stable outcome-node identities, parent-child relationships, descriptions, and the distinction each node represents. Normalize the outcome interpretations into the global candidate set and, on each candidate, preserve explicit originatingOutcomeNodeIds links back to the outcome nodes it was normalized from. Multiple interpretation nodes may normalize to one candidate when they describe the same substantive outcome; materially different outcomes must remain distinct. The outcomeProposalHierarchy is a first-class discovery structure, separate from the shared legal and factual dependency hierarchy. Outcome nodes are not independent evidence supporting their corresponding candidates and must not be double-counted in authoritative scoring. For LEGAL_DECISION / IMPLEMENT_DRAFT, do not force competing outcome branches; follow the drafting objective and its prerequisites.'),
		N'Do NOT use outcome candidates, candidate categories, decision-frame instructions, or generic answer headings as hierarchy branches.',
		N'Do NOT use outcome candidates, candidate categories, decision-frame instructions, or generic answer headings as branches within the shared legal-dependency hierarchy.')
  , OutputSchemaJson = REPLACE(
		REPLACE(
			REPLACE(
				OutputSchemaJson,
				N'"required":["schemaVersion","decisionIntent","queryUnderstanding","semanticRoots","candidates","candidateBranchRelations","unresolvedPropositions","factProvenance","proposalSummary"]',
				N'"required":["schemaVersion","decisionIntent","queryUnderstanding","semanticRoots","candidates","outcomeProposalHierarchy","candidateBranchRelations","unresolvedPropositions","factProvenance","proposalSummary"]'),
			N'"required":["candidateId","resolution","candidateType","rationaleSummary","score"]',
			N'"required":["candidateId","resolution","candidateType","rationaleSummary","score","originatingOutcomeNodeIds"]'),
		N'"score":{"type":["number","null"],"minimum":0,"maximum":1}}}},"candidateBranchRelations"',
		N'"score":{"type":["number","null"],"minimum":0,"maximum":1},"originatingOutcomeNodeIds":{"type":["array","null"],"items":{"type":"string"}}}}},"outcomeProposalHierarchy":{"type":["object","null"],"additionalProperties":false,"required":["nodes"],"properties":{"nodes":{"type":"array","items":{"type":"object","additionalProperties":false,"required":["outcomeNodeId","parentOutcomeNodeId","level","title","description","distinguishingProposition"],"properties":{"outcomeNodeId":{"type":"string"},"parentOutcomeNodeId":{"type":["string","null"]},"level":{"type":["integer","null"]},"title":{"type":"string"},"description":{"type":["string","null"]},"distinguishingProposition":{"type":["string","null"]}}}}}},"candidateBranchRelations"')
  , ModifiedDateUtc = SYSUTCDATETIME()
WHERE PromptCode = N'DECISION_DISCOVERY_V2'
  AND SystemPrompt NOT LIKE N'%The outcomeProposalHierarchy is a first-class discovery structure, separate from the shared legal and factual dependency hierarchy.%';

-- ── 3) First-class Outcome Proposal Hierarchy persistence: the proposed outcome-interpretation nodes
--    (O1, O1.1, …) persisted per session as a typed DISCOVERY artifact. These are NEVER evaluation
--    branches and never carry evidentiary support; POLOXI Core owns all scoring on the shared branch
--    forest. Origin links from normalized candidates are stored on the candidate row (below). ──
IF OBJECT_ID(N'POLOXI.Legal_DecisionOutcomeNode', N'U') IS NULL
CREATE TABLE POLOXI.Legal_DecisionOutcomeNode
(
	DecisionOutcomeNodeId     UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Legal_DecisionOutcomeNode PRIMARY KEY DEFAULT NEWID(),
	DecisionSessionId         UNIQUEIDENTIFIER NOT NULL,
	OutcomeNodeCode           NVARCHAR(100) NOT NULL,
	ParentOutcomeNodeCode     NVARCHAR(100) NULL,
	LevelNumber               INT NOT NULL CONSTRAINT DF_Legal_DecisionOutcomeNode_Level DEFAULT 1,
	Title                     NVARCHAR(MAX) NOT NULL,
	Description               NVARCHAR(MAX) NULL,
	DistinguishingProposition NVARCHAR(MAX) NULL,
	SortOrder                 INT NOT NULL CONSTRAINT DF_Legal_DecisionOutcomeNode_Sort DEFAULT 0,
	TenantId                  UNIQUEIDENTIFIER NOT NULL,
	CreatedDateUtc            DATETIME2 NOT NULL CONSTRAINT DF_Legal_DecisionOutcomeNode_Created DEFAULT SYSUTCDATETIME(),
	CreatedByUserId           UNIQUEIDENTIFIER NULL,
	ModifiedDateUtc           DATETIME2 NULL,
	ModifiedByUserId          UNIQUEIDENTIFIER NULL,
	IsDeleted                 BIT NOT NULL CONSTRAINT DF_Legal_DecisionOutcomeNode_IsDeleted DEFAULT 0,
	CONSTRAINT FK_Legal_DecisionOutcomeNode_Session FOREIGN KEY (DecisionSessionId) REFERENCES POLOXI.Legal_DecisionSession (DecisionSessionId)
);

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'POLOXI.Legal_DecisionOutcomeNode') AND name = N'IX_Legal_DecisionOutcomeNode_Session')
	CREATE INDEX IX_Legal_DecisionOutcomeNode_Session ON POLOXI.Legal_DecisionOutcomeNode (DecisionSessionId) WHERE IsDeleted = 0;

-- ── Candidate origin links (§ normalization step 3): each normalized global candidate preserves the
--    originating outcome-node codes it was discovered from (e.g. "O1,O1.1"). Nullable so the legacy
--    candidate-first path and any response that omits the hierarchy are unaffected. This is DISCOVERY
--    provenance only; it never contributes evidentiary support to the candidate's authoritative score. ──
IF COL_LENGTH(N'POLOXI.Legal_DecisionCandidate', N'OriginatingOutcomeNodeIds') IS NULL
	ALTER TABLE POLOXI.Legal_DecisionCandidate ADD OriginatingOutcomeNodeIds NVARCHAR(MAX) NULL;

COMMIT TRANSACTION;
