using System.Net.Http.Json;
using Ams.Application.Common.Models;
using Ams.Application.Features.Intelligence;

namespace Ams.Web.Services;

public sealed partial class ApiClient
{
    public Task<IntelligenceDashboardDto?> GetIntelligenceDashboardAsync(CancellationToken token=default)=>_httpClient.GetFromJsonAsync<IntelligenceDashboardDto>("api/intelligence/dashboard",token);
    public async Task<IReadOnlyCollection<AiProviderDto>> GetIntelligenceProvidersAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiProviderDto>>("api/intelligence/providers",token)??[];
    public async Task<IReadOnlyCollection<AiModelDeploymentDto>> GetIntelligenceModelsAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiModelDeploymentDto>>("api/intelligence/models",token)??[];
    public async Task<IReadOnlyCollection<AiFeaturePolicyDto>> GetIntelligenceFeaturePoliciesAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiFeaturePolicyDto>>("api/intelligence/feature-policies",token)??[];
    public async Task SaveIntelligenceFeaturePolicyAsync(string featureCode,SaveAiFeaturePolicyRequest request,CancellationToken token=default){var response=await _httpClient.PutAsJsonAsync($"api/intelligence/feature-policies/{Uri.EscapeDataString(featureCode)}",request,token);response.EnsureSuccessStatusCode();}
    public async Task<PagedResult<AiExecutionSummaryDto>> SearchIntelligenceExecutionsAsync(string? search=null,string? feature=null,string? status=null,int pageNumber=1,int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<PagedResult<AiExecutionSummaryDto>>($"api/intelligence/executions?searchTerm={E(search)}&featureCode={E(feature)}&statusCode={E(status)}&pageNumber={pageNumber}&pageSize={pageSize}",token)??new();
    public Task<AiExecutionDetailDto?> GetIntelligenceExecutionAsync(Guid id,CancellationToken token=default)=>_httpClient.GetFromJsonAsync<AiExecutionDetailDto>($"api/intelligence/executions/{id}",token);
    public async Task SubmitIntelligenceFeedbackAsync(Guid id,SubmitAiExecutionFeedbackRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync($"api/intelligence/executions/{id}/feedback",request,token);response.EnsureSuccessStatusCode();}
    public async Task<IReadOnlyCollection<RecommendationTypeDto>> GetRecommendationTypesAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<RecommendationTypeDto>>("api/intelligence/recommendation-types",token)??[];
    public async Task<PagedResult<RecommendationDto>> SearchRecommendationsAsync(string? search=null,string? type=null,string? status=null,string? entityType=null,Guid? entityId=null,int pageNumber=1,int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<PagedResult<RecommendationDto>>($"api/intelligence/recommendations?searchTerm={E(search)}&typeCode={E(type)}&statusCode={E(status)}&entityTypeCode={E(entityType)}&entityId={entityId}&pageNumber={pageNumber}&pageSize={pageSize}",token)??new();
    public async Task QueueRecommendationsAsync(GenerateRecommendationsRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/recommendations/generate",request,token);response.EnsureSuccessStatusCode();}
    public async Task DecideRecommendationAsync(Guid id,DecideRecommendationRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync($"api/intelligence/recommendations/{id}/decision",request,token);response.EnsureSuccessStatusCode();}
    public async Task<IntelligenceSearchResponse?> IntelligenceSearchAsync(IntelligenceSearchRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/search",request,token);response.EnsureSuccessStatusCode();return await response.Content.ReadFromJsonAsync<IntelligenceSearchResponse>(cancellationToken:token);}
    public async Task<PagedResult<AiReviewQueueItemDto>> SearchIntelligenceReviewQueueAsync(string? search=null,string? type=null,string? status=null,string? priority=null,int pageNumber=1,int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<PagedResult<AiReviewQueueItemDto>>($"api/intelligence/review-queue?searchTerm={E(search)}&reviewTypeCode={E(type)}&statusCode={E(status)}&priorityCode={E(priority)}&pageNumber={pageNumber}&pageSize={pageSize}",token)??new();
    public async Task DecideIntelligenceReviewAsync(Guid id,DecideAiReviewRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync($"api/intelligence/review-queue/{id}/decision",request,token);response.EnsureSuccessStatusCode();}
    public async Task<IReadOnlyCollection<AiEvaluationDefinitionDto>> GetIntelligenceEvaluationDefinitionsAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiEvaluationDefinitionDto>>("api/intelligence/evaluations/definitions",token)??[];
    public async Task<IReadOnlyCollection<AiEvaluationRunDto>> GetIntelligenceEvaluationRunsAsync(int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiEvaluationRunDto>>($"api/intelligence/evaluations/runs?pageSize={pageSize}",token)??[];
    public async Task<Guid> QueueIntelligenceEvaluationAsync(QueueAiEvaluationRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/evaluations/runs",request,token);response.EnsureSuccessStatusCode();return (await response.Content.ReadFromJsonAsync<IdResult>(cancellationToken:token))!.Id;}
    private static string E(string? value)=>Uri.EscapeDataString(value??string.Empty);
}
