using System.Net.Http.Json;
using Ams.Application.Common.Models;
using Ams.Application.Features.Intelligence;

namespace Ams.Web.Services;

public sealed partial class ApiClient
{
    public Task<IntelligenceDashboardDto?> GetIntelligenceDashboardAsync(CancellationToken token=default)=>_httpClient.GetFromJsonAsync<IntelligenceDashboardDto>("api/intelligence/dashboard",token);
    public Task<IntelligencePlatformSummaryDto?> GetIntelligencePlatformAsync(CancellationToken token=default)=>_httpClient.GetFromJsonAsync<IntelligencePlatformSummaryDto>("api/intelligence/platform",token);
    public Task<PlatformArchitectureDto?> GetPlatformArchitectureAsync(CancellationToken token=default)=>_httpClient.GetFromJsonAsync<PlatformArchitectureDto>("api/intelligence/platform/architecture",token);
    public async Task<IReadOnlyCollection<IntelligenceEnginePolicyDto>> GetIntelligenceEnginePoliciesAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<IntelligenceEnginePolicyDto>>("api/intelligence/engine-policies",token)??[];
    public async Task SaveIntelligenceEnginePolicyAsync(string policyCode,int versionNumber,SaveIntelligenceEnginePolicyRequest request,CancellationToken token=default){var response=await _httpClient.PutAsJsonAsync($"api/intelligence/engine-policies/{Uri.EscapeDataString(policyCode)}/{versionNumber}",request,token);response.EnsureSuccessStatusCode();}
    public async Task<IReadOnlyCollection<IntelligenceSafetyControlDto>> GetIntelligenceSafetyControlsAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<IntelligenceSafetyControlDto>>("api/intelligence/safety-controls",token)??[];
    public async Task SaveIntelligenceSafetyControlAsync(string controlCode,SaveIntelligenceSafetyControlRequest request,CancellationToken token=default){var response=await _httpClient.PutAsJsonAsync($"api/intelligence/safety-controls/{Uri.EscapeDataString(controlCode)}",request,token);response.EnsureSuccessStatusCode();}
    public async Task<IReadOnlyCollection<IntelligenceComplianceRequirementDto>> GetIntelligenceComplianceRequirementsAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<IntelligenceComplianceRequirementDto>>("api/intelligence/compliance-requirements",token)??[];
    public async Task<IReadOnlyCollection<IntelligenceSafetyEventDto>> GetIntelligenceSafetyEventsAsync(int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<IntelligenceSafetyEventDto>>($"api/intelligence/safety-events?pageSize={pageSize}",token)??[];
    public async Task<IReadOnlyCollection<IntelligencePromptDefinitionDto>> GetIntelligencePromptDefinitionsAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<IntelligencePromptDefinitionDto>>("api/intelligence/prompts",token)??[];
    public async Task SaveIntelligencePromptDefinitionAsync(string promptCode,string versionLabel,SaveIntelligencePromptDefinitionRequest request,CancellationToken token=default){var response=await _httpClient.PutAsJsonAsync($"api/intelligence/prompts/{Uri.EscapeDataString(promptCode)}/{Uri.EscapeDataString(versionLabel)}",request,token);response.EnsureSuccessStatusCode();}
    public async Task SubmitIntelligenceEvaluationLabelAsync(SubmitEvaluationSampleLabelRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/evaluations/labels",request,token);response.EnsureSuccessStatusCode();}
    public async Task<PagedResult<IntelligenceFindingDto>> SearchIntelligenceFindingsAsync(string? search=null,string? capability=null,string? entityType=null,Guid? entityId=null,string? severity=null,string? status=null,int pageNumber=1,int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<PagedResult<IntelligenceFindingDto>>($"api/intelligence/findings?searchTerm={E(search)}&capabilityCode={E(capability)}&entityTypeCode={E(entityType)}&entityId={entityId}&severityCode={E(severity)}&statusCode={E(status)}&pageNumber={pageNumber}&pageSize={pageSize}",token)??new();
    public Task<IntelligenceFindingDetailDto?> GetIntelligenceFindingAsync(Guid id,CancellationToken token=default)=>_httpClient.GetFromJsonAsync<IntelligenceFindingDetailDto>($"api/intelligence/findings/{id}",token);
    public async Task DecideIntelligenceFindingAsync(Guid id,DecideIntelligenceFindingRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync($"api/intelligence/findings/{id}/decision",request,token);response.EnsureSuccessStatusCode();}
    public Task<EntityRelationshipGraphDto?> GetIntelligenceRelationshipsAsync(string entityType,Guid entityId,int maximumDepth=3,CancellationToken token=default)=>_httpClient.GetFromJsonAsync<EntityRelationshipGraphDto>($"api/intelligence/relationships/{Uri.EscapeDataString(entityType)}/{entityId}?maximumDepth={maximumDepth}",token);
    public async Task<IReadOnlyCollection<EntitySimilarityDto>> GetIntelligenceSimilarityAsync(string entityType,Guid entityId,decimal minimumScore=0.7m,int maximumResults=25,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<EntitySimilarityDto>>($"api/intelligence/similarity/{Uri.EscapeDataString(entityType)}/{entityId}?minimumScore={minimumScore}&maximumResults={maximumResults}",token)??[];
    public async Task<PagedResult<BusinessIntelligenceSignalDto>> SearchBusinessIntelligenceSignalsAsync(string? search=null,string? capability=null,string? entityType=null,Guid? entityId=null,string? severity=null,string? status=null,int pageNumber=1,int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<PagedResult<BusinessIntelligenceSignalDto>>($"api/intelligence/business-signals?searchTerm={E(search)}&capabilityCode={E(capability)}&entityTypeCode={E(entityType)}&entityId={entityId}&severityCode={E(severity)}&statusCode={E(status)}&pageNumber={pageNumber}&pageSize={pageSize}",token)??new();
    public async Task DecideBusinessIntelligenceSignalAsync(Guid id,DecideBusinessIntelligenceSignalRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync($"api/intelligence/business-signals/{id}/decision",request,token);response.EnsureSuccessStatusCode();}
    public async Task<InsuranceReasoningResponse?> ExecuteInsuranceReasoningAsync(InsuranceReasoningRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/reasoning",request,token);response.EnsureSuccessStatusCode();return await response.Content.ReadFromJsonAsync<InsuranceReasoningResponse>(cancellationToken:token);}
    public Task<InsuranceReasoningResponse?> GetInsuranceReasoningSessionAsync(Guid id,CancellationToken token=default)=>_httpClient.GetFromJsonAsync<InsuranceReasoningResponse>($"api/intelligence/reasoning/{id}",token);
    public async Task<IReadOnlyCollection<AiProviderDto>> GetIntelligenceProvidersAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiProviderDto>>("api/intelligence/providers",token)??[];
    public async Task<IReadOnlyCollection<AiModelDeploymentDto>> GetIntelligenceModelsAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiModelDeploymentDto>>("api/intelligence/models",token)??[];
    public async Task<IReadOnlyCollection<AiFeaturePolicyDto>> GetIntelligenceFeaturePoliciesAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiFeaturePolicyDto>>("api/intelligence/feature-policies",token)??[];
    public async Task SaveIntelligenceFeaturePolicyAsync(string featureCode,SaveAiFeaturePolicyRequest request,CancellationToken token=default){var response=await _httpClient.PutAsJsonAsync($"api/intelligence/feature-policies/{Uri.EscapeDataString(featureCode)}",request,token);response.EnsureSuccessStatusCode();}
    public async Task<PagedResult<AiExecutionSummaryDto>> SearchIntelligenceExecutionsAsync(string? search=null,string? feature=null,string? status=null,int pageNumber=1,int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<PagedResult<AiExecutionSummaryDto>>($"api/intelligence/executions?searchTerm={E(search)}&featureCode={E(feature)}&statusCode={E(status)}&pageNumber={pageNumber}&pageSize={pageSize}",token)??new();
    public Task<AiExecutionDetailDto?> GetIntelligenceExecutionAsync(Guid id,CancellationToken token=default)=>_httpClient.GetFromJsonAsync<AiExecutionDetailDto>($"api/intelligence/executions/{id}",token);
    public async Task SubmitIntelligenceFeedbackAsync(Guid id,SubmitAiExecutionFeedbackRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync($"api/intelligence/executions/{id}/feedback",request,token);response.EnsureSuccessStatusCode();}
    public async Task<IReadOnlyCollection<RecommendationTypeDto>> GetRecommendationTypesAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<RecommendationTypeDto>>("api/intelligence/recommendation-types",token)??[];
    public async Task<PagedResult<RecommendationDto>> SearchRecommendationsAsync(string? search=null,string? type=null,string? status=null,string? entityType=null,Guid? entityId=null,int pageNumber=1,int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<PagedResult<RecommendationDto>>($"api/intelligence/recommendations?searchTerm={E(search)}&typeCode={E(type)}&statusCode={E(status)}&entityTypeCode={E(entityType)}&entityId={entityId}&pageNumber={pageNumber}&pageSize={pageSize}",token)??new();
    public async Task QueueRecommendationsAsync(GenerateRecommendationsRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/recommendations/generate",request,token);response.EnsureSuccessStatusCode();}
    public async Task DecideRecommendationAsync(Guid id,DecideRecommendationRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync($"api/intelligence/recommendations/{id}/decision",request,token);response.EnsureSuccessStatusCode();}
    public async Task<IntelligenceSearchResponse?> IntelligenceSearchAsync(IntelligenceSearchRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/search",request,token);response.EnsureSuccessStatusCode();return await response.Content.ReadFromJsonAsync<IntelligenceSearchResponse>(cancellationToken:token);}
    public async Task<EphSearchResponse?> IntelligentSearchUsingEphAsync(EphSearchRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/search/eph",request,token);response.EnsureSuccessStatusCode();return await response.Content.ReadFromJsonAsync<EphSearchResponse>(cancellationToken:token);}
    public async Task<EphSearchResponse?> IntelligentSearchUsingEphWideAsync(EphSearchRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence_wide/search/eph_wide",request,token);response.EnsureSuccessStatusCode();return await response.Content.ReadFromJsonAsync<EphSearchResponse>(cancellationToken:token);}

    public async Task<WideSearchResponse?> IntelligentSearchWideDynamicAsync(WideSearchRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence_wide/search/dynamic",request,token);response.EnsureSuccessStatusCode();return await response.Content.ReadFromJsonAsync<WideSearchResponse>(cancellationToken:token);}
    public async Task<QuickSearchFastPathResponse?> QuickSearchFastPathAsync(QuickSearchRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/quick-search/fast",request,token);response.EnsureSuccessStatusCode();return await response.Content.ReadFromJsonAsync<QuickSearchFastPathResponse>(cancellationToken:token);}
    public async Task<QuickSearchResponse?> QuickSearchIntelligentFallbackAsync(QuickSearchRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/quick-search/intelligent-fallback",request,token);response.EnsureSuccessStatusCode();return await response.Content.ReadFromJsonAsync<QuickSearchResponse>(cancellationToken:token);}
    public async Task<PagedResult<AiReviewQueueItemDto>> SearchIntelligenceReviewQueueAsync(string? search=null,string? type=null,string? status=null,string? priority=null,int pageNumber=1,int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<PagedResult<AiReviewQueueItemDto>>($"api/intelligence/review-queue?searchTerm={E(search)}&reviewTypeCode={E(type)}&statusCode={E(status)}&priorityCode={E(priority)}&pageNumber={pageNumber}&pageSize={pageSize}",token)??new();
    public async Task DecideIntelligenceReviewAsync(Guid id,DecideAiReviewRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync($"api/intelligence/review-queue/{id}/decision",request,token);response.EnsureSuccessStatusCode();}
    public async Task<IReadOnlyCollection<AiEvaluationDefinitionDto>> GetIntelligenceEvaluationDefinitionsAsync(CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiEvaluationDefinitionDto>>("api/intelligence/evaluations/definitions",token)??[];
    public async Task<IReadOnlyCollection<AiEvaluationRunDto>> GetIntelligenceEvaluationRunsAsync(int pageSize=100,CancellationToken token=default)=>await _httpClient.GetFromJsonAsync<IReadOnlyCollection<AiEvaluationRunDto>>($"api/intelligence/evaluations/runs?pageSize={pageSize}",token)??[];
    public async Task<Guid> QueueIntelligenceEvaluationAsync(QueueAiEvaluationRequest request,CancellationToken token=default){var response=await _httpClient.PostAsJsonAsync("api/intelligence/evaluations/runs",request,token);response.EnsureSuccessStatusCode();return (await response.Content.ReadFromJsonAsync<IdResult>(cancellationToken:token))!.Id;}
    private static string E(string? value)=>Uri.EscapeDataString(value??string.Empty);
}
