namespace Ams.Knowledge.Application.Features.Knowledge;

public sealed record ConceptSchemeDto(Guid ConceptSchemeId, string SchemeCode, string Name, string? Description, string AuthorityCode, string? VersionLabel, string StatusCode, Guid? TenantId, bool IsSystemDefined, byte[] RowVersion);
public sealed record KnowledgeConceptDto(Guid KnowledgeConceptId, Guid ConceptSchemeId, string ConceptCode, string ConceptTypeCode, string PreferredLabel, string? Definition, Guid? ParentConceptId, bool IsAbstract, bool IsSelectable, string StatusCode, DateTime EffectiveFromUtc, DateTime? EffectiveToUtc, int VersionNumber, Guid? SupersedesConceptId, Guid? TenantId, bool IsSystemDefined, Guid OwnerUserId, Guid BusinessStewardUserId, Guid? TechnicalStewardUserId, string DefinitionSource, string? LicensingNotes, byte[] RowVersion);
public sealed record ConceptLabelDto(Guid ConceptLabelId, Guid KnowledgeConceptId, string Label, string NormalizedLabel, string LabelTypeCode, string LanguageCode, string? Source, bool IsSearchable, bool IsDeprecated, Guid? TenantId, byte[] RowVersion);
public sealed record ConceptRelationshipDto(Guid ConceptRelationshipId, Guid SubjectConceptId, string PredicateCode, Guid ObjectConceptId, decimal? RelationshipStrength, string? Source, DateTime EffectiveFromUtc, DateTime? EffectiveToUtc, string StatusCode, Guid? TenantId, byte[] RowVersion);
public sealed record ExternalConceptMappingDto(Guid ExternalConceptMappingId, Guid KnowledgeConceptId, string SourceSystemTypeCode, Guid? SourceSystemId, string? ExternalCode, string ExternalValue, string MappingDirectionCode, string MatchTypeCode, decimal? ConfidenceScore, string? StateCode, Guid? LineOfBusinessConceptId, Guid? CarrierProductId, bool IsApproved, Guid? ApprovedByUserId, DateTime? ApprovedUtc, Guid? TenantId, byte[] RowVersion);
public sealed record MappingReviewDto(Guid MappingReviewId, Guid ExternalConceptMappingId, string StatusCode, string? RecommendationJson, Guid? ReviewedByUserId, DateTime? ReviewedUtc, string? ReviewReason, Guid TenantId, byte[] RowVersion);
public sealed record KnowledgeLookupDto(string LookupTypeCode, string ValueCode, string DisplayName, string? Description, int SortOrder, bool IsActive);
public sealed record KnowledgeDashboardDto(int ActiveSchemes, int PublishedConcepts, int SearchableLabels, int ApprovedMappings, int PendingMappingReviews, int DraftChangeRequests, int FailedImports);
public sealed record KnowledgeAuditDto(Guid AuditEventId, Guid TenantId, Guid? ActorUserId, string ActionType, string? EntityName, Guid? EntityId, string? OldValue, string? NewValue, string? CorrelationId, string? ChangeReason, int? VersionNumber, DateTime CreatedUtc);
public sealed record KnowledgeImportDto(Guid ImportJobId, string ImportTypeCode, string SourceFileName, string StorageReference, string StatusCode, string CorrelationId, int RecordsReceived, int RecordsProcessed, int RecordsFailed, string? ErrorMessage, int RetryCount, Guid TenantId, DateTime CreatedDateUtc, byte[] RowVersion);
public sealed record KnowledgePublicationDto(Guid PublicationId, string PublicationCode, string Name, string VersionLabel, string StatusCode, Guid? TenantId, bool IsSystemDefined, Guid? PublishedByUserId, DateTime? PublishedDateUtc, int ItemCount, byte[] RowVersion);
public sealed record KnowledgeValidationRuleDto(Guid ConceptValidationRuleId, Guid AppliesToConceptId, string RuleCode, string RuleTypeCode, string? PropertyPath, string OperatorCode, string? ExpectedValue, int? MinimumCount, int? MaximumCount, string SeverityCode, string Message, DateTime EffectiveFromUtc, DateTime? EffectiveToUtc, string StatusCode, Guid? TenantId, bool IsSystemDefined, byte[] RowVersion);
public sealed record KnowledgeRelationshipPredicateDto(string PredicateCode, string DisplayName, string? Description, bool IsHierarchical, bool SubjectIsChild, string? InversePredicateCode);
