using System.ComponentModel.DataAnnotations;
using Ams.Application.Abstractions.Intelligence;
using Ams.Application.Abstractions.Persistence;
using Ams.Application.Abstractions.Services;
using Ams.Application.Common.Models;
using Ams.Application.Features.Intelligence;

namespace Ams.Application;

public sealed class IntelligenceService(IIntelligenceRepository repository,IRecommendationGenerationRepository recommendationRepository,ISemanticQueryExpander queryExpander):IIntelligenceService
{
    public Task<IReadOnlyCollection<AiProviderDto>> GetProvidersAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetProvidersAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task<IReadOnlyCollection<AiModelDeploymentDto>> GetModelsAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetModelsAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task<IReadOnlyCollection<AiFeaturePolicyDto>> GetFeaturePoliciesAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetFeaturePoliciesAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task SaveFeaturePolicyAsync(SaveAiFeaturePolicyRequest request,CancellationToken cancellationToken=default){Validate(request);return repository.SaveFeaturePolicyAsync(request,cancellationToken);}
    public Task<PagedResult<AiExecutionSummaryDto>> SearchExecutionsAsync(SearchAiExecutionsQuery query,CancellationToken cancellationToken=default){ValidatePage(query.TenantId,query.PageNumber,query.PageSize);return repository.SearchExecutionsAsync(query with{PageSize=Math.Clamp(query.PageSize,1,200)},cancellationToken);}
    public Task<AiExecutionDetailDto?> GetExecutionAsync(Guid tenantId,Guid executionId,CancellationToken cancellationToken=default)=>repository.GetExecutionAsync(Required(tenantId,nameof(tenantId)),Required(executionId,nameof(executionId)),cancellationToken);
    public Task SubmitExecutionFeedbackAsync(SubmitAiExecutionFeedbackRequest request,CancellationToken cancellationToken=default){Validate(request);return repository.SubmitExecutionFeedbackAsync(request,cancellationToken);}
    public Task<IReadOnlyCollection<RecommendationTypeDto>> GetRecommendationTypesAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetRecommendationTypesAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task<PagedResult<RecommendationDto>> SearchRecommendationsAsync(SearchRecommendationsQuery query,CancellationToken cancellationToken=default){ValidatePage(query.TenantId,query.PageNumber,query.PageSize);return repository.SearchRecommendationsAsync(query with{PageSize=Math.Clamp(query.PageSize,1,200)},cancellationToken);}
    public Task QueueRecommendationsAsync(GenerateRecommendationsRequest request,CancellationToken cancellationToken=default){Validate(request);return recommendationRepository.GenerateAsync(request,cancellationToken);}
    public Task DecideRecommendationAsync(DecideRecommendationRequest request,CancellationToken cancellationToken=default){Validate(request);return repository.DecideRecommendationAsync(request,cancellationToken);}
    public async Task<IntelligenceSearchResponse> SearchAsync(IntelligenceSearchRequest request,CancellationToken cancellationToken=default){Validate(request);var expansion=await queryExpander.ExpandAsync(request.TenantId,request.Query,20,cancellationToken);return await repository.SearchAsync(request with{MaximumResults=Math.Clamp(request.MaximumResults,1,100)},expansion.Concepts,expansion.Terms,cancellationToken);}
    public Task<PagedResult<AiReviewQueueItemDto>> SearchReviewQueueAsync(SearchAiReviewQueueQuery query,CancellationToken cancellationToken=default){ValidatePage(query.TenantId,query.PageNumber,query.PageSize);return repository.SearchReviewQueueAsync(query with{PageSize=Math.Clamp(query.PageSize,1,200)},cancellationToken);}
    public Task DecideReviewAsync(DecideAiReviewRequest request,CancellationToken cancellationToken=default){Validate(request);return repository.DecideReviewAsync(request,cancellationToken);}
    public Task<IReadOnlyCollection<AiEvaluationDefinitionDto>> GetEvaluationDefinitionsAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetEvaluationDefinitionsAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task<IReadOnlyCollection<AiEvaluationRunDto>> GetEvaluationRunsAsync(Guid tenantId,int pageSize,CancellationToken cancellationToken=default)=>repository.GetEvaluationRunsAsync(Required(tenantId,nameof(tenantId)),Math.Clamp(pageSize,1,500),cancellationToken);
    public Task<Guid> QueueEvaluationAsync(QueueAiEvaluationRequest request,CancellationToken cancellationToken=default){Validate(request);if(request.WindowEndUtc<=request.WindowStartUtc)throw new ValidationException("Evaluation window end must be after its start.");return repository.QueueEvaluationAsync(request,cancellationToken);}
    public Task<IntelligenceDashboardDto> GetDashboardAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetDashboardAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task<IntelligencePlatformSummaryDto> GetPlatformSummaryAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetPlatformSummaryAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task<PlatformArchitectureDto> GetPlatformArchitectureAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetPlatformArchitectureAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task<IReadOnlyCollection<IntelligenceEnginePolicyDto>> GetEnginePoliciesAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetEnginePoliciesAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task SaveEnginePolicyAsync(SaveIntelligenceEnginePolicyRequest request,CancellationToken cancellationToken=default){Validate(request);ValidateJson(request.ConfigurationJson,nameof(request.ConfigurationJson));if(request.EffectiveToUtc<=request.EffectiveFromUtc)throw new ValidationException("Effective end must be after effective start.");return repository.SaveEnginePolicyAsync(request,cancellationToken);}
    public Task<IReadOnlyCollection<IntelligenceSafetyControlDto>> GetSafetyControlsAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetSafetyControlsAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task SaveSafetyControlAsync(SaveIntelligenceSafetyControlRequest request,CancellationToken cancellationToken=default){Validate(request);ValidateJson(request.ConfigurationJson,nameof(request.ConfigurationJson));return repository.SaveSafetyControlAsync(request,cancellationToken);}
    public Task<IReadOnlyCollection<IntelligenceComplianceRequirementDto>> GetComplianceRequirementsAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetComplianceRequirementsAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task<IReadOnlyCollection<IntelligenceSafetyEventDto>> GetSafetyEventsAsync(Guid tenantId,int pageSize,CancellationToken cancellationToken=default)=>repository.GetSafetyEventsAsync(Required(tenantId,nameof(tenantId)),Math.Clamp(pageSize,1,500),cancellationToken);
    public Task<IReadOnlyCollection<IntelligencePromptDefinitionDto>> GetPromptDefinitionsAsync(Guid tenantId,CancellationToken cancellationToken=default)=>repository.GetPromptDefinitionsAsync(Required(tenantId,nameof(tenantId)),cancellationToken);
    public Task SavePromptDefinitionAsync(SaveIntelligencePromptDefinitionRequest request,CancellationToken cancellationToken=default){Validate(request);ValidateJson(request.InputSchemaJson,nameof(request.InputSchemaJson));ValidateJson(request.OutputSchemaJson,nameof(request.OutputSchemaJson));if(request.EffectiveToUtc<=request.EffectiveFromUtc)throw new ValidationException("Effective end must be after effective start.");return repository.SavePromptDefinitionAsync(request,cancellationToken);}
    public Task SubmitEvaluationSampleLabelAsync(SubmitEvaluationSampleLabelRequest request,CancellationToken cancellationToken=default){Validate(request);return repository.SubmitEvaluationSampleLabelAsync(request,cancellationToken);}
    public Task<PagedResult<IntelligenceFindingDto>> SearchFindingsAsync(SearchIntelligenceFindingsQuery query,CancellationToken cancellationToken=default){ValidatePage(query.TenantId,query.PageNumber,query.PageSize);return repository.SearchFindingsAsync(query with{PageSize=Math.Clamp(query.PageSize,1,200)},cancellationToken);}
    public Task<IntelligenceFindingDetailDto?> GetFindingAsync(Guid tenantId,Guid findingId,CancellationToken cancellationToken=default)=>repository.GetFindingAsync(Required(tenantId,nameof(tenantId)),Required(findingId,nameof(findingId)),cancellationToken);
    public Task DecideFindingAsync(DecideIntelligenceFindingRequest request,CancellationToken cancellationToken=default){Validate(request);return repository.DecideFindingAsync(request,cancellationToken);}
    public Task<EntityRelationshipGraphDto> GetRelationshipGraphAsync(RelationshipQuery query,CancellationToken cancellationToken=default){Validate(query);return repository.GetRelationshipGraphAsync(query with{MaximumDepth=Math.Clamp(query.MaximumDepth,1,10)},cancellationToken);}
    public Task<IReadOnlyCollection<EntitySimilarityDto>> GetSimilarEntitiesAsync(SimilarityQuery query,CancellationToken cancellationToken=default){Validate(query);return repository.GetSimilarEntitiesAsync(query with{MaximumResults=Math.Clamp(query.MaximumResults,1,100)},cancellationToken);}
    public Task<PagedResult<BusinessIntelligenceSignalDto>> SearchBusinessSignalsAsync(SearchBusinessIntelligenceSignalsQuery query,CancellationToken cancellationToken=default){ValidatePage(query.TenantId,query.PageNumber,query.PageSize);return repository.SearchBusinessSignalsAsync(query with{PageSize=Math.Clamp(query.PageSize,1,200)},cancellationToken);}
    public Task DecideBusinessSignalAsync(DecideBusinessIntelligenceSignalRequest request,CancellationToken cancellationToken=default){Validate(request);return repository.DecideBusinessSignalAsync(request,cancellationToken);}
    public async Task<InsuranceReasoningResponse> ExecuteReasoningAsync(InsuranceReasoningRequest request,CancellationToken cancellationToken=default){Validate(request);if(!request.GrantedPermissions.Contains("Intelligence.Reason",StringComparer.OrdinalIgnoreCase)&&!request.GrantedPermissions.Contains("NAV_ALL",StringComparer.OrdinalIgnoreCase))throw new ValidationException("Insurance reasoning permission is required.");var expansion=await queryExpander.ExpandAsync(request.TenantId,request.Question,20,cancellationToken);return await repository.ExecuteReasoningAsync(request,expansion.Concepts,cancellationToken);}
    public Task<InsuranceReasoningResponse?> GetReasoningSessionAsync(Guid tenantId,Guid userId,Guid reasoningSessionId,CancellationToken cancellationToken=default)=>repository.GetReasoningSessionAsync(Required(tenantId,nameof(tenantId)),Required(userId,nameof(userId)),Required(reasoningSessionId,nameof(reasoningSessionId)),cancellationToken);

    private static Guid Required(Guid value,string name)=>value==Guid.Empty?throw new ValidationException($"{name} is required."):value;
    private static void ValidatePage(Guid tenantId,int pageNumber,int pageSize){Required(tenantId,nameof(tenantId));if(pageNumber<1||pageSize<1)throw new ValidationException("Page number and page size must be positive.");}
    private static void Validate(object request){var context=new ValidationContext(request);Validator.ValidateObject(request,context,true);foreach(var property in request.GetType().GetProperties().Where(x=>x.PropertyType==typeof(Guid))){if((Guid)(property.GetValue(request)??Guid.Empty)==Guid.Empty)throw new ValidationException($"{property.Name} is required.");}}
    private static void ValidateJson(string value,string name){try{using var _=System.Text.Json.JsonDocument.Parse(value);}catch(System.Text.Json.JsonException ex){throw new ValidationException($"{name} must contain valid JSON.",ex);}}
}
