<Project Sdk="Microsoft.NET.Sdk.Worker">
	<PropertyGroup>
	<UserSecretsId>ams-worker-local-secrets</UserSecretsId>
	<DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**;artifacts/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
	<ProjectReference Include="..\src\Ams.Application\Ams.Application.csproj" />
	<ProjectReference Include="..\src\Ams.Infrastructure\Ams.Infrastructure.csproj" />
	<ProjectReference Include="..\src\Modules\Knowledge\Ams.Knowledge.Application\Ams.Knowledge.Application.csproj" />
	<ProjectReference Include="..\src\Modules\Knowledge\Ams.Knowledge.Infrastructure\Ams.Knowledge.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
	<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
	<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
	<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Settings.job">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
	  <None Update="appsettings.Development.json">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	</None>
  </ItemGroup>
</Project>
