SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF NOT EXISTS(SELECT 1 FROM sys.schemas WHERE name=N'AI') EXEC(N'CREATE SCHEMA AI');

IF OBJECT_ID(N'AI.Provider',N'U') IS NULL CREATE TABLE AI.Provider(ProviderId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_Provider PRIMARY KEY, TenantId UNIQUEIDENTIFIER NULL,ProviderCode NVARCHAR(100) NOT NULL,DisplayName NVARCHAR(200) NOT NULL,ProviderTypeCode NVARCHAR(50) NOT NULL,EndpointConfigurationKey NVARCHAR(200) NULL,CredentialConfigurationKey NVARCHAR(200) NULL,SupportsChat BIT NOT NULL,SupportsEmbeddings BIT NOT NULL,SupportsVision BIT NOT NULL,SupportsStructuredOutput BIT NOT NULL,Priority INT NOT NULL,IsActive BIT NOT NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_Provider_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.Provider') AND name=N'UX_AI_Provider_Code') CREATE UNIQUE INDEX UX_AI_Provider_Code ON AI.Provider(ProviderCode) WHERE TenantId IS NULL AND IsDeleted=0;

IF OBJECT_ID(N'AI.ModelDeployment',N'U') IS NULL CREATE TABLE AI.ModelDeployment(ModelDeploymentId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_ModelDeployment PRIMARY KEY,TenantId UNIQUEIDENTIFIER NULL,ProviderId UNIQUEIDENTIFIER NOT NULL,ModelCode NVARCHAR(100) NOT NULL,DeploymentName NVARCHAR(200) NOT NULL,ModelFamily NVARCHAR(100) NOT NULL,CapabilityCode NVARCHAR(50) NOT NULL,ContextWindowTokens INT NOT NULL,MaximumOutputTokens INT NOT NULL,InputCostPerMillionTokens DECIMAL(18,6) NULL,OutputCostPerMillionTokens DECIMAL(18,6) NULL,CurrencyCode CHAR(3) NOT NULL,Priority INT NOT NULL,IsFallback BIT NOT NULL,IsActive BIT NOT NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_Model_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_AI_Model_Provider FOREIGN KEY(ProviderId) REFERENCES AI.Provider(ProviderId),CONSTRAINT CK_AI_Model_Tokens CHECK(ContextWindowTokens>0 AND MaximumOutputTokens>0));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.ModelDeployment') AND name=N'UX_AI_Model_Code') CREATE UNIQUE INDEX UX_AI_Model_Code ON AI.ModelDeployment(ProviderId,ModelCode,TenantId) WHERE IsDeleted=0;

IF OBJECT_ID(N'AI.FeaturePolicy',N'U') IS NULL CREATE TABLE AI.FeaturePolicy(FeaturePolicyId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_FeaturePolicy PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,FeatureCode NVARCHAR(100) NOT NULL,ModuleCode NVARCHAR(100) NOT NULL,PrimaryModelDeploymentId UNIQUEIDENTIFIER NULL,FallbackModelDeploymentId UNIQUEIDENTIFIER NULL,Temperature DECIMAL(4,3) NOT NULL,MaximumInputTokens INT NOT NULL,MaximumOutputTokens INT NOT NULL,TimeoutSeconds INT NOT NULL,DailyCostLimit DECIMAL(18,4) NULL,MonthlyCostLimit DECIMAL(18,4) NULL,MinimumConfidence DECIMAL(5,4) NOT NULL,RequiresHumanReview BIT NOT NULL,IsEnabled BIT NOT NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_FeaturePolicy_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_AI_FeaturePolicy_Primary FOREIGN KEY(PrimaryModelDeploymentId) REFERENCES AI.ModelDeployment(ModelDeploymentId),CONSTRAINT FK_AI_FeaturePolicy_Fallback FOREIGN KEY(FallbackModelDeploymentId) REFERENCES AI.ModelDeployment(ModelDeploymentId),CONSTRAINT CK_AI_FeaturePolicy_Values CHECK(Temperature BETWEEN 0 AND 2 AND MaximumInputTokens>0 AND MaximumOutputTokens>0 AND TimeoutSeconds BETWEEN 1 AND 900 AND MinimumConfidence BETWEEN 0 AND 1));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.FeaturePolicy') AND name=N'UX_AI_FeaturePolicy_TenantFeature') CREATE UNIQUE INDEX UX_AI_FeaturePolicy_TenantFeature ON AI.FeaturePolicy(TenantId,FeatureCode) WHERE IsDeleted=0;

IF OBJECT_ID(N'AI.Execution',N'U') IS NULL CREATE TABLE AI.Execution(ExecutionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_Execution PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,FeatureCode NVARCHAR(100) NOT NULL,ModuleCode NVARCHAR(100) NOT NULL,EntityTypeCode NVARCHAR(100) NULL,EntityId UNIQUEIDENTIFIER NULL,PromptDefinitionId UNIQUEIDENTIFIER NULL,PromptVersion NVARCHAR(50) NULL,ProviderId UNIQUEIDENTIFIER NULL,ModelDeploymentId UNIQUEIDENTIFIER NULL,StatusCode NVARCHAR(30) NOT NULL,CorrelationId NVARCHAR(120) NOT NULL,RequestedByUserId UNIQUEIDENTIFIER NULL,StartedDateUtc DATETIME2 NOT NULL,CompletedDateUtc DATETIME2 NULL,DurationMilliseconds BIGINT NULL,InputTokenCount INT NULL,OutputTokenCount INT NULL,EstimatedCost DECIMAL(18,6) NULL,CurrencyCode CHAR(3) NULL,Confidence DECIMAL(5,4) NULL,GroundingSourceCount INT NOT NULL CONSTRAINT DF_AI_Execution_Grounding DEFAULT 0,InputReference NVARCHAR(2000) NULL,OutputReference NVARCHAR(2000) NULL,ErrorCode NVARCHAR(100) NULL,ErrorMessage NVARCHAR(4000) NULL,CreatedDateUtc DATETIME2 NOT NULL CONSTRAINT DF_AI_Execution_Created DEFAULT SYSUTCDATETIME(),CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_Execution_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_AI_Execution_Provider FOREIGN KEY(ProviderId) REFERENCES AI.Provider(ProviderId),CONSTRAINT FK_AI_Execution_Model FOREIGN KEY(ModelDeploymentId) REFERENCES AI.ModelDeployment(ModelDeploymentId),CONSTRAINT CK_AI_Execution_Confidence CHECK(Confidence IS NULL OR Confidence BETWEEN 0 AND 1));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.Execution') AND name=N'IX_AI_Execution_TenantDate') CREATE INDEX IX_AI_Execution_TenantDate ON AI.Execution(TenantId,CreatedDateUtc DESC) INCLUDE(FeatureCode,StatusCode,EstimatedCost,Confidence,DurationMilliseconds);

IF OBJECT_ID(N'AI.ExecutionGroundingSource',N'U') IS NULL CREATE TABLE AI.ExecutionGroundingSource(ExecutionGroundingSourceId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_ExecutionGrounding PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,ExecutionId UNIQUEIDENTIFIER NOT NULL,SourceTypeCode NVARCHAR(50) NOT NULL,SourceEntityId UNIQUEIDENTIFIER NULL,SourceReference NVARCHAR(2000) NOT NULL,Title NVARCHAR(500) NULL,RelevanceScore DECIMAL(5,4) NULL,ExcerptHash CHAR(64) NULL,CreatedDateUtc DATETIME2 NOT NULL CONSTRAINT DF_AI_Grounding_Created DEFAULT SYSUTCDATETIME(),CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_Grounding_Deleted DEFAULT 0,CONSTRAINT FK_AI_Grounding_Execution FOREIGN KEY(ExecutionId) REFERENCES AI.Execution(ExecutionId));
IF OBJECT_ID(N'AI.ExecutionFeedback',N'U') IS NULL CREATE TABLE AI.ExecutionFeedback(ExecutionFeedbackId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_ExecutionFeedback PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,ExecutionId UNIQUEIDENTIFIER NOT NULL,FeedbackTypeCode NVARCHAR(50) NOT NULL,Rating SMALLINT NULL,CorrectionReference NVARCHAR(2000) NULL,Comment NVARCHAR(2000) NULL,DecisionCode NVARCHAR(30) NULL,ReviewedByUserId UNIQUEIDENTIFIER NULL,ReviewedDateUtc DATETIME2 NULL,CreatedDateUtc DATETIME2 NOT NULL CONSTRAINT DF_AI_Feedback_Created DEFAULT SYSUTCDATETIME(),CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_Feedback_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_AI_Feedback_Execution FOREIGN KEY(ExecutionId) REFERENCES AI.Execution(ExecutionId),CONSTRAINT CK_AI_Feedback_Rating CHECK(Rating IS NULL OR Rating BETWEEN 1 AND 5));

IF OBJECT_ID(N'AI.RecommendationType',N'U') IS NULL CREATE TABLE AI.RecommendationType(RecommendationTypeId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_RecommendationType PRIMARY KEY, TenantId UNIQUEIDENTIFIER NULL,TypeCode NVARCHAR(100) NOT NULL,DisplayName NVARCHAR(200) NOT NULL,Description NVARCHAR(1000) NULL,TargetModuleCode NVARCHAR(100) NOT NULL,DefaultPriorityCode NVARCHAR(30) NOT NULL,DefaultExpirationHours INT NULL,RequiresHumanReview BIT NOT NULL,SortOrder INT NOT NULL,IsActive BIT NOT NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_RecommendationType_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.RecommendationType') AND name=N'UX_AI_RecommendationType_Code') CREATE UNIQUE INDEX UX_AI_RecommendationType_Code ON AI.RecommendationType(TypeCode) WHERE TenantId IS NULL AND IsDeleted=0;
IF OBJECT_ID(N'AI.RecommendationRule',N'U') IS NULL CREATE TABLE AI.RecommendationRule(RecommendationRuleId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_RecommendationRule PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,RecommendationTypeId UNIQUEIDENTIFIER NOT NULL,RuleCode NVARCHAR(100) NOT NULL,Name NVARCHAR(200) NOT NULL,Description NVARCHAR(1000) NULL,EntityTypeCode NVARCHAR(100) NOT NULL,ConditionJson NVARCHAR(MAX) NOT NULL,ActionJson NVARCHAR(MAX) NOT NULL,Priority INT NOT NULL,MinimumConfidence DECIMAL(5,4) NOT NULL,EffectiveFromUtc DATETIME2 NOT NULL,EffectiveToUtc DATETIME2 NULL,IsActive BIT NOT NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_RecommendationRule_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_AI_RecommendationRule_Type FOREIGN KEY(RecommendationTypeId) REFERENCES AI.RecommendationType(RecommendationTypeId));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.RecommendationRule') AND name=N'UX_AI_RecommendationRule_Code') CREATE UNIQUE INDEX UX_AI_RecommendationRule_Code ON AI.RecommendationRule(TenantId,RuleCode) WHERE IsDeleted=0;
IF OBJECT_ID(N'AI.Recommendation',N'U') IS NULL CREATE TABLE AI.Recommendation(RecommendationId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_Recommendation PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,RecommendationTypeId UNIQUEIDENTIFIER NOT NULL,RecommendationRuleId UNIQUEIDENTIFIER NULL,ExecutionId UNIQUEIDENTIFIER NULL,EntityTypeCode NVARCHAR(100) NOT NULL,EntityId UNIQUEIDENTIFIER NOT NULL,Title NVARCHAR(300) NOT NULL,Summary NVARCHAR(2000) NOT NULL,Rationale NVARCHAR(MAX) NULL,ActionCode NVARCHAR(100) NULL,ActionPayloadJson NVARCHAR(MAX) NULL,PriorityCode NVARCHAR(30) NOT NULL,StatusCode NVARCHAR(30) NOT NULL,Confidence DECIMAL(5,4) NOT NULL,Score DECIMAL(18,6) NOT NULL,AssignedToUserId UNIQUEIDENTIFIER NULL,ExpiresDateUtc DATETIME2 NULL,CompletedDateUtc DATETIME2 NULL,DismissedReason NVARCHAR(1000) NULL,IdempotencyKey NVARCHAR(240) NOT NULL,CreatedDateUtc DATETIME2 NOT NULL CONSTRAINT DF_AI_Recommendation_Created DEFAULT SYSUTCDATETIME(),CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_Recommendation_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_AI_Recommendation_Type FOREIGN KEY(RecommendationTypeId) REFERENCES AI.RecommendationType(RecommendationTypeId),CONSTRAINT FK_AI_Recommendation_Rule FOREIGN KEY(RecommendationRuleId) REFERENCES AI.RecommendationRule(RecommendationRuleId),CONSTRAINT FK_AI_Recommendation_Execution FOREIGN KEY(ExecutionId) REFERENCES AI.Execution(ExecutionId),CONSTRAINT CK_AI_Recommendation_Confidence CHECK(Confidence BETWEEN 0 AND 1));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.Recommendation') AND name=N'UX_AI_Recommendation_Idempotency') CREATE UNIQUE INDEX UX_AI_Recommendation_Idempotency ON AI.Recommendation(TenantId,IdempotencyKey) WHERE IsDeleted=0;
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.Recommendation') AND name=N'IX_AI_Recommendation_Worklist') CREATE INDEX IX_AI_Recommendation_Worklist ON AI.Recommendation(TenantId,StatusCode,PriorityCode,CreatedDateUtc DESC) INCLUDE(EntityTypeCode,EntityId,Title,Confidence,AssignedToUserId);
IF OBJECT_ID(N'AI.RecommendationWorkItem',N'U') IS NULL CREATE TABLE AI.RecommendationWorkItem(RecommendationWorkItemId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_RecommendationWorkItem PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,EntityTypeCode NVARCHAR(100) NOT NULL,EntityId UNIQUEIDENTIFIER NOT NULL,StatusCode NVARCHAR(30) NOT NULL,AttemptCount INT NOT NULL,MaximumAttempts INT NOT NULL,AvailableDateUtc DATETIME2 NOT NULL,LeaseOwner NVARCHAR(200) NULL,LeaseExpiresDateUtc DATETIME2 NULL,CorrelationId NVARCHAR(120) NOT NULL,IdempotencyKey NVARCHAR(240) NOT NULL,LastErrorMessage NVARCHAR(4000) NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_RecommendationWork_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.RecommendationWorkItem') AND name=N'UX_AI_RecommendationWork_Idempotency') CREATE UNIQUE INDEX UX_AI_RecommendationWork_Idempotency ON AI.RecommendationWorkItem(TenantId,IdempotencyKey) WHERE IsDeleted=0;
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.RecommendationWorkItem') AND name=N'IX_AI_RecommendationWork_Lease') CREATE INDEX IX_AI_RecommendationWork_Lease ON AI.RecommendationWorkItem(StatusCode,AvailableDateUtc,LeaseExpiresDateUtc) INCLUDE(TenantId,EntityTypeCode,EntityId,AttemptCount,MaximumAttempts) WHERE IsDeleted=0;
IF OBJECT_ID(N'AI.RecommendationEvidence',N'U') IS NULL CREATE TABLE AI.RecommendationEvidence(RecommendationEvidenceId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_RecommendationEvidence PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,RecommendationId UNIQUEIDENTIFIER NOT NULL,EvidenceTypeCode NVARCHAR(50) NOT NULL,SourceEntityTypeCode NVARCHAR(100) NULL,SourceEntityId UNIQUEIDENTIFIER NULL,SourceReference NVARCHAR(2000) NULL,Description NVARCHAR(1000) NOT NULL,RelevanceScore DECIMAL(5,4) NULL,CreatedDateUtc DATETIME2 NOT NULL CONSTRAINT DF_AI_RecommendationEvidence_Created DEFAULT SYSUTCDATETIME(),CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_RecommendationEvidence_Deleted DEFAULT 0,CONSTRAINT FK_AI_RecommendationEvidence_Recommendation FOREIGN KEY(RecommendationId) REFERENCES AI.Recommendation(RecommendationId));

IF OBJECT_ID(N'AI.SearchDocument',N'U') IS NULL CREATE TABLE AI.SearchDocument(SearchDocumentId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_SearchDocument PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,EntityTypeCode NVARCHAR(100) NOT NULL,EntityId UNIQUEIDENTIFIER NOT NULL,ModuleCode NVARCHAR(100) NOT NULL,Title NVARCHAR(500) NOT NULL,ContentText NVARCHAR(MAX) NOT NULL,Keywords NVARCHAR(2000) NULL,ConceptIdsJson NVARCHAR(MAX) NULL,SecurityScopeJson NVARCHAR(MAX) NOT NULL,ContentHash CHAR(64) NOT NULL,EmbeddingProviderCode NVARCHAR(100) NULL,EmbeddingModelCode NVARCHAR(100) NULL,EmbeddingReference NVARCHAR(2000) NULL,IndexedDateUtc DATETIME2 NOT NULL,SourceModifiedDateUtc DATETIME2 NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_SearchDocument_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.SearchDocument') AND name=N'UX_AI_SearchDocument_Entity') CREATE UNIQUE INDEX UX_AI_SearchDocument_Entity ON AI.SearchDocument(TenantId,EntityTypeCode,EntityId) WHERE IsDeleted=0;
IF OBJECT_ID(N'AI.SearchPermission',N'U') IS NULL CREATE TABLE AI.SearchPermission(SearchPermissionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_SearchPermission PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,SearchDocumentId UNIQUEIDENTIFIER NOT NULL,PrincipalTypeCode NVARCHAR(30) NOT NULL,PrincipalId UNIQUEIDENTIFIER NOT NULL,PermissionCode NVARCHAR(50) NOT NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_SearchPermission_Deleted DEFAULT 0,CONSTRAINT FK_AI_SearchPermission_Document FOREIGN KEY(SearchDocumentId) REFERENCES AI.SearchDocument(SearchDocumentId));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.SearchPermission') AND name=N'IX_AI_SearchPermission_Principal') CREATE INDEX IX_AI_SearchPermission_Principal ON AI.SearchPermission(TenantId,PrincipalTypeCode,PrincipalId,PermissionCode) INCLUDE(SearchDocumentId) WHERE IsDeleted=0;
IF OBJECT_ID(N'AI.SearchQuery',N'U') IS NULL CREATE TABLE AI.SearchQuery(SearchQueryId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_SearchQuery PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,UserId UNIQUEIDENTIFIER NOT NULL,QueryText NVARCHAR(1000) NOT NULL,NormalizedQuery NVARCHAR(1000) NOT NULL,SearchModeCode NVARCHAR(30) NOT NULL,ExpandedConceptIdsJson NVARCHAR(MAX) NULL,FilterJson NVARCHAR(MAX) NULL,ResultCount INT NOT NULL,DurationMilliseconds BIGINT NOT NULL,CorrelationId NVARCHAR(120) NOT NULL,CreatedDateUtc DATETIME2 NOT NULL CONSTRAINT DF_AI_SearchQuery_Created DEFAULT SYSUTCDATETIME(),CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_SearchQuery_Deleted DEFAULT 0);

IF OBJECT_ID(N'AI.ReviewQueueItem',N'U') IS NULL CREATE TABLE AI.ReviewQueueItem(ReviewQueueItemId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_ReviewQueue PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,ReviewTypeCode NVARCHAR(50) NOT NULL,SourceEntityTypeCode NVARCHAR(100) NOT NULL,SourceEntityId UNIQUEIDENTIFIER NOT NULL,ExecutionId UNIQUEIDENTIFIER NULL,Title NVARCHAR(300) NOT NULL,Summary NVARCHAR(2000) NULL,PriorityCode NVARCHAR(30) NOT NULL,StatusCode NVARCHAR(30) NOT NULL,Confidence DECIMAL(5,4) NULL,AssignedToUserId UNIQUEIDENTIFIER NULL,DueDateUtc DATETIME2 NULL,DecisionCode NVARCHAR(30) NULL,DecisionReason NVARCHAR(2000) NULL,ReviewedByUserId UNIQUEIDENTIFIER NULL,ReviewedDateUtc DATETIME2 NULL,IdempotencyKey NVARCHAR(240) NOT NULL,CreatedDateUtc DATETIME2 NOT NULL CONSTRAINT DF_AI_Review_Created DEFAULT SYSUTCDATETIME(),CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_Review_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_AI_Review_Execution FOREIGN KEY(ExecutionId) REFERENCES AI.Execution(ExecutionId));
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.ReviewQueueItem') AND name=N'UX_AI_Review_Idempotency') CREATE UNIQUE INDEX UX_AI_Review_Idempotency ON AI.ReviewQueueItem(TenantId,IdempotencyKey) WHERE IsDeleted=0;
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.ReviewQueueItem') AND name=N'IX_AI_Review_Worklist') CREATE INDEX IX_AI_Review_Worklist ON AI.ReviewQueueItem(TenantId,StatusCode,PriorityCode,DueDateUtc) INCLUDE(ReviewTypeCode,Title,AssignedToUserId,Confidence);

IF OBJECT_ID(N'AI.EvaluationDefinition',N'U') IS NULL CREATE TABLE AI.EvaluationDefinition(EvaluationDefinitionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_EvaluationDefinition PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NULL,EvaluationCode NVARCHAR(100) NOT NULL,DisplayName NVARCHAR(200) NOT NULL,FeatureCode NVARCHAR(100) NOT NULL,MetricCode NVARCHAR(100) NOT NULL,CalculationCode NVARCHAR(100) NOT NULL,TargetValue DECIMAL(18,6) NOT NULL,WarningValue DECIMAL(18,6) NOT NULL,WindowHours INT NOT NULL,MinimumSampleSize INT NOT NULL,ConfigurationJson NVARCHAR(MAX) NULL,IsActive BIT NOT NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_EvaluationDefinition_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL);
IF OBJECT_ID(N'AI.EvaluationRun',N'U') IS NULL CREATE TABLE AI.EvaluationRun(EvaluationRunId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_EvaluationRun PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NULL,EvaluationDefinitionId UNIQUEIDENTIFIER NOT NULL,WindowStartUtc DATETIME2 NOT NULL,WindowEndUtc DATETIME2 NOT NULL,StatusCode NVARCHAR(30) NOT NULL,SampleCount INT NOT NULL,MetricValue DECIMAL(18,6) NULL,Passed BIT NULL,DetailsJson NVARCHAR(MAX) NULL,ErrorMessage NVARCHAR(4000) NULL,StartedDateUtc DATETIME2 NOT NULL,CompletedDateUtc DATETIME2 NULL,LeaseOwner NVARCHAR(200) NULL,LeaseExpiresDateUtc DATETIME2 NULL,CreatedDateUtc DATETIME2 NOT NULL CONSTRAINT DF_AI_EvaluationRun_Created DEFAULT SYSUTCDATETIME(),CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_EvaluationRun_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_AI_EvaluationRun_Definition FOREIGN KEY(EvaluationDefinitionId) REFERENCES AI.EvaluationDefinition(EvaluationDefinitionId));
IF COL_LENGTH(N'AI.EvaluationRun',N'LeaseOwner') IS NULL ALTER TABLE AI.EvaluationRun ADD LeaseOwner NVARCHAR(200) NULL;
IF COL_LENGTH(N'AI.EvaluationRun',N'LeaseExpiresDateUtc') IS NULL ALTER TABLE AI.EvaluationRun ADD LeaseExpiresDateUtc DATETIME2 NULL;
IF OBJECT_ID(N'AI.ModuleMetricSnapshot',N'U') IS NULL CREATE TABLE AI.ModuleMetricSnapshot(ModuleMetricSnapshotId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_AI_ModuleMetricSnapshot PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,ModuleCode NVARCHAR(100) NOT NULL,MetricCode NVARCHAR(100) NOT NULL,MetricValue DECIMAL(18,6) NOT NULL,WindowStartUtc DATETIME2 NOT NULL,WindowEndUtc DATETIME2 NOT NULL,DimensionsJson NVARCHAR(MAX) NULL,CreatedDateUtc DATETIME2 NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NULL,ModifiedDateUtc DATETIME2 NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_AI_ModuleMetric_Deleted DEFAULT 0);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'AI.ModuleMetricSnapshot') AND name=N'IX_AI_ModuleMetric_Latest') CREATE INDEX IX_AI_ModuleMetric_Latest ON AI.ModuleMetricSnapshot(TenantId,ModuleCode,MetricCode,WindowEndUtc DESC) INCLUDE(MetricValue) WHERE IsDeleted=0;

MERGE AI.EvaluationDefinition target USING(VALUES
(CONVERT(uniqueidentifier,'842d595c-1e59-4fb7-b9fa-041c0191a635'),N'EXECUTION_SUCCESS_RATE',N'Execution success rate',N'ALL',N'SUCCESS_RATE',N'SUCCESS_RATE',CONVERT(decimal(18,6),0.98),CONVERT(decimal(18,6),0.95),24,20,N'{"direction":"HIGHER_IS_BETTER"}'),
(CONVERT(uniqueidentifier,'a838123e-7723-41d5-95a2-abfba947b62d'),N'AVERAGE_CONFIDENCE',N'Average confidence',N'ALL',N'AVERAGE_CONFIDENCE',N'AVERAGE_CONFIDENCE',CONVERT(decimal(18,6),0.85),CONVERT(decimal(18,6),0.75),24,20,N'{"direction":"HIGHER_IS_BETTER"}'),
(CONVERT(uniqueidentifier,'10ce583f-fc67-4574-bc0d-c4222986fd44'),N'AVERAGE_DURATION',N'Average processing duration',N'ALL',N'AVERAGE_DURATION_MS',N'AVERAGE_DURATION_MS',CONVERT(decimal(18,6),5000),CONVERT(decimal(18,6),10000),24,20,N'{"direction":"LOWER_IS_BETTER"}'),
(CONVERT(uniqueidentifier,'018e847e-349d-497c-b7c0-9cab0cb31555'),N'CORRECTION_RATE',N'User correction rate',N'ALL',N'CORRECTION_RATE',N'CORRECTION_RATE',CONVERT(decimal(18,6),0.05),CONVERT(decimal(18,6),0.10),168,20,N'{"direction":"LOWER_IS_BETTER"}')) source(Id,Code,Name,FeatureCode,MetricCode,CalculationCode,TargetValue,WarningValue,WindowHours,MinimumSampleSize,ConfigurationJson) ON target.TenantId IS NULL AND target.EvaluationCode=source.Code WHEN MATCHED THEN UPDATE SET DisplayName=source.Name,FeatureCode=source.FeatureCode,MetricCode=source.MetricCode,CalculationCode=source.CalculationCode,TargetValue=source.TargetValue,WarningValue=source.WarningValue,WindowHours=source.WindowHours,MinimumSampleSize=source.MinimumSampleSize,ConfigurationJson=source.ConfigurationJson,IsActive=1,IsDeleted=0,ModifiedDateUtc=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(EvaluationDefinitionId,TenantId,EvaluationCode,DisplayName,FeatureCode,MetricCode,CalculationCode,TargetValue,WarningValue,WindowHours,MinimumSampleSize,ConfigurationJson,IsActive,CreatedDateUtc,IsDeleted) VALUES(source.Id,NULL,source.Code,source.Name,source.FeatureCode,source.MetricCode,source.CalculationCode,source.TargetValue,source.WarningValue,source.WindowHours,source.MinimumSampleSize,source.ConfigurationJson,1,SYSUTCDATETIME(),0);

MERGE AI.Provider target USING(VALUES(CONVERT(uniqueidentifier,'600a7a1c-9a80-4f59-b52f-3bcfd47187c1'),N'AZURE_OPENAI',N'Azure OpenAI',N'AZURE_OPENAI',N'AI:AzureOpenAI:Endpoint',N'AI:AzureOpenAI:Credential',1,1,1,1,10)) source(Id,Code,Name,TypeCode,EndpointKey,CredentialKey,Chat,Embeddings,Vision,Structured,Priority) ON target.TenantId IS NULL AND target.ProviderCode=source.Code WHEN MATCHED THEN UPDATE SET DisplayName=source.Name,ProviderTypeCode=source.TypeCode,EndpointConfigurationKey=source.EndpointKey,CredentialConfigurationKey=source.CredentialKey,SupportsChat=source.Chat,SupportsEmbeddings=source.Embeddings,SupportsVision=source.Vision,SupportsStructuredOutput=source.Structured,Priority=source.Priority,IsDeleted=0 WHEN NOT MATCHED THEN INSERT(ProviderId,TenantId,ProviderCode,DisplayName,ProviderTypeCode,EndpointConfigurationKey,CredentialConfigurationKey,SupportsChat,SupportsEmbeddings,SupportsVision,SupportsStructuredOutput,Priority,IsActive,CreatedDateUtc,IsDeleted) VALUES(source.Id,NULL,source.Code,source.Name,source.TypeCode,source.EndpointKey,source.CredentialKey,source.Chat,source.Embeddings,source.Vision,source.Structured,source.Priority,1,SYSUTCDATETIME(),0);

MERGE AI.RecommendationType target USING(VALUES
(CONVERT(uniqueidentifier,'37d5fb3c-3e5b-4396-82c6-106f876bdd4b'),N'MISSING_COVERAGE',N'Missing coverage',N'Coverage identified as potentially absent from the current risk program.',N'Submissions',N'HIGH',1,10),
(CONVERT(uniqueidentifier,'73fbfe61-dcf9-4bfb-81cb-85fd764f8980'),N'MISSING_ENDORSEMENT',N'Missing endorsement',N'Endorsement identified as potentially relevant to the insured risk.',N'Submissions',N'HIGH',1,20),
(CONVERT(uniqueidentifier,'584945bf-74a5-438f-851d-d1cb2aeef967'),N'MISSING_DOCUMENT',N'Missing document',N'Document required by configuration, readiness, or underwriting evidence.',N'Documents',N'HIGH',1,30),
(CONVERT(uniqueidentifier,'1917fe9f-b1be-43b8-8f43-f00d3e65e08b'),N'NEXT_WORKFLOW',N'Next workflow',N'Eligible next workflow action derived from persisted state.',N'Workflow',N'NORMAL',1,40),
(CONVERT(uniqueidentifier,'7876027c-0268-4460-81bc-f2d014802aeb'),N'PRODUCER_ACTION',N'Producer action',N'Action recommended for the responsible producer.',N'Workbench',N'NORMAL',1,50),
(CONVERT(uniqueidentifier,'bebdf75e-b18c-42ad-aeaf-1527ab7d27f6'),N'SIMILAR_SUBMISSION',N'Similar submission',N'Permission-aware historically similar submission.',N'Submissions',N'NORMAL',0,60),
(CONVERT(uniqueidentifier,'ddac4874-9adb-466e-9dda-0c34c4ef66bd'),N'SIMILAR_CLAIM',N'Similar claim',N'Permission-aware historically similar claim.',N'Claims',N'NORMAL',0,70),
(CONVERT(uniqueidentifier,'b4db9e89-cba0-4949-8541-6dfe882cf7b9'),N'SIMILAR_ACCOUNT',N'Similar account',N'Permission-aware historically similar account.',N'Accounts',N'NORMAL',0,80)) source(Id,Code,Name,Description,ModuleCode,PriorityCode,RequiresReview,SortOrder) ON target.TenantId IS NULL AND target.TypeCode=source.Code WHEN MATCHED THEN UPDATE SET DisplayName=source.Name,Description=source.Description,TargetModuleCode=source.ModuleCode,DefaultPriorityCode=source.PriorityCode,RequiresHumanReview=source.RequiresReview,SortOrder=source.SortOrder,IsActive=1,IsDeleted=0 WHEN NOT MATCHED THEN INSERT(RecommendationTypeId,TenantId,TypeCode,DisplayName,Description,TargetModuleCode,DefaultPriorityCode,DefaultExpirationHours,RequiresHumanReview,SortOrder,IsActive,CreatedDateUtc,IsDeleted) VALUES(source.Id,NULL,source.Code,source.Name,source.Description,source.ModuleCode,source.PriorityCode,168,source.RequiresReview,source.SortOrder,1,SYSUTCDATETIME(),0);

DECLARE @Config TABLE(SettingKey NVARCHAR(200),Value NVARCHAR(MAX),DataType NVARCHAR(30),Name NVARCHAR(200),Description NVARCHAR(1000));
INSERT @Config VALUES
(N'AI:AzureOpenAI:Endpoint',N'',N'String',N'Azure OpenAI endpoint',N'Tenant-overridable Azure OpenAI resource endpoint; no endpoint is assumed.'),
(N'AI:AzureOpenAI:Credential',N'',N'String',N'Azure OpenAI credential reference',N'Optional environment reference in env://VARIABLE_NAME format; when empty, managed identity is used.'),
(N'Intelligence.Provider.HealthTimeoutSeconds',N'10',N'Integer',N'Provider health timeout',N'Time allowed for provider health probes.'),
(N'Intelligence.AzureOpenAi.ApiVersion',N'2024-10-21',N'String',N'Azure OpenAI API version',N'Azure OpenAI data-plane API version used by the provider adapter.'),
(N'Intelligence.Execution.RetentionDays',N'2555',N'Integer',N'Execution retention days',N'Governed retention for AI execution audit evidence.'),
(N'Intelligence.Search.MaximumResults',N'100',N'Integer',N'Search maximum results',N'Maximum permission-filtered hybrid search results.'),
(N'Intelligence.Search.KeywordWeight',N'0.45',N'Decimal',N'Keyword search weight',N'Keyword contribution to hybrid ranking.'),
(N'Intelligence.Search.SemanticWeight',N'0.55',N'Decimal',N'Semantic search weight',N'Semantic contribution to hybrid ranking.'),
(N'Intelligence.Search.IndexIntervalMinutes',N'10',N'Integer',N'Search index interval',N'Interval for synchronizing authoritative AMS records into permission-aware search.'),
(N'Intelligence.Recommendation.DefaultExpirationHours',N'168',N'Integer',N'Recommendation expiration',N'Default recommendation validity period.'),
(N'Intelligence.Recommendation.WorkerBatchSize',N'20',N'Integer',N'Recommendation worker batch size',N'Maximum recommendation work items leased per cycle.'),
(N'Intelligence.Recommendation.WorkerIntervalSeconds',N'10',N'Integer',N'Recommendation worker interval',N'Recommendation queue polling interval.'),
(N'Intelligence.Recommendation.LeaseSeconds',N'300',N'Integer',N'Recommendation lease duration',N'Exclusive recommendation work lease duration.'),
(N'Intelligence.Evaluation.WorkerIntervalMinutes',N'15',N'Integer',N'Evaluation worker interval',N'Continuous evaluation calculation interval.');
MERGE Core.ConfigurationSetting target USING @Config source ON target.TenantId IS NULL AND target.ScopeCode=N'Platform' AND target.SettingKey=source.SettingKey WHEN MATCHED THEN UPDATE SET ModuleCode=N'Intelligence',DefaultValue=source.Value,DataTypeCode=source.DataType,Description=source.Name+N'. '+source.Description,IsDeleted=0,ModifiedDateUtc=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(SettingId,TenantId,ScopeCode,ModuleCode,SettingKey,SettingValue,DefaultValue,DataTypeCode,Description,IsEncrypted,IsReadOnly,IsDeleted,CreatedDateUtc) VALUES(NEWID(),NULL,N'Platform',N'Intelligence',source.SettingKey,source.Value,source.Value,source.DataType,source.Name+N'. '+source.Description,0,0,0,SYSUTCDATETIME());

IF OBJECT_ID(N'Master.PermissionAction',N'U') IS NOT NULL AND OBJECT_ID(N'IAM.Permission',N'U') IS NOT NULL
BEGIN
	DECLARE @Permissions TABLE(PermissionCode NVARCHAR(150),PermissionName NVARCHAR(200),ResourceCode NVARCHAR(100),ActionCode NVARCHAR(50),Description NVARCHAR(500));
	INSERT @Permissions VALUES
	(N'Intelligence.Read',N'View intelligence operations',N'AI.Intelligence',N'READ',N'View intelligence dashboards, executions, evaluations, and recommendations.'),
	(N'Intelligence.Search',N'Use intelligent search',N'AI.Search',N'READ',N'Use permission-aware keyword and semantic search.'),
	(N'Intelligence.Recommend',N'Generate recommendations',N'AI.Recommendation',N'WRITE',N'Queue and act on governed recommendations.'),
	(N'Intelligence.Review',N'Review AI output',N'AI.Review',N'APPROVE',N'Review AI output, corrections, and recommendations.'),
	(N'Intelligence.Configure',N'Configure intelligence platform',N'AI.Configuration',N'MANAGE',N'Configure providers, model routes, feature policies, and limits.'),
	(N'Intelligence.Evaluate',N'Run AI evaluations',N'AI.Evaluation',N'MANAGE',N'Queue and inspect governed intelligence evaluations.'),
	(N'Intelligence.Audit.Read',N'View AI audit evidence',N'AI.Execution',N'READ',N'View execution, grounding, feedback, cost, and failure evidence.');
	UPDATE existing SET PermissionName=source.PermissionName,ResourceCode=source.ResourceCode,ActionCode=source.ActionCode,ModuleCode=N'AI',Description=source.Description,PermissionActionId=COALESCE(actionRow.PermissionActionId,existing.PermissionActionId),IsBuiltIn=1,IsActive=1,IsDeleted=0,ModifiedDateUtc=SYSUTCDATETIME() FROM IAM.Permission existing JOIN @Permissions source ON source.PermissionCode=existing.PermissionCode OUTER APPLY(SELECT TOP 1 PermissionActionId FROM Master.PermissionAction WHERE UPPER(ActionCode)=source.ActionCode OR UPPER(ActionName)=source.ActionCode ORDER BY PermissionActionId) actionRow;
	INSERT IAM.Permission(PermissionId,TenantId,PermissionCode,PermissionActionId,PermissionName,ResourceCode,ActionCode,ModuleCode,Description,IsBuiltIn,IsActive,CreatedDateUtc,IsDeleted)
	SELECT NEWID(),seedTenant.TenantId,source.PermissionCode,COALESCE(actionRow.PermissionActionId,readAction.PermissionActionId,1),source.PermissionName,source.ResourceCode,source.ActionCode,N'AI',source.Description,1,1,SYSUTCDATETIME(),0 FROM @Permissions source CROSS APPLY(SELECT TOP 1 TenantId FROM Core.Tenant ORDER BY TenantId) seedTenant OUTER APPLY(SELECT TOP 1 PermissionActionId FROM Master.PermissionAction WHERE UPPER(ActionCode)=source.ActionCode OR UPPER(ActionName)=source.ActionCode ORDER BY PermissionActionId) actionRow OUTER APPLY(SELECT TOP 1 PermissionActionId FROM Master.PermissionAction WHERE UPPER(ActionCode)=N'READ' OR UPPER(ActionName)=N'READ' ORDER BY PermissionActionId) readAction WHERE NOT EXISTS(SELECT 1 FROM IAM.Permission existing WHERE existing.PermissionCode=source.PermissionCode);
	INSERT IAM.RolePermission(RolePermissionId,TenantId,RoleId,PermissionId,PermissionCode,GrantedDateUtc,CreatedDateUtc,IsDeleted)
	SELECT NEWID(),role.TenantId,role.RoleId,permission.PermissionId,permission.PermissionCode,SYSUTCDATETIME(),SYSUTCDATETIME(),0 FROM IAM.Role role CROSS JOIN IAM.Permission permission WHERE permission.PermissionCode IN(SELECT PermissionCode FROM @Permissions) AND permission.IsDeleted=0 AND role.RoleCode IN(N'SYSTEM_ADMIN',N'TENANT_ADMIN',N'ADMINISTRATOR') AND role.IsDeleted=0 AND NOT EXISTS(SELECT 1 FROM IAM.RolePermission existing WHERE existing.TenantId=role.TenantId AND existing.RoleId=role.RoleId AND (existing.PermissionId=permission.PermissionId OR existing.PermissionCode=permission.PermissionCode) AND existing.IsDeleted=0);
END;
COMMIT TRANSACTION;
