<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
	<ProjectReference Include="..\Ams.Knowledge.Application\Ams.Knowledge.Application.csproj" />
	<ProjectReference Include="..\Ams.Knowledge.Contracts\Ams.Knowledge.Contracts.csproj" />
	<ProjectReference Include="..\Ams.Knowledge.Domain\Ams.Knowledge.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Dapper" Version="2.1.72" />
	<PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
	<EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>
</Project>
