<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>AmsWeb.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Components\Pages\Platform\Tenants\Tabs\**" />
    <Content Remove="Components\Pages\Platform\Tenants\Tabs\**" />
    <EmbeddedResource Remove="Components\Pages\Platform\Tenants\Tabs\**" />
    <None Remove="Components\Pages\Platform\Tenants\Tabs\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="Components\Pages\Branches.razor" />
    <Content Remove="Components\Pages\CreateLead.razor" />
    <Content Remove="Components\Pages\Iam\Permissions\RolePermissionMatrix.razor" />
    <Content Remove="Components\Pages\ProducerWorkbench.razor" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Components\Pages\Branches.razor.css" />
    <None Remove="Components\Pages\Iam\Permissions\RolePermissionMatrix.razor.css" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ams.Application\Ams.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Blazor" Version="28.1.33" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Components\Pages\Platform\Provisioning\" />
  </ItemGroup>
</Project>
