<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>AmsWeb.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Components\Pages\Platform\Tenants\Tabs\**" />
    <Content Remove="Components\Pages\Platform\Tenants\Tabs\**" />
    <EmbeddedResource Remove="Components\Pages\Platform\Tenants\Tabs\**" />
    <None Remove="Components\Pages\Platform\Tenants\Tabs\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="Components\Pages\Iam\Permissions\RolePermissionMatrix.razor" />
    <Content Remove="Components\Pages\Iam\Roles\Roles.razor" />
    <Content Remove="Components\Pages\Iam\Users\Users.razor" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Components\Pages\Iam\Permissions\RolePermissionMatrix.razor.css" />
    <None Remove="Components\Pages\Iam\Roles\Roles.razor.css" />
    <None Remove="Components\Pages\Iam\Users\Users.razor.css" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="bin\Debug\net9.0\Ams.Web.deps.json" />
    <Content Include="bin\Debug\net9.0\Ams.Web.runtimeconfig.json" />
    <Content Include="bin\Debug\net9.0\Ams.Web.staticwebassets.endpoints.json" />
    <Content Include="bin\Debug\net9.0\Ams.Web.staticwebassets.runtime.json" />
    <Content Include="bin\Debug\net9.0\appsettings.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ams.Application\Ams.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Blazor" Version="28.1.33" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="bin\Release\net9.0\" />
    <Folder Include="Components\Pages\Platform\Provisioning\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="bin\Debug\net9.0\Ams.Application.dll" />
    <None Include="bin\Debug\net9.0\Ams.Application.pdb" />
    <None Include="bin\Debug\net9.0\Ams.Domain.dll" />
    <None Include="bin\Debug\net9.0\Ams.Domain.pdb" />
    <None Include="bin\Debug\net9.0\Ams.Web.dll" />
    <None Include="bin\Debug\net9.0\Ams.Web.exe" />
    <None Include="bin\Debug\net9.0\Ams.Web.pdb" />
    <None Include="bin\Debug\net9.0\Newtonsoft.Json.dll" />
    <None Include="bin\Debug\net9.0\Syncfusion.Blazor.dll" />
    <None Include="bin\Debug\net9.0\Syncfusion.ExcelExport.Net.dll" />
    <None Include="bin\Debug\net9.0\Syncfusion.Licensing.dll" />
    <None Include="bin\Debug\net9.0\Syncfusion.PdfExport.Net.dll" />
  </ItemGroup>
</Project>
