namespace Ams.Application.Common.Dtos;

public sealed record PremiumFinanceReferenceOptionDto(
    Guid PremiumFinanceReferenceOptionId,
    Guid TenantId,
    string OptionGroupCode,
    string OptionCode,
    string DisplayName,
    string? Description,
    string? ColorHex,
    bool IsTerminal,
    bool IsDefault,
    int SortOrder);

public sealed record PremiumFinanceProviderDto(
    Guid FinanceCompanyId,
    Guid TenantId,
    string CompanyCode,
    string CompanyName,
    string? ContactName,
    string? EmailAddress,
    string? PhoneNumber,
    string? RemittanceInstructions,
    string? ProviderKey,
    string IntegrationLevelCode,
    string? WebsiteUrl,
    string? PortalUrl,
    bool SupportsQuotes,
    bool SupportsApplications,
    bool SupportsAgreements,
    bool SupportsPaymentSchedules,
    bool SupportsAccountStatus,
    bool SupportsPayoff,
    string? ExternalProviderId,
    bool IsActive);

public sealed record PremiumFinanceRequestDto(
    Guid PremiumFinanceRequestId,
    Guid TenantId,
    string RequestNumber,
    string SourceTypeCode,
    Guid? QuoteId,
    Guid? PolicyId,
    Guid? RenewalId,
    Guid? SubmissionId,
    Guid AccountId,
    Guid? CarrierId,
    Guid? ProducerUserId,
    Guid? AssignedToUserId,
    string InsuredName,
    string? AgencyName,
    string? ProducerName,
    string? CarrierName,
    string PolicyOrQuoteNumber,
    string LineOfBusiness,
    DateOnly EffectiveDate,
    decimal PremiumAmount,
    decimal TaxAmount,
    decimal FeeAmount,
    decimal TotalCostAmount,
    decimal? RequestedDownPaymentAmount,
    int? RequestedInstallmentCount,
    string StatusCode,
    Guid? PreferredFinanceCompanyId,
    Guid? SelectedQuoteOptionId,
    string? CustomerEmail,
    string? CustomerPhone,
    string? Notes,
    DateTime? RequestedDateUtc,
    DateTime? SubmittedDateUtc,
    DateTime? CompletedDateUtc,
    DateTime CreatedDateUtc);

public sealed record PremiumFinanceQuoteOptionDto(
    Guid PremiumFinanceQuoteOptionId,
    Guid TenantId,
    Guid PremiumFinanceRequestId,
    Guid FinanceCompanyId,
    string FinanceCompanyName,
    string? ProviderQuoteReference,
    string OptionName,
    decimal DownPaymentPercent,
    decimal DownPaymentAmount,
    decimal AmountFinanced,
    decimal AprPercent,
    decimal FinanceChargeAmount,
    int PaymentCount,
    decimal PaymentAmount,
    DateOnly? FirstPaymentDate,
    DateOnly? QuoteExpirationDate,
    string StatusCode,
    string? TermsSummary,
    bool IsSelected,
    DateTime? SelectedDateUtc,
    DateTime CreatedDateUtc);

public sealed record PremiumFinanceAgreementDto(
    Guid FinanceAgreementId,
    Guid TenantId,
    Guid? AgencyBillReceivableId,
    Guid FinanceCompanyId,
    string FinanceCompanyName,
    Guid? PremiumFinanceRequestId,
    Guid? PremiumFinanceQuoteOptionId,
    Guid? PolicyId,
    Guid? QuoteId,
    Guid? AccountId,
    string AgreementNumber,
    decimal? OriginalPremiumAmount,
    decimal? TaxAndFeeAmount,
    decimal FinancedAmount,
    decimal DownPaymentAmount,
    decimal? AprPercent,
    decimal? FinanceChargeAmount,
    int? PaymentCount,
    decimal? PaymentAmount,
    DateOnly? NextPaymentDate,
    string FundingStatusCode,
    string? ApplicationStatusCode,
    string? SignatureStatusCode,
    string? AccountStatusCode,
    string? ProviderApplicationReference,
    Guid? DocumentId,
    Guid? ESignEnvelopeId,
    DateOnly? ExpectedFundingDate,
    DateOnly? FundedDate,
    DateOnly? CancellationProtectionDate,
    DateTime? ApprovedDateUtc,
    DateTime? ActivatedDateUtc,
    DateTime? LastSynchronizedDateUtc,
    decimal? PayoffAmount,
    DateOnly? PayoffGoodThroughDate,
    string StatusCode,
    DateTime CreatedDateUtc);

public sealed record PremiumFinancePaymentScheduleDto(
    Guid PremiumFinancePaymentScheduleId,
    Guid TenantId,
    Guid FinanceAgreementId,
    int InstallmentNumber,
    DateOnly DueDate,
    decimal ScheduledAmount,
    decimal? PrincipalAmount,
    decimal? FinanceChargeAmount,
    decimal? PaidAmount,
    DateOnly? PaidDate,
    string StatusCode,
    string? ProviderPaymentReference);

public sealed record PremiumFinanceActivityDto(
    Guid PremiumFinanceActivityId,
    Guid TenantId,
    Guid? PremiumFinanceRequestId,
    Guid? FinanceAgreementId,
    string ActivityTypeCode,
    string Subject,
    string? Notes,
    string? OldStatusCode,
    string? NewStatusCode,
    string? ProviderReference,
    DateTime ActivityDateUtc,
    string? CreatedByName,
    Guid? CreatedByUserId);

public sealed record PremiumFinanceDocumentDto(
    Guid PremiumFinanceDocumentId,
    Guid TenantId,
    Guid? PremiumFinanceRequestId,
    Guid? FinanceAgreementId,
    Guid DocumentId,
    string DocumentRoleCode,
    bool IsCurrent,
    string? FileName,
    string? DocumentTypeCode,
    DateTime CreatedDateUtc);

public sealed record PremiumFinanceProviderTransactionDto(
    Guid PremiumFinanceProviderTransactionId,
    Guid TenantId,
    Guid FinanceCompanyId,
    Guid? PremiumFinanceRequestId,
    Guid? FinanceAgreementId,
    string OperationCode,
    Guid CorrelationId,
    string? ExternalTransactionId,
    string StatusCode,
    int AttemptCount,
    string? ErrorDetails,
    DateTime? CompletedDateUtc,
    DateTime CreatedDateUtc);

public sealed record PremiumFinanceSourceDto(
    string SourceTypeCode,
    Guid SourceId,
    Guid TenantId,
    Guid? QuoteId,
    Guid? PolicyId,
    Guid? RenewalId,
    Guid? SubmissionId,
    Guid AccountId,
    Guid? CarrierId,
    Guid? ProducerUserId,
    string InsuredName,
    string? AgencyName,
    string? ProducerName,
    string? CarrierName,
    string PolicyOrQuoteNumber,
    string LineOfBusiness,
    DateOnly EffectiveDate,
    decimal PremiumAmount,
    decimal TaxAmount,
    decimal FeeAmount,
    string? CustomerEmail,
    string? CustomerPhone,
    bool IsEligible,
    string? IneligibilityReason);

public sealed record PremiumFinanceSummaryDto(
    int TotalRequests,
    int OptionsPending,
    int PendingSignatures,
    int PendingApprovals,
    int ActiveFinancing,
    int AttentionRequired,
    int RenewalsDue,
    decimal TotalAmountFinanced,
    decimal TotalOutstandingScheduled);

public sealed record PremiumFinanceWorkbenchDto(
    IReadOnlyList<PremiumFinanceReferenceOptionDto> ReferenceOptions,
    IReadOnlyList<PremiumFinanceProviderDto> Providers,
    IReadOnlyList<PremiumFinanceRequestDto> Requests,
    IReadOnlyList<PremiumFinanceQuoteOptionDto> QuoteOptions,
    IReadOnlyList<PremiumFinanceAgreementDto> Agreements,
    IReadOnlyList<PremiumFinancePaymentScheduleDto> PaymentSchedule,
    PremiumFinanceSummaryDto Summary);

public sealed record PremiumFinanceDetailDto(
    PremiumFinanceRequestDto Request,
    IReadOnlyList<PremiumFinanceQuoteOptionDto> QuoteOptions,
    PremiumFinanceAgreementDto? Agreement,
    IReadOnlyList<PremiumFinancePaymentScheduleDto> PaymentSchedule,
    IReadOnlyList<PremiumFinanceActivityDto> Activities,
    IReadOnlyList<PremiumFinanceDocumentDto> Documents,
    IReadOnlyList<PremiumFinanceProviderTransactionDto> ProviderTransactions);

public sealed record PremiumFinanceProviderResultDto(
    bool IsSuccessful,
    string StatusCode,
    string? ExternalReference,
    string? Message,
    IReadOnlyList<PremiumFinanceQuoteOptionDto> QuoteOptions,
    PremiumFinanceAgreementDto? Agreement,
    IReadOnlyList<PremiumFinancePaymentScheduleDto> PaymentSchedule);
