using System.ComponentModel.DataAnnotations;

namespace Ams.Application.Features.Intelligence;

public sealed record AiProviderDto(Guid ProviderId,string ProviderCode,string DisplayName,string ProviderTypeCode,bool SupportsChat,bool SupportsEmbeddings,bool SupportsVision,bool SupportsStructuredOutput,int Priority,bool IsActive,byte[] RowVersion);
public sealed record AiModelDeploymentDto(Guid ModelDeploymentId,Guid ProviderId,string ProviderCode,string ModelCode,string DeploymentName,string ModelFamily,string CapabilityCode,int ContextWindowTokens,int MaximumOutputTokens,decimal? InputCostPerMillionTokens,decimal? OutputCostPerMillionTokens,string CurrencyCode,int Priority,bool IsFallback,bool IsActive,byte[] RowVersion);
public sealed record AiFeaturePolicyDto(Guid FeaturePolicyId,Guid TenantId,string FeatureCode,string ModuleCode,Guid? PrimaryModelDeploymentId,Guid? FallbackModelDeploymentId,decimal Temperature,int MaximumInputTokens,int MaximumOutputTokens,int TimeoutSeconds,decimal? DailyCostLimit,decimal? MonthlyCostLimit,decimal MinimumConfidence,bool RequiresHumanReview,bool IsEnabled,byte[] RowVersion);
public sealed record SaveAiFeaturePolicyRequest(Guid TenantId,[Required,StringLength(100)]string FeatureCode,[Required,StringLength(100)]string ModuleCode,Guid? PrimaryModelDeploymentId,Guid? FallbackModelDeploymentId,[Range(0,2)]decimal Temperature,[Range(1,1000000)]int MaximumInputTokens,[Range(1,1000000)]int MaximumOutputTokens,[Range(1,900)]int TimeoutSeconds,[Range(0,double.MaxValue)]decimal? DailyCostLimit,[Range(0,double.MaxValue)]decimal? MonthlyCostLimit,[Range(0,1)]decimal MinimumConfidence,bool RequiresHumanReview,bool IsEnabled,Guid ActorUserId,byte[]? RowVersion);

public sealed record AiExecutionSummaryDto(Guid ExecutionId,Guid TenantId,string FeatureCode,string ModuleCode,string? EntityTypeCode,Guid? EntityId,string StatusCode,string? ProviderCode,string? ModelCode,string? PromptVersion,long? DurationMilliseconds,int? InputTokenCount,int? OutputTokenCount,decimal? EstimatedCost,string? CurrencyCode,decimal? Confidence,int GroundingSourceCount,Guid? RequestedByUserId,DateTime StartedDateUtc,DateTime? CompletedDateUtc,string CorrelationId,string? ErrorCode,string? ErrorMessage,byte[] RowVersion);
public sealed record AiExecutionDetailDto(AiExecutionSummaryDto Execution,IReadOnlyCollection<AiGroundingSourceDto> GroundingSources,IReadOnlyCollection<AiExecutionFeedbackDto> Feedback);
public sealed record AiGroundingSourceDto(Guid GroundingSourceId,string SourceTypeCode,string? SourceEntityTypeCode,Guid? SourceEntityId,string SourceReference,string? Title,decimal? RelevanceScore);
public sealed record AiExecutionFeedbackDto(Guid FeedbackId,string FeedbackTypeCode,short? Rating,string? CorrectionReference,string? Comment,string? DecisionCode,Guid? ReviewedByUserId,DateTime? ReviewedDateUtc,DateTime CreatedDateUtc);
public sealed record SearchAiExecutionsQuery(Guid TenantId,string? SearchTerm,string? FeatureCode,string? StatusCode,DateTime? FromUtc,DateTime? ToUtc,int PageNumber=1,int PageSize=50);
public sealed record SubmitAiExecutionFeedbackRequest(Guid TenantId,Guid ExecutionId,[Required,StringLength(50)]string FeedbackTypeCode,[Range(1,5)]short? Rating,[StringLength(2000)]string? CorrectionReference,[StringLength(2000)]string? Comment,Guid ActorUserId);

public sealed record RecommendationTypeDto(Guid RecommendationTypeId,string TypeCode,string DisplayName,string? Description,string TargetModuleCode,string DefaultPriorityCode,int? DefaultExpirationHours,bool RequiresHumanReview,int SortOrder,bool IsActive);
public sealed record RecommendationDto(Guid RecommendationId,Guid TenantId,string TypeCode,string TypeName,string EntityTypeCode,Guid EntityId,string Title,string Summary,string? Rationale,string? ActionCode,string? ActionPayloadJson,string PriorityCode,string StatusCode,decimal Confidence,decimal Score,Guid? AssignedToUserId,DateTime? ExpiresDateUtc,DateTime CreatedDateUtc,byte[] RowVersion);
public sealed record SearchRecommendationsQuery(Guid TenantId,string? SearchTerm,string? TypeCode,string? StatusCode,string? EntityTypeCode,Guid? EntityId,Guid? AssignedToUserId,int PageNumber=1,int PageSize=50);
public sealed record GenerateRecommendationsRequest(Guid TenantId,[Required,StringLength(100)]string EntityTypeCode,Guid EntityId,[Required,StringLength(120)]string CorrelationId,Guid ActorUserId);
public sealed record DecideRecommendationRequest(Guid TenantId,Guid RecommendationId,[Required,StringLength(30)]string DecisionCode,[Required,StringLength(1000)]string Reason,Guid ActorUserId,byte[] RowVersion);

public sealed record IntelligenceSearchRequest(Guid TenantId,Guid UserId,[Required,StringLength(1000,MinimumLength=2)]string Query,[StringLength(100)]string? ModuleCode,[StringLength(100)]string? EntityTypeCode,[Range(1,100)]int MaximumResults=25,[Required,StringLength(120)]string CorrelationId="");
public sealed record IntelligenceSearchResultDto(Guid SearchDocumentId,string EntityTypeCode,Guid EntityId,string ModuleCode,string Title,string? Excerpt,decimal KeywordScore,decimal SemanticScore,decimal CombinedScore,IReadOnlyCollection<SemanticConceptMatchDto> Concepts);
public sealed record SemanticConceptMatchDto(Guid ConceptId,string ConceptCode,string PreferredLabel,int VersionNumber,decimal Score,string MatchReasonCode);
public sealed record IntelligenceSearchResponse(Guid SearchQueryId,string Query,IReadOnlyCollection<string> ExpandedTerms,IReadOnlyCollection<IntelligenceSearchResultDto> Results,long DurationMilliseconds);

public sealed record AiReviewQueueItemDto(Guid ReviewQueueItemId,string ReviewTypeCode,string SourceEntityTypeCode,Guid SourceEntityId,Guid? ExecutionId,string Title,string? Summary,string PriorityCode,string StatusCode,decimal? Confidence,Guid? AssignedToUserId,DateTime? DueDateUtc,DateTime CreatedDateUtc,byte[] RowVersion);
public sealed record SearchAiReviewQueueQuery(Guid TenantId,string? SearchTerm,string? ReviewTypeCode,string? StatusCode,string? PriorityCode,Guid? AssignedToUserId,int PageNumber=1,int PageSize=50);
public sealed record DecideAiReviewRequest(Guid TenantId,Guid ReviewQueueItemId,[Required,StringLength(30)]string DecisionCode,[Required,StringLength(2000)]string Reason,Guid ActorUserId,byte[] RowVersion);

public sealed record AiEvaluationDefinitionDto(Guid EvaluationDefinitionId,Guid? TenantId,string EvaluationCode,string DisplayName,string FeatureCode,string MetricCode,string CalculationCode,decimal TargetValue,decimal WarningValue,int WindowHours,int MinimumSampleSize,bool IsActive,byte[] RowVersion);
public sealed record AiEvaluationRunDto(Guid EvaluationRunId,Guid? TenantId,string EvaluationCode,string DisplayName,string FeatureCode,string MetricCode,DateTime WindowStartUtc,DateTime WindowEndUtc,string StatusCode,int SampleCount,decimal? MetricValue,bool? Passed,string? DetailsJson,string? ErrorMessage,DateTime StartedDateUtc,DateTime? CompletedDateUtc);
public sealed record QueueAiEvaluationRequest(Guid TenantId,Guid EvaluationDefinitionId,DateTime WindowStartUtc,DateTime WindowEndUtc,Guid ActorUserId);

public sealed record IntelligenceDashboardDto(DateTime GeneratedDateUtc,int ExecutionsToday,int FailedExecutionsToday,decimal EstimatedCostToday,decimal? AverageConfidenceToday,long? AverageDurationMillisecondsToday,int OpenReviewCount,int OpenRecommendationCount,int SearchCountToday,int KnowledgeChangesToday,int ImportJobsInProgress,int WorkerQueueDepth,IReadOnlyCollection<IntelligenceUsageMetricDto> UsageByFeature,IReadOnlyCollection<RecommendationTypeMetricDto> RecommendationsByType);
public sealed record IntelligenceUsageMetricDto(string FeatureCode,int ExecutionCount,int FailedCount,decimal EstimatedCost,decimal? AverageConfidence,long? AverageDurationMilliseconds);
public sealed record RecommendationTypeMetricDto(string TypeCode,string DisplayName,int OpenCount,int AcceptedCount,int DismissedCount);
