SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID(N'knowledge.TerminologySource',N'U') IS NULL CREATE TABLE knowledge.TerminologySource(TerminologySourceId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_KnowledgeTerminologySource PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NULL,SourceCode VARCHAR(100) NOT NULL,DisplayName NVARCHAR(200) NOT NULL,SourceTypeCode VARCHAR(50) NOT NULL,AuthorityName NVARCHAR(300) NOT NULL,LicenseTypeCode VARCHAR(50) NOT NULL,LicenseReference NVARCHAR(1000) NULL,ProvenanceRequirements NVARCHAR(2000) NOT NULL,DefaultLanguageCode VARCHAR(10) NOT NULL,IsSystemDefined BIT NOT NULL,IsActive BIT NOT NULL,CreatedDateUtc DATETIME2(7) NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NOT NULL,ModifiedDateUtc DATETIME2(7) NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_KnowledgeTerminologySource_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL);
CREATE UNIQUE INDEX UX_KnowledgeTerminologySource_System ON knowledge.TerminologySource(SourceCode) WHERE TenantId IS NULL AND IsDeleted=0;
CREATE UNIQUE INDEX UX_KnowledgeTerminologySource_Tenant ON knowledge.TerminologySource(TenantId,SourceCode) WHERE TenantId IS NOT NULL AND IsDeleted=0;

IF OBJECT_ID(N'knowledge.CarrierTerminology',N'U') IS NULL CREATE TABLE knowledge.CarrierTerminology(CarrierTerminologyId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_KnowledgeCarrierTerminology PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NOT NULL,TerminologySourceId UNIQUEIDENTIFIER NOT NULL,CarrierId UNIQUEIDENTIFIER NULL,CarrierCode NVARCHAR(100) NOT NULL,ExternalTermCode NVARCHAR(200) NULL,ExternalTerm NVARCHAR(500) NOT NULL,NormalizedExternalTerm NVARCHAR(500) NOT NULL,KnowledgeConceptId UNIQUEIDENTIFIER NOT NULL,ConceptVersionNumber INT NOT NULL,ContextCode VARCHAR(100) NULL,LineOfBusinessCode VARCHAR(100) NULL,StateCode VARCHAR(10) NULL,EffectiveFromUtc DATETIME2(7) NOT NULL,EffectiveToUtc DATETIME2(7) NULL,StatusCode VARCHAR(30) NOT NULL,ConfidenceScore DECIMAL(5,4) NOT NULL,ApprovedByUserId UNIQUEIDENTIFIER NULL,ApprovedDateUtc DATETIME2(7) NULL,CreatedDateUtc DATETIME2(7) NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NOT NULL,ModifiedDateUtc DATETIME2(7) NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_KnowledgeCarrierTerminology_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_KnowledgeCarrierTerminology_Source FOREIGN KEY(TerminologySourceId) REFERENCES knowledge.TerminologySource(TerminologySourceId),CONSTRAINT FK_KnowledgeCarrierTerminology_Concept FOREIGN KEY(KnowledgeConceptId) REFERENCES knowledge.KnowledgeConcept(KnowledgeConceptId),CONSTRAINT CK_KnowledgeCarrierTerminology_Confidence CHECK(ConfidenceScore BETWEEN 0 AND 1),CONSTRAINT CK_KnowledgeCarrierTerminology_Effective CHECK(EffectiveToUtc IS NULL OR EffectiveToUtc>EffectiveFromUtc));
CREATE UNIQUE INDEX UX_KnowledgeCarrierTerminology_Key ON knowledge.CarrierTerminology(TenantId,CarrierCode,NormalizedExternalTerm,KnowledgeConceptId,ConceptVersionNumber) WHERE IsDeleted=0;
CREATE INDEX IX_KnowledgeCarrierTerminology_Resolve ON knowledge.CarrierTerminology(TenantId,CarrierCode,NormalizedExternalTerm,StatusCode,EffectiveFromUtc) INCLUDE(KnowledgeConceptId,ConceptVersionNumber,ConfidenceScore,ContextCode,LineOfBusinessCode,StateCode) WHERE IsDeleted=0;

IF OBJECT_ID(N'knowledge.ConceptVersionAlias',N'U') IS NULL CREATE TABLE knowledge.ConceptVersionAlias(ConceptVersionAliasId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_KnowledgeConceptVersionAlias PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NULL,KnowledgeConceptId UNIQUEIDENTIFIER NOT NULL,VersionNumber INT NOT NULL,AliasCode VARCHAR(100) NOT NULL,AliasValue NVARCHAR(500) NOT NULL,NormalizedAliasValue NVARCHAR(500) NOT NULL,LanguageCode VARCHAR(10) NOT NULL,IsSearchable BIT NOT NULL,CreatedDateUtc DATETIME2(7) NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NOT NULL,ModifiedDateUtc DATETIME2(7) NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_KnowledgeConceptVersionAlias_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_KnowledgeConceptVersionAlias_Concept FOREIGN KEY(KnowledgeConceptId) REFERENCES knowledge.KnowledgeConcept(KnowledgeConceptId));
CREATE UNIQUE INDEX UX_KnowledgeConceptVersionAlias_Value ON knowledge.ConceptVersionAlias(KnowledgeConceptId,VersionNumber,AliasCode,NormalizedAliasValue) WHERE IsDeleted=0;

IF OBJECT_ID(N'knowledge.SemanticSearchProjection',N'U') IS NULL CREATE TABLE knowledge.SemanticSearchProjection(SemanticSearchProjectionId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_KnowledgeSemanticSearchProjection PRIMARY KEY DEFAULT NEWID(),TenantId UNIQUEIDENTIFIER NULL,KnowledgeConceptId UNIQUEIDENTIFIER NOT NULL,ConceptVersionNumber INT NOT NULL,SchemeCode VARCHAR(100) NOT NULL,ConceptCode VARCHAR(100) NOT NULL,ConceptTypeCode VARCHAR(50) NOT NULL,PreferredLabel NVARCHAR(250) NOT NULL,SearchText NVARCHAR(MAX) NOT NULL,AncestorConceptIdsJson NVARCHAR(MAX) NOT NULL,RelatedConceptIdsJson NVARCHAR(MAX) NOT NULL,ContentHash CHAR(64) NOT NULL,EmbeddingProviderCode VARCHAR(100) NULL,EmbeddingModelCode VARCHAR(100) NULL,EmbeddingReference NVARCHAR(2000) NULL,IndexedDateUtc DATETIME2(7) NOT NULL,CreatedDateUtc DATETIME2(7) NOT NULL,CreatedByUserId UNIQUEIDENTIFIER NOT NULL,ModifiedDateUtc DATETIME2(7) NULL,ModifiedByUserId UNIQUEIDENTIFIER NULL,IsDeleted BIT NOT NULL CONSTRAINT DF_KnowledgeSemanticSearchProjection_Deleted DEFAULT 0,RowVersion ROWVERSION NOT NULL,CONSTRAINT FK_KnowledgeSemanticSearchProjection_Concept FOREIGN KEY(KnowledgeConceptId) REFERENCES knowledge.KnowledgeConcept(KnowledgeConceptId));
CREATE UNIQUE INDEX UX_KnowledgeSemanticSearchProjection_Concept ON knowledge.SemanticSearchProjection(KnowledgeConceptId,ConceptVersionNumber,TenantId) WHERE IsDeleted=0;
CREATE INDEX IX_KnowledgeSemanticSearchProjection_Lookup ON knowledge.SemanticSearchProjection(TenantId,SchemeCode,ConceptTypeCode,PreferredLabel) INCLUDE(KnowledgeConceptId,ConceptCode,ConceptVersionNumber,IndexedDateUtc) WHERE IsDeleted=0;

IF COL_LENGTH(N'knowledge.ImportJob',N'TerminologySourceId') IS NULL ALTER TABLE knowledge.ImportJob ADD TerminologySourceId UNIQUEIDENTIFIER NULL;
IF COL_LENGTH(N'knowledge.ImportJob',N'LicenseAcknowledgedByUserId') IS NULL ALTER TABLE knowledge.ImportJob ADD LicenseAcknowledgedByUserId UNIQUEIDENTIFIER NULL;
IF COL_LENGTH(N'knowledge.ImportJob',N'LicenseAcknowledgedDateUtc') IS NULL ALTER TABLE knowledge.ImportJob ADD LicenseAcknowledgedDateUtc DATETIME2(7) NULL;
IF NOT EXISTS(SELECT 1 FROM sys.foreign_keys WHERE name=N'FK_KnowledgeImportJob_TerminologySource') ALTER TABLE knowledge.ImportJob ADD CONSTRAINT FK_KnowledgeImportJob_TerminologySource FOREIGN KEY(TerminologySourceId) REFERENCES knowledge.TerminologySource(TerminologySourceId);

MERGE knowledge.LookupType target USING(VALUES
('TERMINOLOGY_SOURCE_TYPE',N'Terminology source type',N'Types of governed terminology authorities.'),
('LICENSE_TYPE',N'License type',N'License classifications for imported knowledge.'),
('CARRIER_TERMINOLOGY_STATUS',N'Carrier terminology status',N'Governance states for carrier terminology mappings.'),
('KNOWLEDGE_IMPORT_FORMAT',N'Knowledge import format',N'Supported governed import formats.')) source(Code,Name,Description) ON target.LookupTypeCode=source.Code WHEN MATCHED THEN UPDATE SET DisplayName=source.Name,Description=source.Description,IsActive=1,ModifiedDateUtc=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(LookupTypeCode,DisplayName,Description,IsSystemDefined,IsActive) VALUES(source.Code,source.Name,source.Description,1,1);

MERGE knowledge.LookupValue target USING(VALUES
('TERMINOLOGY_SOURCE_TYPE','AGENCY',N'Agency maintained',10),('TERMINOLOGY_SOURCE_TYPE','CARRIER',N'Carrier',20),('TERMINOLOGY_SOURCE_TYPE','STANDARD',N'Industry standard',30),('TERMINOLOGY_SOURCE_TYPE','INTERNAL_IMPORT',N'Internal import',40),
('LICENSE_TYPE','AMS_AUTHORED',N'AMS authored',10),('LICENSE_TYPE','CUSTOMER_OWNED',N'Customer owned',20),('LICENSE_TYPE','LICENSED',N'Licensed',30),('LICENSE_TYPE','PUBLIC_DOMAIN',N'Public domain',40),
('CARRIER_TERMINOLOGY_STATUS','DRAFT',N'Draft',10),('CARRIER_TERMINOLOGY_STATUS','IN_REVIEW',N'In review',20),('CARRIER_TERMINOLOGY_STATUS','APPROVED',N'Approved',30),('CARRIER_TERMINOLOGY_STATUS','RETIRED',N'Retired',40),
('KNOWLEDGE_IMPORT_FORMAT','JSON',N'JSON',10),('KNOWLEDGE_IMPORT_FORMAT','CSV',N'CSV',20),('KNOWLEDGE_IMPORT_FORMAT','XLSX',N'Excel workbook',30),('KNOWLEDGE_IMPORT_FORMAT','XML',N'XML',40)) source(TypeCode,ValueCode,DisplayName,SortOrder) ON target.TenantId IS NULL AND target.LookupTypeCode=source.TypeCode AND target.ValueCode=source.ValueCode WHEN MATCHED THEN UPDATE SET DisplayName=source.DisplayName,SortOrder=source.SortOrder,IsActive=1,ModifiedDateUtc=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(LookupValueId,LookupTypeCode,ValueCode,DisplayName,SortOrder,TenantId,IsSystemDefined,IsActive,CreatedDateUtc) VALUES(NEWID(),source.TypeCode,source.ValueCode,source.DisplayName,source.SortOrder,NULL,1,1,SYSUTCDATETIME());

MERGE knowledge.Configuration target USING(VALUES
('SEARCH_MAX_RESULTS',N'100','INTEGER',N'Maximum semantic search results.'),
('SEARCH_KEYWORD_WEIGHT',N'0.45','DECIMAL',N'Keyword contribution to hybrid concept ranking.'),
('SEARCH_SEMANTIC_WEIGHT',N'0.55','DECIMAL',N'Semantic contribution to hybrid concept ranking.'),
('TERMINOLOGY_REVIEW_REQUIRED',N'true','BOOLEAN',N'Require approval before carrier terminology becomes active.'),
('IMPORT_MAX_RECORDS',N'100000','INTEGER',N'Maximum records accepted by one governed import.')) source(Code,Value,TypeCode,Description) ON target.TenantId IS NULL AND target.ConfigurationCode=source.Code WHEN MATCHED THEN UPDATE SET ConfigurationValue=source.Value,DataTypeCode=source.TypeCode,Description=source.Description,IsActive=1,ModifiedDateUtc=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(ConfigurationId,TenantId,ConfigurationCode,ConfigurationValue,DataTypeCode,Description,IsSystemDefined,IsActive,CreatedDateUtc) VALUES(NEWID(),NULL,source.Code,source.Value,source.TypeCode,source.Description,1,1,SYSUTCDATETIME());

COMMIT TRANSACTION;
