SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID(N'knowledge.WorkflowGuideStep', N'U') IS NULL
BEGIN
	CREATE TABLE knowledge.WorkflowGuideStep
	(
		WorkflowGuideStepId UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_KnowledgeWorkflowGuideStep PRIMARY KEY,
		TenantId UNIQUEIDENTIFIER NULL,
		WorkflowCode VARCHAR(100) NOT NULL,
		StepCode VARCHAR(100) NOT NULL,
		SequenceNumber INT NOT NULL,
		ModuleCode VARCHAR(100) NOT NULL,
		ModuleSequenceNumber INT NOT NULL,
		ModuleDisplayName NVARCHAR(200) NOT NULL,
		StageName NVARCHAR(200) NOT NULL,
		StepTitle NVARCHAR(250) NOT NULL,
		StepDescription NVARCHAR(2000) NOT NULL,
		PageName NVARCHAR(200) NOT NULL,
		PageRoute NVARCHAR(500) NOT NULL,
		NavigationRoute NVARCHAR(500) NOT NULL,
		ActionLabel NVARCHAR(200) NOT NULL,
		ActionTypeCode VARCHAR(50) NOT NULL,
		FromStatusCode NVARCHAR(100) NULL,
		ToStatusCode NVARCHAR(100) NULL,
		ExpectedResult NVARCHAR(2000) NOT NULL,
		NextUserMove NVARCHAR(2000) NOT NULL,
		ValidationRequirements NVARCHAR(3000) NULL,
		AlternatePath NVARCHAR(3000) NULL,
		SearchKeywords NVARCHAR(2000) NOT NULL,
		IsOptional BIT NOT NULL CONSTRAINT DF_KnowledgeWorkflowGuideStep_Optional DEFAULT 0,
		IsActive BIT NOT NULL CONSTRAINT DF_KnowledgeWorkflowGuideStep_Active DEFAULT 1,
		CreatedDateUtc DATETIME2(7) NOT NULL,
		CreatedByUserId UNIQUEIDENTIFIER NULL,
		ModifiedDateUtc DATETIME2(7) NULL,
		ModifiedByUserId UNIQUEIDENTIFIER NULL,
		IsDeleted BIT NOT NULL CONSTRAINT DF_KnowledgeWorkflowGuideStep_Deleted DEFAULT 0,
		RowVersion ROWVERSION NOT NULL
	);
END;

IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'knowledge.WorkflowGuideStep') AND name = N'UX_KnowledgeWorkflowGuideStep_System')
	CREATE UNIQUE INDEX UX_KnowledgeWorkflowGuideStep_System ON knowledge.WorkflowGuideStep(WorkflowCode, StepCode) WHERE TenantId IS NULL AND IsDeleted = 0;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'knowledge.WorkflowGuideStep') AND name = N'UX_KnowledgeWorkflowGuideStep_Tenant')
	CREATE UNIQUE INDEX UX_KnowledgeWorkflowGuideStep_Tenant ON knowledge.WorkflowGuideStep(TenantId, WorkflowCode, StepCode) WHERE TenantId IS NOT NULL AND IsDeleted = 0;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'knowledge.WorkflowGuideStep') AND name = N'IX_KnowledgeWorkflowGuideStep_Search')
	CREATE INDEX IX_KnowledgeWorkflowGuideStep_Search ON knowledge.WorkflowGuideStep(WorkflowCode, ModuleCode, SequenceNumber, IsActive) INCLUDE(StageName, StepTitle, PageRoute, ActionLabel, FromStatusCode, ToStatusCode) WHERE IsDeleted = 0;

DECLARE @Seed TABLE
(
	StepCode VARCHAR(100), SequenceNumber INT, ModuleCode VARCHAR(100), StageName NVARCHAR(200), StepTitle NVARCHAR(250),
	StepDescription NVARCHAR(2000), PageName NVARCHAR(200), PageRoute NVARCHAR(500), ActionLabel NVARCHAR(200), ActionTypeCode VARCHAR(50),
	FromStatusCode NVARCHAR(100), ToStatusCode NVARCHAR(100), ExpectedResult NVARCHAR(2000), NextUserMove NVARCHAR(2000),
	ValidationRequirements NVARCHAR(3000), AlternatePath NVARCHAR(3000), SearchKeywords NVARCHAR(2000), IsOptional BIT
);

INSERT INTO @Seed VALUES
(N'LEAD_CREATE',10,N'CRM_LEAD',N'Lead Intake',N'Create the lead',N'Create the prospect record with identity, contact, account name, and interested service.',N'Create Lead',N'/crm/leads/new',N'Save Lead',N'SUBMIT',NULL,N'New',N'A tenant-scoped lead record is created and becomes available in the CRM lead register.',N'Open the lead from /crm/leads and complete qualification, ownership, interests, activity, documents, and compliance readiness.',N'Lead number, account/contact identity, and valid tenant context are required by the request and database constraints.',N'Use Cancel to return to /crm/leads without creating a record.',N'new lead create prospect save lead crm intake',0),
(N'LEAD_QUALIFY',20,N'CRM_LEAD',N'Lead Qualification',N'Complete lead readiness',N'Review the lead command center, assign an owner, complete contacts and lines of interest, record activities, upload documents, and clear phone-compliance blockers.',N'Lead Detail',N'/crm/leads/{leadId}',N'Edit; Assign; Add activity; Upload Document',N'WORKFLOW',N'New',N'Qualified',N'The lead has sufficient persisted data and ownership for conversion readiness.',N'Use Convert after the conversion readiness indicators and required lead data are complete.',N'Conversion readiness depends on configured lead status, account/contact data, ownership, interest lines, and compliance controls.',N'Use Disqualify when the prospect is not viable; use follow-up activities when more qualification is needed.',N'qualify lead assign owner contacts interest activity documents compliance readiness',0),
(N'LEAD_DISQUALIFY',25,N'CRM_LEAD',N'Lead Qualification',N'Disqualify an ineligible lead',N'Record the configured disqualification reason and close the lead without creating an opportunity.',N'Lead Detail',N'/crm/leads/{leadId}',N'Disqualify',N'ALTERNATE',N'New or Qualified',N'Disqualified',N'The lead is closed with an auditable disqualification outcome.',N'Review or create another lead when the prospect becomes viable again according to agency policy.',N'A configured disqualification reason is required.',N'Do not convert a disqualified lead unless it is restored through the supported CRM process.',N'lead disqualify decline closed lost reason',1),
(N'LEAD_CONVERT',30,N'CRM_LEAD',N'Lead Conversion',N'Convert lead to account and opportunity',N'Choose Create Account or Link Existing Account, complete opportunity details, and convert the qualified lead.',N'Lead Detail',N'/crm/leads/{leadId}',N'Convert Lead',N'SUBMIT',N'Qualified',N'Converted',N'The lead is converted and linked to an Account and Opportunity; conversion launch actions are persisted.',N'Open the created opportunity and review account, owner, forecast, lines, and submission readiness.',N'The lead must be conversion-ready. Account choice, opportunity name, line/forecast fields, and tenant ownership must be valid.',N'Link Existing Account prevents duplicate account creation when the insured already exists.',N'convert lead account opportunity create link existing account',0),
(N'OPPORTUNITY_CREATE_DIRECT',40,N'CRM_OPPORTUNITY',N'Opportunity Intake',N'Create an opportunity directly',N'Create a revenue opportunity under an existing account when lead conversion is not the source.',N'New Opportunity',N'/crm/opportunities/new',N'Create Opportunity',N'SUBMIT',NULL,N'Open',N'An account-linked opportunity is created with owner, amount, forecast, probability, and close timing.',N'Open Opportunity Detail and add lines or create the first submission.',N'Account, opportunity name, owner/forecast configuration, close date, amount, and valid tenant context must satisfy the request.',N'Normally use lead conversion when the business originated as a CRM lead.',N'new opportunity create account forecast owner probability close date',1),
(N'OPPORTUNITY_PREPARE',50,N'CRM_OPPORTUNITY',N'Opportunity Development',N'Prepare the opportunity',N'Review opportunity details, add coverage lines, update owner and forecast, and move the configured pipeline stage as work progresses.',N'Opportunity Detail',N'/crm/opportunities/{opportunityId}',N'Edit; Add Line; Move Stage',N'WORKFLOW',N'Open',N'Qualified or configured stage',N'The opportunity contains the lines and commercial context needed for underwriting submissions.',N'Click New Submission to create an underwriting package.',N'Stage movement and line values must use tenant-configured CRM options. Mark Won remains blocked until a bound policy exists.',N'Use Mark Lost or the configured lost-stage transition when the sale terminates.',N'opportunity edit add line move stage qualified pipeline forecast',0),
(N'SUBMISSION_CREATE',60,N'SUBMISSION',N'Underwriting Intake',N'Create the submission',N'Create an underwriting submission from the opportunity with term, risk state, line, premium target, owner, and risk description.',N'Opportunity Detail',N'/crm/opportunities/{opportunityId}',N'New Submission',N'SUBMIT',N'Opportunity qualified',N'Draft',N'A tenant-scoped submission is created and linked to the account and opportunity.',N'Open Submission Detail and complete readiness, documents, coverage data, and market selection.',N'Opportunity/account consistency, effective and expiration dates, canonical line of business, configured state/options, and required request values are validated.',N'Create additional submissions for distinct underwriting packages or terms under the same opportunity.',N'create submission underwriting package draft opportunity line effective date',0),
(N'SUBMISSION_READINESS',70,N'SUBMISSION',N'Underwriting Readiness',N'Complete submission readiness',N'Use readiness, coverage, documents, notes, tasks, and assignment controls to resolve all required underwriting data.',N'Submission Detail',N'/submissions/{submissionId}',N'Refresh Readiness; Upload Document; Add Note; Follow-Up Task',N'WORKFLOW',N'Draft or In Progress',N'Ready for Marketing',N'The submission passes configured readiness checks and can be distributed to markets.',N'Load recommended markets or choose Submit to market.',N'Applicant/account, line, dates, risk details, coverages, underwriting questions, required documents, producer, and branch must be complete.',N'If blocked, follow each readiness message and return after correcting the authoritative data.',N'submission readiness underwriting documents coverage questions ready marketing',0),
(N'MARKET_SELECT',80,N'SUBMISSION_MARKET',N'Market Selection',N'Attach target markets',N'Load DB-backed market suggestions and attach the appropriate carrier, MGA, wholesaler, or market records.',N'Submission Detail',N'/submissions/{submissionId}',N'Suggestions; Load Recommended Markets; Submit to market',N'WORKFLOW',N'Ready for Marketing',N'Market selected',N'SubmissionMarket records represent the intended distribution targets.',N'For each market, click Submit to send or record the submission package distribution.',N'Markets and selectable options are database-backed; submission readiness must be complete.',N'Remove a market only through the confirmation dialog before submission; retain unsuccessful historical market records.',N'market suggestions carrier appetite attach submit to market distribution',0),
(N'MARKET_SUBMIT',90,N'SUBMISSION_MARKET',N'Market Distribution',N'Submit package to market',N'Record distribution of the submission package to the selected market.',N'Submission Detail',N'/submissions/{submissionId}',N'Submit',N'SUBMIT',N'Market selected',N'Submitted',N'The SubmissionMarket records submitted date, method, sender, and market workflow state.',N'Click Quote for that market when pricing terms should be requested.',N'Readiness, market, package data, delivery method, and tenant scope must be valid.',N'For API carriers, Request Quote may internally create/submit the market record; manual markets may require package preparation first.',N'submit market carrier distribution package submitted',0),
(N'QUOTE_REQUEST_CREATE',100,N'QUOTE_REQUEST',N'Quote Request',N'Create the quote request',N'Create a QuoteRequest before dispatching to the carrier, rater, MGA, wholesaler, portal, email, or manual workflow.',N'Submission Detail',N'/submissions/{submissionId}',N'Quote; Request Quote',N'SUBMIT',N'Market Submitted',N'Pending Dispatch or Submitted',N'A distinct QuoteRequest is created; an empty Quote is not created.',N'Monitor carrier acknowledgement or use Record Response when the market answers.',N'Quote readiness, selected market, products/lines, coverage option, requested effective date, producer, branch, and required documents are validated.',N'Missing data produces Validation Required. More Information Required creates follow-up work; decline records reason without creating a quote.',N'quote request pending dispatch submitted validation required carrier',0),
(N'QUOTE_RESPONSE_RECORD',110,N'QUOTE_REQUEST',N'Carrier Response',N'Record carrier response',N'Record quoted, declined, referred, failed, or more-information-required carrier outcomes.',N'Submission Detail',N'/submissions/{submissionId}',N'Record Response',N'SUBMIT',N'Submitted or Under Review',N'Quoted, Declined, Referred, More Information Required, or Failed',N'The QuoteRequest captures the response. A Quote is created only when pricing and coverage terms are returned.',N'If quoted, review and normalize quote terms. If more information is required, complete the task and resubmit.',N'Carrier response status, pricing, dates, lines, premium, limits, deductibles, documents, and references must be consistent.',N'Declines and failures remain in history. Requote creates a new QuoteRequest and preserves prior responses.',N'carrier response quote decline referral more information failed quoted',0),
(N'QUOTE_REVIEW',120,N'QUOTE',N'Quote Review',N'Review quote terms',N'Open quote review and verify persisted line terms, coverage, premium, limits, deductibles, subjectivities, exclusions, documents, and bindability.',N'Submission Detail',N'/submissions/{submissionId}',N'Review; Save Quote',N'WORKFLOW',N'Received or Under Review',N'Approved for Presentation',N'The quote is normalized and marked presentation-ready only when every submission line has matching bindable terms.',N'Compare quotes and select the approved customer option.',N'Quote must be active, unexpired, bindable, and complete at both package and line levels.',N'Revision Requested creates a new quote-request cycle; expired, rejected, or not-selected quotes remain historical.',N'quote review approved presentation bindable lines premium subjectivities',0),
(N'QUOTE_SELECT',130,N'QUOTE',N'Quote Selection',N'Select the customer option',N'Persist the selected quote after comparison and proposal readiness review.',N'Submission Detail',N'/submissions/{submissionId}',N'Select',N'SUBMIT',N'Approved for Presentation or Presented',N'Selected',N'The selected quote is identified for proposal and later bind authorization; other active quotes become Not Selected.',N'Open Proposal Workflow and generate a proposal version.',N'Only approved/presented active quotes can be selected. Changing accepted quote terms requires new customer acceptance.',N'Use quote comparison for multiple options; do not request bind before proposal and customer authorization.',N'select quote comparison selected not selected proposal ready',0),
(N'PROPOSAL_GENERATE',140,N'PROPOSAL',N'Proposal Creation',N'Generate proposal',N'Build a governed proposal version from one or more presentation-ready quotes.',N'Proposal Workflow',N'/submissions/{submissionId}/proposals',N'Generate Proposal',N'SUBMIT',N'Quote Selected',N'Draft',N'A versioned proposal artifact is created without replacing quote or policy source data.',N'Review content, add the primary recipient, and click Submit Review.',N'At least one usable presentation-ready quote and complete quote lines are required.',N'Create a new proposal version when customer options or presentation content changes.',N'generate proposal draft selected quote version recipient',0),
(N'PROPOSAL_REVIEW',150,N'PROPOSAL',N'Internal Proposal Review',N'Submit and decide proposal review',N'Send the draft for internal governance review, then approve it or request corrections.',N'Proposal Workflow',N'/submissions/{submissionId}/proposals',N'Submit Review; Approve; Request Changes',N'WORKFLOW',N'Draft or Changes Required',N'Internal Review then Approved or Changes Required',N'Approved proposals become eligible for customer delivery; requested changes return to the creator.',N'After approval, click Deliver Proposal and choose a configured delivery method.',N'Reviewer permissions, bindable quote lines, recipient readiness, and current proposal version are enforced.',N'Changes Required returns to proposal editing and resubmission.',N'proposal internal review approve changes required governance',0),
(N'PROPOSAL_DELIVER',160,N'PROPOSAL',N'Proposal Delivery',N'Deliver proposal',N'Queue the approved proposal through a configured delivery provider and recipient.',N'Proposal Workflow',N'/submissions/{submissionId}/proposals',N'Deliver Proposal',N'SUBMIT',N'Approved',N'Queued, Processing, Delivered, Failed, or Configuration Required',N'A persisted delivery dispatch is processed by the provider/worker and updates delivery status.',N'When delivery is confirmed, click Mark Presented after the customer meeting or presentation.',N'A primary recipient, active delivery provider, approved proposal, permissions, and no duplicate active dispatch are required.',N'Use Retry only for Failed or Configuration Required dispatches after correcting the issue.',N'proposal deliver queued processing delivered failed recipient provider',0),
(N'PROPOSAL_PRESENT',170,N'PROPOSAL',N'Customer Presentation',N'Mark proposal presented',N'Record that the delivered proposal was presented to the customer.',N'Proposal Workflow',N'/submissions/{submissionId}/proposals',N'Mark Presented',N'SUBMIT',N'Delivered',N'Presented',N'Customer decision capture is unlocked for the exact proposal version and quote fingerprint.',N'Click Client Acceptance and record the customer decision and authorization.',N'Delivery must be confirmed and proposal quote data must remain bindable and unchanged.',N'If terms change, regenerate/re-deliver a current proposal before acceptance.',N'proposal presented customer meeting mark presented',0),
(N'CLIENT_ACCEPTANCE',180,N'CLIENT_ACCEPTANCE',N'Customer Decision',N'Record client decision',N'Capture accepted, declined, or withdrawn decision, coverage elections, authorized person, authority basis, method, evidence, and configured consents.',N'Client Acceptance',N'/submissions/{submissionId}/client-acceptance',N'Record Client Decision',N'SUBMIT',N'Presented',N'Accepted, Declined, or Withdrawn',N'An immutable ClientAcceptance and CustomerAuthorization record is created for the exact proposal and quote fingerprint.',N'When Accepted, click Request Bind. For Declined or Withdrawn, return to proposal/remarketing as appropriate.',N'Current delivered proposal, selected quote, unchanged fingerprint, complete line elections, consents, authorization reference/document, and signer details are required.',N'Withdraw Acceptance revokes unused bind eligibility. A changed quote requires new acceptance.',N'client acceptance authorization consent accepted declined withdrawn decision',0),
(N'BIND_REQUEST_CREATE',190,N'BIND_REQUEST',N'Bind Initiation',N'Create bind request',N'Create the auditable bind request from the selected quote and unused customer authorization.',N'Bind Request Command Center',N'/submissions/bind-requests',N'Create Bind Request',N'SUBMIT',N'Accepted',N'Draft',N'One active PolicyBindTransaction is created for the tenant, submission, and quote.',N'Click Validate, resolve blockers, then Mark Ready.',N'Quote must be selected, bindable, unexpired, and match an unused Accepted authorization. Duplicate active requests are rejected.',N'Continue an existing active bind request instead of creating another. Terminal attempts require a new valid acceptance when retried.',N'bind request draft accepted authorization duplicate active',0),
(N'BIND_VALIDATE',200,N'BIND_REQUEST',N'Bind Readiness',N'Validate and mark ready',N'Run configured bind requirements and satisfy documents, licensing, appointments, payment, and approval conditions.',N'Bind Request Command Center',N'/submissions/bind-requests',N'Validate; Approval; Mark Ready',N'WORKFLOW',N'Draft or Pending Approval',N'Ready',N'All blocking validation results are Passed or Waived and required approval/payment conditions are complete.',N'Click Prepare Binder if needed, then Submit the bind request.',N'Tenant-configured requirements, manager approval, payment verification, required documents, producer license, and carrier appointment are enforced.',N'Pending Approval routes to an approver. Rejected approval returns according to configured workflow.',N'bind validate ready approval payment documents license appointment',0),
(N'BIND_SUBMIT',210,N'BIND_REQUEST',N'Carrier Bind Request',N'Submit bind request',N'Send or record the bind request through the selected delivery method.',N'Bind Request Command Center',N'/submissions/bind-requests',N'Prepare Binder; Submit',N'SUBMIT',N'Ready',N'Submitted',N'The bind package/request is submitted; submission does not mean coverage is bound.',N'Wait for authoritative carrier response and record it with Carrier Response.',N'Validation and approval must remain current. Delivery method, package, carrier instructions, and references must be complete.',N'Withdraw according to configured transitions if the request should be stopped.',N'bind submitted prepare binder carrier request not bound',0),
(N'BIND_CARRIER_RESPONSE',220,N'BIND_REQUEST',N'Carrier Response',N'Record carrier response',N'Record acknowledgement, review, information request, approval, rejection, payment requirement, or binder receipt.',N'Bind Request Command Center',N'/submissions/bind-requests',N'Carrier Response',N'SUBMIT',N'Submitted or Received or Under Review',N'Received, Under Review, Need Information, Pending Payment, Approved, Rejected, or Binder Received',N'Carrier evidence, status, references, premium, source, and history are persisted atomically.',N'If Need Information, complete the generated follow-up and resubmit. If Binder Received, verify the binder.',N'Only configured carrier-response transitions are allowed. Confirmation evidence/source and references are required where applicable.',N'Rejected and expired requests remain historical and do not create a policy.',N'carrier response received under review need information approved rejected binder',0),
(N'BINDER_REVIEW',230,N'BIND_REQUEST',N'Binder Review',N'Accept carrier binder',N'Compare authoritative binder dates, premium, taxes, fees, commission, billing, coverage, and documents to the request and quote.',N'Bind Request Command Center',N'/submissions/bind-requests',N'Accept Carrier Binder',N'SUBMIT',N'Binder Received',N'Binder Accepted',N'Producer attestation records accepted binder terms and authorizes policy generation.',N'Click Generate Policy when binder review is accepted.',N'Certified confirmation, binder evidence, policy number/terms, and explicit producer attestation are required.',N'Reject or request correction when binder terms are inaccurate; do not generate policy until corrected and accepted.',N'binder review accept reject correction policy terms attestation',0),
(N'POLICY_GENERATE',240,N'POLICY',N'Policy Creation',N'Generate policy',N'Queue policy generation after accepted carrier binder confirmation.',N'Bind Request Command Center',N'/submissions/bind-requests',N'Generate Policy',N'SUBMIT',N'Binder Accepted',N'Policy Generation Queued then Policy Created',N'The policy service creates the AMS policy, term, coverage, billing, commissions, documents, activities, tasks, renewal schedule, and audit records.',N'Open Policy Workspace and complete issuance/service setup. The related opportunity can then be marked won.',N'Accepted binder review, certified carrier confirmation, idempotency checks, and valid policy-generation state are required.',N'Failed generation can be retried safely; duplicate policy creation is prevented.',N'generate policy queued created binder accepted policy service',0),
(N'POLICY_SERVICE',250,N'POLICY',N'Policy Servicing',N'Open and service policy',N'Review policy status, issue/coverage state, terms, coverages, risks, documents, service team, billing, commissions, certificates, and communications.',N'Policy Detail',N'/policies/{policyId}',N'Policy Workspace; Manage assignments; Upload; Issue Cert; E-Sign; Message',N'WORKFLOW',N'Pending Issue or Issued',N'Issued or Active',N'The internal AMS policy becomes the authoritative servicing workspace while carrier legal documents remain carrier-issued artifacts.',N'Complete servicing tasks, billing, documents, and monitor endorsements and renewal schedule.',N'Policy data remains tenant-scoped and must match the confirmed binder and carrier evidence.',N'Cancel and Reinstate use explicit actions and audit history; use Remarket or Rewrite for replacement business.',N'policy workspace pending issue issued active servicing billing documents certificate',0),
(N'POLICY_CANCEL',255,N'POLICY',N'Policy Servicing',N'Cancel or reinstate policy',N'Use governed policy lifecycle actions to cancel coverage or restore a cancelled policy.',N'Policy Detail',N'/policies/{policyId}',N'Cancel; Reinstate',N'ALTERNATE',N'Active or Cancelled',N'Cancelled or Reinstated/Active',N'Policy lifecycle status and dates are updated with auditable reasons.',N'After cancellation, service remaining accounting/document obligations or reinstate when authorized.',N'Reason, effective date, permissions, carrier/customer evidence, and configured lifecycle transition requirements apply.',N'Use Rewrite or Remarket when replacement coverage is required instead of reinstatement.',N'policy cancel reinstate cancelled active lifecycle',1),
(N'ENDORSEMENT_CREATE',260,N'ENDORSEMENT',N'Policy Change',N'Create endorsement',N'Select the policy and endorsement type, effective date, reason, typed changes, comparison, and financial impact.',N'Policy Endorsements',N'/policies/endorsements',N'Create Endorsement; Save Draft; Save and Submit',N'SUBMIT',NULL,N'Draft or In Review/Pending Approval',N'An endorsement and typed policy-change rows are created; submission uses tenant-configured routing.',N'If submitted, follow the Next Action panel or assigned approval queue.',N'Active policy, configured endorsement type/options, effective date, change summary, billing/commission impact, and permissions are required.',N'Save Draft for incomplete work. Multi-change records may require specialized editing outside the single-change wizard.',N'endorsement create policy change draft submit review approval financial',0),
(N'ENDORSEMENT_REVIEW',270,N'ENDORSEMENT',N'Endorsement Review',N'Review and approve endorsement',N'Execute the tenant-configured next action, approval, rejection, or request for information.',N'Policy Endorsements',N'/policies/endorsements',N'Approve; Reject; Request Information',N'WORKFLOW',N'In Review or Pending Approval',N'Approved, Need More Info, Rejected, or Declined',N'Authority and underwriting decisions are recorded and route the endorsement to the next configured state.',N'If approved, continue configured issuance/completion. If information is requested, the assigned user must respond.',N'Assigned approver, required permission, row version, documents, authority level, and configured transition are enforced.',N'Rejection/decline closes the request. Need More Info preserves the request for correction.',N'endorsement approve reject request information pending approval review',0),
(N'ENDORSEMENT_RFI',280,N'ENDORSEMENT',N'Endorsement Information Request',N'Respond and resubmit',N'Provide requested information or documents, then return the endorsement to review.',N'Policy Endorsements',N'/policies/endorsements',N'Respond; Resubmit for review',N'WORKFLOW',N'Need More Info or Open RFI',N'Responded then In Review',N'The information request and response remain auditable while endorsement review resumes.',N'Assigned approver reviews the resubmitted endorsement.',N'Only the assigned user can respond/resubmit; required notes and due-date/document rules apply.',N'Additional information requests can repeat without deleting prior requests.',N'endorsement need more info rfi respond resubmit review',0),
(N'ENDORSEMENT_COMPLETE',290,N'ENDORSEMENT',N'Endorsement Completion',N'Complete and activate endorsement',N'Apply approved changes, create the new policy version, dispatch carrier/accounting/document work, and complete the endorsement.',N'Policy Endorsements',N'/policies/endorsements',N'Configured next action',N'WORKFLOW',N'Approved or Issued',N'Completed',N'The endorsed policy version and downstream operational records become active.',N'Return to Policy Detail and verify updated terms, documents, billing, and servicing data.',N'All configured transitions, approvals, automation, financial posting, and document requirements must succeed.',N'Use Reverse on a completed endorsement only with permission and a documented reversal reason.',N'endorsement completed issued activate policy version accounting documents reverse',0),
(N'RENEWAL_OPEN',300,N'RENEWAL',N'Renewal Intake',N'Open renewal workflow',N'Open the generated renewal record from the renewal dashboard or policy schedule and review policy, expiration, risk, premium, claims, and retention context.',N'Renewal Detail',N'/renewals/{renewalId}',N'Start Renewal',N'SUBMIT',N'Not Started',N'In Progress',N'The renewal is actively owned and available for tasks, communications, risk review, and marketing.',N'Complete renewal tasks, contact the client, review risk changes, and decide whether to remarket.',N'A valid policy/term and renewal record must exist. Assignment and timing are tenant-driven.',N'Use Non-Renewed when the carrier will not renew; use Lost when the account does not renew with the agency.',N'renewal not started start renewal in progress expiration retention',0),
(N'RENEWAL_PREPARE',310,N'RENEWAL',N'Renewal Preparation',N'Complete renewal review',N'Review risk changes, claims, premium history, retention score, tasks, and communications.',N'Renewal Detail',N'/renewals/{renewalId}',N'Protect retention; Clear tasks; New Message; Log Call',N'WORKFLOW',N'In Progress',N'In Progress',N'Renewal readiness and client/carrier communication history are updated.',N'Continue with incumbent renewal or click Remarket/Add Market when competitive terms are needed.',N'Overdue tasks, unresolved risk changes, missing client contact, claims, and required documents should be resolved before proposal.',N'High retention risk should trigger configured retention outreach or review.',N'renewal tasks communications claims risk changes retention premium history',0),
(N'RENEWAL_MARKET',320,N'RENEWAL',N'Renewal Marketing',N'Market the renewal',N'Add markets, track incumbent and alternative carrier activity, and record renewal quote options.',N'Renewal Detail',N'/renewals/{renewalId}',N'Remarket; Market renewal; Add Market',N'WORKFLOW',N'In Progress',N'Quoted',N'Renewal market actions and quote options are persisted for comparison.',N'Open Quotes, compare options, and select the recommended/customer-approved renewal terms.',N'Market, submission/risk updates, carrier contact, quote terms, and expiration timing must be complete.',N'If no viable quote exists, continue remarketing or record Non-Renewed/Lost with reason.',N'renewal remarket add market quoted incumbent alternative carrier',0),
(N'RENEWAL_PROPOSAL',330,N'RENEWAL',N'Renewal Decision',N'Build renewal proposal and bind',N'Build the renewal proposal, capture customer acceptance, and use the governed bind workflow for selected renewal terms.',N'Renewal Detail',N'/renewals/{renewalId}',N'Build Proposal; Bind',N'WORKFLOW',N'Quoted',N'Customer Accepted or Binding',N'The selected renewal quote follows proposal, authorization, bind, binder review, and policy-generation controls.',N'After confirmed renewal bind/policy term creation, mark the renewal Renewed.',N'Selected valid quote, proposal delivery, customer authorization, and carrier confirmation are required; clicking Bind alone does not create a policy.',N'If the customer declines, mark Lost; if the carrier declines renewal, mark Non-Renewed.',N'renewal proposal customer acceptance bind quoted binding',0),
(N'RENEWAL_COMPLETE',340,N'RENEWAL',N'Renewal Completion',N'Mark renewal complete',N'Close the renewal after confirmed coverage and new policy term records are complete.',N'Renewal Detail',N'/renewals/{renewalId}',N'Mark Renewed',N'SUBMIT',N'Quoted or Binding',N'Renewed',N'The renewal workflow is complete and the renewed policy term becomes the active servicing term.',N'Open Policy Detail to verify the renewed term, documents, billing, commissions, tasks, and next renewal schedule.',N'Confirmed coverage, selected terms, policy/term persistence, required documents, and completed critical tasks should be verified before closure.',N'Use Lost or Non-Renewed instead of Renewed when coverage is not retained.',N'renewal complete renewed active term lost non-renewed',0);

MERGE knowledge.WorkflowGuideStep AS target
USING
(
	SELECT CAST(NULL AS UNIQUEIDENTIFIER) AS TenantId, N'LEAD_TO_RENEWAL' AS WorkflowCode, seed.*
	FROM @Seed seed
) AS source
ON target.TenantId IS NULL AND target.WorkflowCode = source.WorkflowCode AND target.StepCode = source.StepCode
WHEN MATCHED THEN UPDATE SET
	SequenceNumber=source.SequenceNumber,
	ModuleSequenceNumber=CASE source.ModuleCode WHEN 'CRM_LEAD' THEN 10 WHEN 'CRM_OPPORTUNITY' THEN 20 WHEN 'SUBMISSION' THEN 30 WHEN 'SUBMISSION_MARKET' THEN 40 WHEN 'QUOTE_REQUEST' THEN 50 WHEN 'QUOTE' THEN 60 WHEN 'PROPOSAL' THEN 70 WHEN 'CLIENT_ACCEPTANCE' THEN 80 WHEN 'BIND_REQUEST' THEN 90 WHEN 'POLICY' THEN 100 WHEN 'ENDORSEMENT' THEN 110 WHEN 'RENEWAL' THEN 120 ELSE source.SequenceNumber END,
	ModuleDisplayName=CASE source.ModuleCode WHEN 'CRM_LEAD' THEN N'Leads' WHEN 'CRM_OPPORTUNITY' THEN N'Opportunities' WHEN 'SUBMISSION' THEN N'Submissions' WHEN 'SUBMISSION_MARKET' THEN N'Submission Markets' WHEN 'QUOTE_REQUEST' THEN N'Quote Requests' WHEN 'QUOTE' THEN N'Quotes' WHEN 'PROPOSAL' THEN N'Proposals' WHEN 'CLIENT_ACCEPTANCE' THEN N'Client Acceptance' WHEN 'BIND_REQUEST' THEN N'Bind Requests' WHEN 'POLICY' THEN N'Policies' WHEN 'ENDORSEMENT' THEN N'Endorsements' WHEN 'RENEWAL' THEN N'Renewals' ELSE REPLACE(source.ModuleCode, '_', ' ') END,
	ModuleCode=source.ModuleCode, StageName=source.StageName, StepTitle=source.StepTitle,
	StepDescription=source.StepDescription, PageName=source.PageName, PageRoute=source.PageRoute, ActionLabel=source.ActionLabel,
	NavigationRoute=CASE source.ModuleCode WHEN 'CRM_LEAD' THEN N'/crm/leads' WHEN 'CRM_OPPORTUNITY' THEN N'/crm/opportunities' WHEN 'SUBMISSION' THEN N'/submissions' WHEN 'SUBMISSION_MARKET' THEN N'/submissions' WHEN 'QUOTE_REQUEST' THEN N'/submissions/quotes' WHEN 'QUOTE' THEN N'/submissions/quotes' WHEN 'PROPOSAL' THEN N'/submissions/quotes' WHEN 'CLIENT_ACCEPTANCE' THEN N'/submissions/quotes' WHEN 'BIND_REQUEST' THEN N'/submissions/bind-requests' WHEN 'POLICY' THEN N'/policies' WHEN 'ENDORSEMENT' THEN N'/policies/endorsements' WHEN 'RENEWAL' THEN N'/renewals' ELSE source.PageRoute END,
	ActionTypeCode=source.ActionTypeCode, FromStatusCode=source.FromStatusCode, ToStatusCode=source.ToStatusCode,
	ExpectedResult=source.ExpectedResult, NextUserMove=source.NextUserMove, ValidationRequirements=source.ValidationRequirements,
	AlternatePath=source.AlternatePath, SearchKeywords=source.SearchKeywords, IsOptional=source.IsOptional, IsActive=1,
	ModifiedDateUtc=SYSUTCDATETIME(), IsDeleted=0
WHEN NOT MATCHED THEN INSERT
	(WorkflowGuideStepId,TenantId,WorkflowCode,StepCode,SequenceNumber,ModuleCode,ModuleSequenceNumber,ModuleDisplayName,StageName,StepTitle,StepDescription,PageName,PageRoute,NavigationRoute,
	 ActionLabel,ActionTypeCode,FromStatusCode,ToStatusCode,ExpectedResult,NextUserMove,ValidationRequirements,AlternatePath,SearchKeywords,
	 IsOptional,IsActive,CreatedDateUtc,IsDeleted)
VALUES
	(NEWID(),source.TenantId,source.WorkflowCode,source.StepCode,source.SequenceNumber,source.ModuleCode,
	 CASE source.ModuleCode WHEN 'CRM_LEAD' THEN 10 WHEN 'CRM_OPPORTUNITY' THEN 20 WHEN 'SUBMISSION' THEN 30 WHEN 'SUBMISSION_MARKET' THEN 40 WHEN 'QUOTE_REQUEST' THEN 50 WHEN 'QUOTE' THEN 60 WHEN 'PROPOSAL' THEN 70 WHEN 'CLIENT_ACCEPTANCE' THEN 80 WHEN 'BIND_REQUEST' THEN 90 WHEN 'POLICY' THEN 100 WHEN 'ENDORSEMENT' THEN 110 WHEN 'RENEWAL' THEN 120 ELSE source.SequenceNumber END,
	 CASE source.ModuleCode WHEN 'CRM_LEAD' THEN N'Leads' WHEN 'CRM_OPPORTUNITY' THEN N'Opportunities' WHEN 'SUBMISSION' THEN N'Submissions' WHEN 'SUBMISSION_MARKET' THEN N'Submission Markets' WHEN 'QUOTE_REQUEST' THEN N'Quote Requests' WHEN 'QUOTE' THEN N'Quotes' WHEN 'PROPOSAL' THEN N'Proposals' WHEN 'CLIENT_ACCEPTANCE' THEN N'Client Acceptance' WHEN 'BIND_REQUEST' THEN N'Bind Requests' WHEN 'POLICY' THEN N'Policies' WHEN 'ENDORSEMENT' THEN N'Endorsements' WHEN 'RENEWAL' THEN N'Renewals' ELSE REPLACE(source.ModuleCode, '_', ' ') END,
	 source.StageName,source.StepTitle,source.StepDescription,source.PageName,source.PageRoute,
	 CASE source.ModuleCode WHEN 'CRM_LEAD' THEN N'/crm/leads' WHEN 'CRM_OPPORTUNITY' THEN N'/crm/opportunities' WHEN 'SUBMISSION' THEN N'/submissions' WHEN 'SUBMISSION_MARKET' THEN N'/submissions' WHEN 'QUOTE_REQUEST' THEN N'/submissions/quotes' WHEN 'QUOTE' THEN N'/submissions/quotes' WHEN 'PROPOSAL' THEN N'/submissions/quotes' WHEN 'CLIENT_ACCEPTANCE' THEN N'/submissions/quotes' WHEN 'BIND_REQUEST' THEN N'/submissions/bind-requests' WHEN 'POLICY' THEN N'/policies' WHEN 'ENDORSEMENT' THEN N'/policies/endorsements' WHEN 'RENEWAL' THEN N'/renewals' ELSE source.PageRoute END,
	 source.ActionLabel,source.ActionTypeCode,source.FromStatusCode,source.ToStatusCode,
	 source.ExpectedResult,source.NextUserMove,source.ValidationRequirements,source.AlternatePath,source.SearchKeywords,source.IsOptional,1,SYSUTCDATETIME(),0);
