<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <Content Include="..\..\..\..\..\..\OneDrive\Documents\1–61 placement map.txt" Link="wwwroot\1–61 placement map.txt" />
  </ItemGroup>
  <ItemGroup>
	<ProjectReference Include="..\Legal.Application\Legal.Application.csproj" />
  </ItemGroup>
</Project>
