<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
	<ProjectReference Include="..\Legal.Application\Legal.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Components\Pages\Legal\" />
    <Folder Include="wwwroot\image\" />
  </ItemGroup>
</Project>
