<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup>  <UserSecretsId>3281fea9-48a3-4794-8cc9-4edf50419b92</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
	<ProjectReference Include="..\Legal.Application\Legal.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Components\Pages\Legal\" />
  </ItemGroup>
</Project>
